// Package uigen generates package ui's typed builders from package
// widget's source: one builder per widget type, a constructor per New*
// function, a chainable method per setter, adder, binder and exported
// field, and the props every widget shares through its embedded node.
package uigen

import (
	"bytes"
	"cmp"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"unicode"
)

const widgetPath = "github.com/stubbedev/gelm/widget"

var mutators = []string{"Set", "Add", "Bind", "Attach", "Append", "Insert", "Pack", "Push"}

var plumbing = map[string]bool{
	"SetHovered": true, "SetPressed": true, "SetFocused": true, "SetDragOver": true,
	"InsertRune": true, "SetParent": true,
}

var reserved = map[string]bool{
	"Build": true, "Widget": true, "Ref": true, "With": true, "Watch": true, "Track": true,
	"Font": true, "Size": true, "Ink": true,
}

var builtins = map[string]bool{
	"bool": true, "byte": true, "rune": true, "string": true, "error": true, "any": true,
	"int": true, "int8": true, "int16": true, "int32": true, "int64": true,
	"uint": true, "uint8": true, "uint16": true, "uint32": true, "uint64": true, "uintptr": true,
	"float32": true, "float64": true, "complex64": true, "complex128": true, "comparable": true,
}

type source struct {
	types   map[string]*ast.TypeSpec
	fields  map[string][]*ast.Field
	imports map[*ast.TypeSpec]map[string]string
	ctors   []*ast.FuncDecl
	methods map[string][]*ast.FuncDecl
	fileOf  map[ast.Node]map[string]string
}

type gen struct {
	src     *source
	used    map[string]string
	out     bytes.Buffer
	widgets map[string]bool
}

// Generate renders the ui package's generated builders from the widget
// package in dir.
func Generate(dir string) ([]byte, error) {
	src, err := load(dir)
	if err != nil {
		return nil, err
	}
	g := &gen{src: src, used: map[string]string{}, widgets: map[string]bool{}}
	for name := range src.types {
		if g.isWidget(name) {
			g.widgets[name] = true
		}
	}
	g.emitNodeProps()
	for _, name := range slices.Sorted(maps.Keys(g.widgets)) {
		g.emitBuilder(name)
	}
	var file bytes.Buffer
	file.WriteString("// Code generated by internal/uigen from package widget; DO NOT EDIT.\n\npackage ui\n\nimport (\n")
	g.used["widget"] = widgetPath
	var std, module []string
	for _, name := range slices.Sorted(maps.Keys(g.used)) {
		line := fmt.Sprintf("\t%q\n", g.used[name])
		if strings.Contains(g.used[name], ".") {
			module = append(module, line)
		} else {
			std = append(std, line)
		}
	}
	file.WriteString(strings.Join(std, "") + "\n" + strings.Join(module, "") + ")\n\n")
	file.Write(g.out.Bytes())
	formatted, err := format.Source(file.Bytes())
	if err != nil {
		return nil, fmt.Errorf("uigen: formatting the generated builders: %w\n%s", err, file.Bytes())
	}
	return formatted, nil
}

func load(dir string) (*source, error) {
	fset := token.NewFileSet()
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("uigen: reading %s: %w", dir, err)
	}
	src := &source{
		types:   map[string]*ast.TypeSpec{},
		fields:  map[string][]*ast.Field{},
		imports: map[*ast.TypeSpec]map[string]string{},
		methods: map[string][]*ast.FuncDecl{},
		fileOf:  map[ast.Node]map[string]string{},
	}
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		f, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, parser.SkipObjectResolution)
		if err != nil {
			return nil, fmt.Errorf("uigen: parsing %s: %w", name, err)
		}
		if strings.HasSuffix(f.Name.Name, "_test") {
			continue
		}
		imports := fileImports(f)
		for _, decl := range f.Decls {
			switch d := decl.(type) {
			case *ast.GenDecl:
				for _, spec := range d.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok || ts.Assign.IsValid() {
						continue
					}
					st, ok := ts.Type.(*ast.StructType)
					if !ok {
						continue
					}
					src.types[ts.Name.Name] = ts
					src.fields[ts.Name.Name] = st.Fields.List
					src.fileOf[ts] = imports
				}
			case *ast.FuncDecl:
				src.fileOf[d] = imports
				if d.Recv == nil {
					if strings.HasPrefix(d.Name.Name, "New") && d.Name.IsExported() {
						src.ctors = append(src.ctors, d)
					}
					continue
				}
				if recv := receiverName(d); recv != "" {
					src.methods[recv] = append(src.methods[recv], d)
				}
			}
		}
	}
	slices.SortFunc(src.ctors, func(a, b *ast.FuncDecl) int { return cmp.Compare(a.Name.Name, b.Name.Name) })
	for k := range src.methods {
		slices.SortStableFunc(src.methods[k], func(a, b *ast.FuncDecl) int { return cmp.Compare(a.Name.Name, b.Name.Name) })
	}
	return src, nil
}

func fileImports(f *ast.File) map[string]string {
	m := map[string]string{}
	for _, imp := range f.Imports {
		path := strings.Trim(imp.Path.Value, `"`)
		name := path[strings.LastIndex(path, "/")+1:]
		if imp.Name != nil {
			name = imp.Name.Name
		}
		m[name] = path
	}
	return m
}

func receiverName(d *ast.FuncDecl) string {
	t := d.Recv.List[0].Type
	if s, ok := t.(*ast.StarExpr); ok {
		t = s.X
	}
	switch x := t.(type) {
	case *ast.Ident:
		return x.Name
	case *ast.IndexExpr:
		if id, ok := x.X.(*ast.Ident); ok {
			return id.Name
		}
	case *ast.IndexListExpr:
		if id, ok := x.X.(*ast.Ident); ok {
			return id.Name
		}
	}
	return ""
}

func (g *gen) embedsNode(name string, seen map[string]bool) bool {
	if seen[name] {
		return false
	}
	seen[name] = true
	for _, f := range g.src.fields[name] {
		if len(f.Names) != 0 {
			continue
		}
		t := f.Type
		if s, ok := t.(*ast.StarExpr); ok {
			t = s.X
		}
		id, ok := t.(*ast.Ident)
		if !ok {
			continue
		}
		if id.Name == "node" || g.embedsNode(id.Name, seen) {
			return true
		}
	}
	return false
}

func (g *gen) isWidget(name string) bool {
	return ast.IsExported(name) && g.embedsNode(name, map[string]bool{}) &&
		slices.ContainsFunc(g.methodsOf(name), func(d *ast.FuncDecl) bool { return d.Name.Name == "Paint" })
}

type typeParams struct {
	decl string
	use  string
}

func (g *gen) typeParams(fl *ast.FieldList, imports map[string]string) typeParams {
	if fl == nil || len(fl.List) == 0 {
		return typeParams{}
	}
	var decl, use []string
	for _, f := range fl.List {
		names := make([]string, len(f.Names))
		for i, n := range f.Names {
			names[i] = n.Name
			use = append(use, n.Name)
		}
		decl = append(decl, strings.Join(names, ", ")+" "+g.typ(f.Type, imports, nil))
	}
	return typeParams{decl: "[" + strings.Join(decl, ", ") + "]", use: "[" + strings.Join(use, ", ") + "]"}
}

func (g *gen) typ(e ast.Expr, imports map[string]string, tparams map[string]bool) string {
	switch x := e.(type) {
	case *ast.Ident:
		if builtins[x.Name] || tparams[x.Name] || !ast.IsExported(x.Name) {
			return x.Name
		}
		return "widget." + x.Name
	case *ast.SelectorExpr:
		id, ok := x.X.(*ast.Ident)
		if !ok {
			panic(fmt.Sprintf("uigen: unsupported qualified type %T", x.X))
		}
		pkg := id.Name
		path, ok := imports[pkg]
		if !ok {
			panic(fmt.Sprintf("uigen: package %s is not imported where %s.%s is used", pkg, pkg, x.Sel.Name))
		}
		g.used[pkg] = path
		return pkg + "." + x.Sel.Name
	case *ast.StarExpr:
		return "*" + g.typ(x.X, imports, tparams)
	case *ast.ArrayType:
		if x.Len == nil {
			return "[]" + g.typ(x.Elt, imports, tparams)
		}
		return "[" + exprString(x.Len) + "]" + g.typ(x.Elt, imports, tparams)
	case *ast.MapType:
		return "map[" + g.typ(x.Key, imports, tparams) + "]" + g.typ(x.Value, imports, tparams)
	case *ast.Ellipsis:
		return "..." + g.typ(x.Elt, imports, tparams)
	case *ast.FuncType:
		return "func" + g.signature(x, imports, tparams)
	case *ast.InterfaceType:
		if x.Methods == nil || len(x.Methods.List) == 0 {
			return "interface{}"
		}
	case *ast.ChanType:
		dir := "chan "
		switch x.Dir {
		case ast.RECV:
			dir = "<-chan "
		case ast.SEND:
			dir = "chan<- "
		}
		return dir + g.typ(x.Value, imports, tparams)
	case *ast.IndexExpr:
		return g.typ(x.X, imports, tparams) + "[" + g.typ(x.Index, imports, tparams) + "]"
	case *ast.IndexListExpr:
		args := make([]string, len(x.Indices))
		for i, ix := range x.Indices {
			args[i] = g.typ(ix, imports, tparams)
		}
		return g.typ(x.X, imports, tparams) + "[" + strings.Join(args, ", ") + "]"
	case *ast.BinaryExpr:
		return g.typ(x.X, imports, tparams) + " " + x.Op.String() + " " + g.typ(x.Y, imports, tparams)
	case *ast.UnaryExpr:
		return x.Op.String() + g.typ(x.X, imports, tparams)
	}
	panic(fmt.Sprintf("uigen: unsupported type expression %T", e))
}

func (g *gen) signature(ft *ast.FuncType, imports map[string]string, tparams map[string]bool) string {
	var params []string
	for _, f := range ft.Params.List {
		t := g.typ(f.Type, imports, tparams)
		if len(f.Names) == 0 {
			params = append(params, t)
			continue
		}
		for _, n := range f.Names {
			params = append(params, n.Name+" "+t)
		}
	}
	s := "(" + strings.Join(params, ", ") + ")"
	if ft.Results == nil {
		return s
	}
	var results []string
	for _, f := range ft.Results.List {
		t := g.typ(f.Type, imports, tparams)
		n := max(len(f.Names), 1)
		for range n {
			results = append(results, t)
		}
	}
	if len(results) == 1 {
		return s + " " + results[0]
	}
	return s + " (" + strings.Join(results, ", ") + ")"
}

func exprString(e ast.Expr) string {
	if b, ok := e.(*ast.BasicLit); ok {
		return b.Value
	}
	panic(fmt.Sprintf("uigen: unsupported array length %T", e))
}

type param struct {
	name   string
	decl   string
	arg    string
	envArg string
}

var generatorNames = map[string]bool{"b": true, "s": true, "w": true, "get": true, "value": true, "fn": true}

func rename(t ast.Expr) string {
	for {
		switch x := t.(type) {
		case *ast.StarExpr:
			t = x.X
			continue
		case *ast.Ellipsis:
			t = x.Elt
			continue
		case *ast.ArrayType:
			t = x.Elt
			continue
		case *ast.IndexExpr:
			t = x.X
			continue
		case *ast.SelectorExpr:
			t = x.Sel
			continue
		case *ast.Ident:
			switch x.Name {
			case "Widget":
				return "child"
			case "string":
				return "text"
			}
			if builtins[x.Name] {
				return "arg"
			}
			return strings.ToLower(x.Name[:1]) + x.Name[1:]
		}
		return "arg"
	}
}

func (g *gen) mapParam(name string, t ast.Expr, imports map[string]string, tparams map[string]bool) param {
	if generatorNames[name] {
		name = rename(t)
	}
	variadic := false
	if el, ok := t.(*ast.Ellipsis); ok {
		variadic = true
		t = el.Elt
	}
	prefix := ""
	if variadic {
		prefix = "..."
	}
	if id, ok := t.(*ast.Ident); ok && id.Name == "Widget" {
		if variadic {
			return param{name: name, decl: name + " ...Node", arg: "buildAll(s, " + name + ")..."}
		}
		return param{name: name, decl: name + " Node", arg: "build(s, " + name + ")"}
	}
	if at, ok := t.(*ast.ArrayType); ok && at.Len == nil {
		if id, ok := at.Elt.(*ast.Ident); ok && id.Name == "Widget" && !variadic {
			return param{name: name, decl: name + " []Node", arg: "buildAll(s, " + name + ")"}
		}
	}
	if st, ok := t.(*ast.StarExpr); ok && !variadic {
		if id, ok := st.X.(*ast.Ident); ok && g.widgets[id.Name] && g.src.types[id.Name].TypeParams == nil {
			return param{name: name, decl: name + " Of[*widget." + id.Name + "]", arg: "buildOf(s, " + name + ")"}
		}
	}
	tt := g.typ(t, imports, tparams)
	return param{name: name, decl: name + " " + prefix + tt, arg: name + prefix}
}

func (g *gen) params(ft *ast.FuncType, imports map[string]string, tparams map[string]bool, ctor bool) ([]param, bool) {
	var ps []param
	for _, f := range ft.Params.List {
		if len(f.Names) == 0 {
			return nil, false
		}
		for _, n := range f.Names {
			if ctor {
				if env := envParam(n.Name, f.Type); env != "" {
					ps = append(ps, param{name: n.Name, envArg: env})
					continue
				}
			}
			ps = append(ps, g.mapParam(n.Name, f.Type, imports, tparams))
		}
	}
	return ps, true
}

func envParam(name string, t ast.Expr) string {
	sel, ok := t.(*ast.SelectorExpr)
	switch {
	case name == "face" && ok && sel.Sel.Name == "Font":
		return "s.face(b.face)"
	case name == "sizePx":
		if id, ok := t.(*ast.Ident); ok && id.Name == "float64" {
			return "s.size(b.size)"
		}
	case name == "color" && ok && sel.Sel.Name == "Color":
		return "s.ink(b.ink)"
	}
	return ""
}

func (g *gen) emitNodeProps() {
	var iface []string
	var methods bytes.Buffer
	for _, d := range g.src.methods["node"] {
		name, ok := builderName(d.Name.Name)
		if !ok || d.Type.Results != nil || reserved[name] {
			continue
		}
		imports := g.src.fileOf[d]
		ps, ok := g.params(d.Type, imports, nil, false)
		if !ok {
			continue
		}
		iface = append(iface, d.Name.Name+g.signature(d.Type, imports, nil))
		fmt.Fprintf(&methods, "// %s calls %s on the widget.\n", name, d.Name.Name)
		fmt.Fprintf(&methods, "func (b *base[W, B]) %s(%s) B {\n", name, decls(ps))
		fmt.Fprintf(&methods, "\tb.do(func(s *Scope, w W) { w.%s(%s) })\n\treturn b.self\n}\n\n", d.Name.Name, args(ps))
		if strings.HasPrefix(d.Name.Name, "Set") && len(ps) == 1 && ps[0].arg == ps[0].name && !isFunc(d.Type.Params.List[0].Type) {
			ptype := strings.TrimPrefix(ps[0].decl, ps[0].name+" ")
			fmt.Fprintf(&methods, "// Watch%s re-applies %s with get's value after every update.\n", name, d.Name.Name)
			fmt.Fprintf(&methods, "func (b *base[W, B]) Watch%s(get func() %s) B {\n", name, ptype)
			fmt.Fprintf(&methods, "\tb.watch(func(w W) { w.%s(get()) })\n\treturn b.self\n}\n\n", d.Name.Name)
		}
	}
	g.out.WriteString("type nodeProps interface {\n\twidget.Widget\n")
	for _, m := range iface {
		g.out.WriteString("\t" + m + "\n")
	}
	g.out.WriteString("}\n\n")
	g.out.Write(methods.Bytes())
}

func builderName(method string) (string, bool) {
	if plumbing[method] || !ast.IsExported(method) {
		return "", false
	}
	for _, p := range mutators {
		if !strings.HasPrefix(method, p) {
			continue
		}
		if p != "Set" {
			return method, true
		}
		rest := strings.TrimPrefix(method, "Set")
		if rest == "" || !unicode.IsUpper(rune(rest[0])) {
			return "", false
		}
		return rest, true
	}
	return "", false
}

func decls(ps []param) string {
	var out []string
	for _, p := range ps {
		if p.envArg == "" {
			out = append(out, p.decl)
		}
	}
	return strings.Join(out, ", ")
}

func args(ps []param) string {
	out := make([]string, len(ps))
	for i, p := range ps {
		out[i] = cmp.Or(p.envArg, p.arg)
	}
	return strings.Join(out, ", ")
}

func (g *gen) emitBuilder(name string) {
	ts := g.src.types[name]
	imports := g.src.fileOf[ts]
	tp := g.typeParams(ts.TypeParams, imports)
	tparams := map[string]bool{}
	if ts.TypeParams != nil {
		for _, f := range ts.TypeParams.List {
			for _, n := range f.Names {
				tparams[n.Name] = true
			}
		}
	}
	bt := name + "Builder" + tp.use
	wt := "*widget." + name + tp.use

	var ctors bytes.Buffer
	needs := map[string]bool{}
	for _, d := range g.src.ctors {
		if !g.returns(d, name) {
			continue
		}
		fimports := g.src.fileOf[d]
		ctp := g.typeParams(d.Type.TypeParams, fimports)
		ctparams := maps.Clone(tparams)
		if d.Type.TypeParams != nil {
			for _, f := range d.Type.TypeParams.List {
				for _, n := range f.Names {
					ctparams[n.Name] = true
				}
			}
		}
		ps, ok := g.params(d.Type, fimports, ctparams, true)
		if !ok {
			continue
		}
		for _, p := range ps {
			switch p.envArg {
			case "s.face(b.face)":
				needs["face"] = true
			case "s.size(b.size)":
				needs["size"] = true
			case "s.ink(b.ink)":
				needs["ink"] = true
			}
		}
		fn := strings.TrimPrefix(d.Name.Name, "New")
		fmt.Fprintf(&ctors, "// %s builds a widget.%s with widget.%s.\n", fn, name, d.Name.Name)
		fmt.Fprintf(&ctors, "func %s%s(%s) *%s {\n", fn, ctp.decl, decls(ps), bt)
		fmt.Fprintf(&ctors, "\tb := &%s{}\n", bt)
		fmt.Fprintf(&ctors, "\tb.init(b, func(s *Scope) %s { return widget.%s%s(%s) })\n\treturn b\n}\n\n", wt, d.Name.Name, ctp.use, args(ps))
	}

	fmt.Fprintf(&g.out, "// %sBuilder builds a widget.%s.\n", name, name)
	fmt.Fprintf(&g.out, "type %sBuilder%s struct {\n\tbase[%s, *%s]\n", name, tp.decl, wt, bt)
	if needs["face"] || needs["size"] {
		g.used["render"] = "github.com/stubbedev/gelm/render"
		g.out.WriteString("\tface render.Font\n\tsize float64\n")
	}
	if needs["ink"] {
		g.used["render"] = "github.com/stubbedev/gelm/render"
		g.out.WriteString("\tink render.Color\n")
	}
	g.out.WriteString("}\n\n")
	g.out.Write(ctors.Bytes())
	if needs["face"] || needs["size"] {
		fmt.Fprintf(&g.out, "// Font overrides the environment's typeface and size for this widget; zero values keep the environment's.\n")
		fmt.Fprintf(&g.out, "func (b *%s) Font(face render.Font, sizePx float64) *%s {\n\tb.face, b.size = face, sizePx\n\treturn b\n}\n\n", bt, bt)
	}
	if needs["ink"] {
		fmt.Fprintf(&g.out, "// Ink overrides the environment's text color for this widget.\n")
		fmt.Fprintf(&g.out, "func (b *%s) Ink(c render.Color) *%s {\n\tb.ink = c\n\treturn b\n}\n\n", bt, bt)
	}

	taken := map[string]bool{}
	for _, d := range g.src.methods["node"] {
		if n, ok := builderName(d.Name.Name); ok {
			taken[n] = true
			taken["Watch"+n] = true
		}
	}
	for n := range reserved {
		taken[n] = true
	}
	for _, d := range g.methodsOf(name) {
		bname, ok := builderName(d.Name.Name)
		if !ok || taken[bname] || !resultsOK(d) {
			continue
		}
		mimports := g.src.fileOf[d]
		ps, ok := g.params(d.Type, mimports, tparams, false)
		if !ok {
			continue
		}
		taken[bname] = true
		call := fmt.Sprintf("w.%s(%s)", d.Name.Name, args(ps))
		if strings.HasPrefix(d.Name.Name, "Bind") && returnsFunc(d) {
			call = "s.onShutdown(" + call + ")"
		}
		fmt.Fprintf(&g.out, "// %s calls (*widget.%s).%s.\n", bname, name, d.Name.Name)
		fmt.Fprintf(&g.out, "func (b *%s) %s(%s) *%s {\n", bt, bname, decls(ps), bt)
		fmt.Fprintf(&g.out, "\tb.do(func(s *Scope, w %s) { %s })\n\treturn b\n}\n\n", wt, call)
		if strings.HasPrefix(d.Name.Name, "Set") && len(ps) == 1 && ps[0].arg == ps[0].name && !isFunc(d.Type.Params.List[0].Type) {
			wname := "Watch" + bname
			if !taken[wname] {
				taken[wname] = true
				ptype := strings.TrimPrefix(ps[0].decl, ps[0].name+" ")
				fmt.Fprintf(&g.out, "// %s re-applies %s with get's value after every update.\n", wname, d.Name.Name)
				fmt.Fprintf(&g.out, "func (b *%s) %s(get func() %s) *%s {\n", bt, wname, ptype, bt)
				fmt.Fprintf(&g.out, "\tb.watch(func(w %s) { w.%s(get()) })\n\treturn b\n}\n\n", wt, d.Name.Name)
			}
		}
	}
	for _, fl := range g.fieldsOf(name) {
		for _, n := range fl.f.Names {
			if !n.IsExported() || taken[n.Name] {
				continue
			}
			taken[n.Name] = true
			t := g.typ(fl.f.Type, fl.imports, tparams)
			arg := "value"
			if isFunc(fl.f.Type) {
				arg = "fn"
			}
			fmt.Fprintf(&g.out, "// %s sets the widget's %s field.\n", n.Name, n.Name)
			fmt.Fprintf(&g.out, "func (b *%s) %s(%s %s) *%s {\n", bt, n.Name, arg, t, bt)
			fmt.Fprintf(&g.out, "\tb.do(func(_ *Scope, w %s) { w.%s = %s })\n\treturn b\n}\n\n", wt, n.Name, arg)
		}
	}
}

func (g *gen) methodsOf(name string) []*ast.FuncDecl {
	out := slices.Clone(g.src.methods[name])
	for _, f := range g.src.fields[name] {
		if len(f.Names) != 0 {
			continue
		}
		t := f.Type
		if s, ok := t.(*ast.StarExpr); ok {
			t = s.X
		}
		if id, ok := t.(*ast.Ident); ok && id.Name != "node" && g.src.types[id.Name] != nil {
			for _, d := range g.methodsOf(id.Name) {
				if !slices.ContainsFunc(out, func(o *ast.FuncDecl) bool { return o.Name.Name == d.Name.Name }) {
					out = append(out, d)
				}
			}
		}
	}
	return out
}

type field struct {
	f       *ast.Field
	imports map[string]string
}

func (g *gen) fieldsOf(name string) []field {
	var own, promoted []field
	imports := g.src.fileOf[g.src.types[name]]
	for _, f := range g.src.fields[name] {
		if len(f.Names) != 0 {
			own = append(own, field{f: f, imports: imports})
			continue
		}
		t := f.Type
		if s, ok := t.(*ast.StarExpr); ok {
			t = s.X
		}
		if id, ok := t.(*ast.Ident); ok && id.Name != "node" && g.src.types[id.Name] != nil {
			promoted = append(promoted, g.fieldsOf(id.Name)...)
		}
	}
	return append(own, promoted...)
}

func (g *gen) returns(d *ast.FuncDecl, name string) bool {
	if d.Type.Results == nil || len(d.Type.Results.List) != 1 || len(d.Type.Results.List[0].Names) > 1 {
		return false
	}
	st, ok := d.Type.Results.List[0].Type.(*ast.StarExpr)
	if !ok {
		return false
	}
	switch x := st.X.(type) {
	case *ast.Ident:
		return x.Name == name
	case *ast.IndexExpr:
		id, ok := x.X.(*ast.Ident)
		return ok && id.Name == name
	case *ast.IndexListExpr:
		id, ok := x.X.(*ast.Ident)
		return ok && id.Name == name
	}
	return false
}

func resultsOK(d *ast.FuncDecl) bool {
	if d.Type.Results == nil {
		return true
	}
	for _, f := range d.Type.Results.List {
		if id, ok := f.Type.(*ast.Ident); ok && id.Name == "error" {
			return false
		}
	}
	return true
}

func isFunc(t ast.Expr) bool {
	_, ok := t.(*ast.FuncType)
	return ok
}

func returnsFunc(d *ast.FuncDecl) bool {
	if d.Type.Results == nil || len(d.Type.Results.List) != 1 {
		return false
	}
	ft, ok := d.Type.Results.List[0].Type.(*ast.FuncType)
	return ok && len(ft.Params.List) == 0 && ft.Results == nil
}
