// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: alpha-modifier-v1.xml
// Do not edit

// Package wlr implements the alpha_modifier_v1 protocol
package wlr

import ()

// WpAlphaModifierV1ErrorAlreadyConstructed means wl_surface already has a alpha modifier object
const WpAlphaModifierV1ErrorAlreadyConstructed = 0

// WpAlphaModifierSurfaceV1ErrorNoSurface means wl_surface was destroyed
const WpAlphaModifierSurfaceV1ErrorNoSurface = 0

// WpAlphaModifierV1 surface alpha modifier manager
type WpAlphaModifierV1 struct {
	BaseProxy
}

// NewWpAlphaModifierV1 is a constructor for the WpAlphaModifierV1 object
func NewWpAlphaModifierV1(ctx *Context) *WpAlphaModifierV1 {
	ret := new(WpAlphaModifierV1)
	ctx.Register(ret)
	return ret
}

// Destroy destroy the alpha modifier manager object
func (p *WpAlphaModifierV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// GetSurface create a new alpha modifier surface object
func (p *WpAlphaModifierV1) GetSurface(Surface *Surface) (*WpAlphaModifierSurfaceV1, error) {
	retId := NewWpAlphaModifierSurfaceV1(p.Context())
	return retId, p.Context().SendRequest(p, 1, retId, Surface)
}

// Dispatch dispatches event for object WpAlphaModifierV1
func (p *WpAlphaModifierV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// WpAlphaModifierSurfaceV1 alpha modifier object for a surface
type WpAlphaModifierSurfaceV1 struct {
	BaseProxy
}

// NewWpAlphaModifierSurfaceV1 is a constructor for the WpAlphaModifierSurfaceV1 object
func NewWpAlphaModifierSurfaceV1(ctx *Context) *WpAlphaModifierSurfaceV1 {
	ret := new(WpAlphaModifierSurfaceV1)
	ctx.Register(ret)
	return ret
}

// Destroy destroy the alpha modifier object
func (p *WpAlphaModifierSurfaceV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// SetMultiplier specify the alpha multiplier
func (p *WpAlphaModifierSurfaceV1) SetMultiplier(Factor uint32) error {

	return p.Context().SendRequest(p, 1, Factor)
}

// Dispatch dispatches event for object WpAlphaModifierSurfaceV1
func (p *WpAlphaModifierSurfaceV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}
