// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: content-type-v1.xml
// Do not edit

// Package wlr implements the content_type_v1 protocol
package wlr

import ()

// WpContentTypeManagerV1ErrorAlreadyConstructed means wl_surface already has a content type object
const WpContentTypeManagerV1ErrorAlreadyConstructed = 0

// WpContentTypeV1TypeNone
const WpContentTypeV1TypeNone = 0

// WpContentTypeV1TypePhoto
const WpContentTypeV1TypePhoto = 1

// WpContentTypeV1TypeVideo
const WpContentTypeV1TypeVideo = 2

// WpContentTypeV1TypeGame
const WpContentTypeV1TypeGame = 3

// WpContentTypeManagerV1 surface content type manager
type WpContentTypeManagerV1 struct {
	BaseProxy
}

// NewWpContentTypeManagerV1 is a constructor for the WpContentTypeManagerV1 object
func NewWpContentTypeManagerV1(ctx *Context) *WpContentTypeManagerV1 {
	ret := new(WpContentTypeManagerV1)
	ctx.Register(ret)
	return ret
}

// Destroy destroy the content type manager object
func (p *WpContentTypeManagerV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// GetSurfaceType create a new content type object
func (p *WpContentTypeManagerV1) GetSurfaceType(Surface *Surface) (*WpContentTypeV1, error) {
	retId := NewWpContentTypeV1(p.Context())
	return retId, p.Context().SendRequest(p, 1, retId, Surface)
}

// Dispatch dispatches event for object WpContentTypeManagerV1
func (p *WpContentTypeManagerV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// WpContentTypeV1 content type object for a surface
type WpContentTypeV1 struct {
	BaseProxy
}

// NewWpContentTypeV1 is a constructor for the WpContentTypeV1 object
func NewWpContentTypeV1(ctx *Context) *WpContentTypeV1 {
	ret := new(WpContentTypeV1)
	ctx.Register(ret)
	return ret
}

// Destroy destroy the content type object
func (p *WpContentTypeV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// SetType specify the content type
func (p *WpContentTypeV1) SetType(Type uint32) error {

	return p.Context().SendRequest(p, 1, Type)
}

// Dispatch dispatches event for object WpContentTypeV1
func (p *WpContentTypeV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}
