// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: cursor-shape-v1.xml
// Do not edit

// Package wlr implements the cursor_shape_v1 protocol
package wlr

import ()

// WpCursorShapeDeviceV1ShapeDefault means default cursor
const WpCursorShapeDeviceV1ShapeDefault = 1

// WpCursorShapeDeviceV1ShapeContextMenu means a context menu is available for the object under the cursor
const WpCursorShapeDeviceV1ShapeContextMenu = 2

// WpCursorShapeDeviceV1ShapeHelp means help is available for the object under the cursor
const WpCursorShapeDeviceV1ShapeHelp = 3

// WpCursorShapeDeviceV1ShapePointer means pointer that indicates a link or another interactive element
const WpCursorShapeDeviceV1ShapePointer = 4

// WpCursorShapeDeviceV1ShapeProgress means progress indicator
const WpCursorShapeDeviceV1ShapeProgress = 5

// WpCursorShapeDeviceV1ShapeWait means program is busy, user should wait
const WpCursorShapeDeviceV1ShapeWait = 6

// WpCursorShapeDeviceV1ShapeCell means a cell or set of cells may be selected
const WpCursorShapeDeviceV1ShapeCell = 7

// WpCursorShapeDeviceV1ShapeCrosshair means simple crosshair
const WpCursorShapeDeviceV1ShapeCrosshair = 8

// WpCursorShapeDeviceV1ShapeText means text may be selected
const WpCursorShapeDeviceV1ShapeText = 9

// WpCursorShapeDeviceV1ShapeVerticalText means vertical text may be selected
const WpCursorShapeDeviceV1ShapeVerticalText = 10

// WpCursorShapeDeviceV1ShapeAlias means drag-and-drop: alias of/shortcut to something is to be created
const WpCursorShapeDeviceV1ShapeAlias = 11

// WpCursorShapeDeviceV1ShapeCopy means drag-and-drop: something is to be copied
const WpCursorShapeDeviceV1ShapeCopy = 12

// WpCursorShapeDeviceV1ShapeMove means drag-and-drop: something is to be moved
const WpCursorShapeDeviceV1ShapeMove = 13

// WpCursorShapeDeviceV1ShapeNoDrop means drag-and-drop: the dragged item cannot be dropped at the current cursor location
const WpCursorShapeDeviceV1ShapeNoDrop = 14

// WpCursorShapeDeviceV1ShapeNotAllowed means drag-and-drop: the requested action will not be carried out
const WpCursorShapeDeviceV1ShapeNotAllowed = 15

// WpCursorShapeDeviceV1ShapeGrab means drag-and-drop: something can be grabbed
const WpCursorShapeDeviceV1ShapeGrab = 16

// WpCursorShapeDeviceV1ShapeGrabbing means drag-and-drop: something is being grabbed
const WpCursorShapeDeviceV1ShapeGrabbing = 17

// WpCursorShapeDeviceV1ShapeEResize means resizing: the east border is to be moved
const WpCursorShapeDeviceV1ShapeEResize = 18

// WpCursorShapeDeviceV1ShapeNResize means resizing: the north border is to be moved
const WpCursorShapeDeviceV1ShapeNResize = 19

// WpCursorShapeDeviceV1ShapeNeResize means resizing: the north-east corner is to be moved
const WpCursorShapeDeviceV1ShapeNeResize = 20

// WpCursorShapeDeviceV1ShapeNwResize means resizing: the north-west corner is to be moved
const WpCursorShapeDeviceV1ShapeNwResize = 21

// WpCursorShapeDeviceV1ShapeSResize means resizing: the south border is to be moved
const WpCursorShapeDeviceV1ShapeSResize = 22

// WpCursorShapeDeviceV1ShapeSeResize means resizing: the south-east corner is to be moved
const WpCursorShapeDeviceV1ShapeSeResize = 23

// WpCursorShapeDeviceV1ShapeSwResize means resizing: the south-west corner is to be moved
const WpCursorShapeDeviceV1ShapeSwResize = 24

// WpCursorShapeDeviceV1ShapeWResize means resizing: the west border is to be moved
const WpCursorShapeDeviceV1ShapeWResize = 25

// WpCursorShapeDeviceV1ShapeEwResize means resizing: the east and west borders are to be moved
const WpCursorShapeDeviceV1ShapeEwResize = 26

// WpCursorShapeDeviceV1ShapeNsResize means resizing: the north and south borders are to be moved
const WpCursorShapeDeviceV1ShapeNsResize = 27

// WpCursorShapeDeviceV1ShapeNeswResize means resizing: the north-east and south-west corners are to be moved
const WpCursorShapeDeviceV1ShapeNeswResize = 28

// WpCursorShapeDeviceV1ShapeNwseResize means resizing: the north-west and south-east corners are to be moved
const WpCursorShapeDeviceV1ShapeNwseResize = 29

// WpCursorShapeDeviceV1ShapeColResize means resizing: that the item/column can be resized horizontally
const WpCursorShapeDeviceV1ShapeColResize = 30

// WpCursorShapeDeviceV1ShapeRowResize means resizing: that the item/row can be resized vertically
const WpCursorShapeDeviceV1ShapeRowResize = 31

// WpCursorShapeDeviceV1ShapeAllScroll means something can be scrolled in any direction
const WpCursorShapeDeviceV1ShapeAllScroll = 32

// WpCursorShapeDeviceV1ShapeZoomIn means something can be zoomed in
const WpCursorShapeDeviceV1ShapeZoomIn = 33

// WpCursorShapeDeviceV1ShapeZoomOut means something can be zoomed out
const WpCursorShapeDeviceV1ShapeZoomOut = 34

// WpCursorShapeDeviceV1ShapeDndAsk means drag-and-drop: the user will select which action will be carried out (non-css value)
const WpCursorShapeDeviceV1ShapeDndAsk = 35

// WpCursorShapeDeviceV1ShapeAllResize means resizing: something can be moved or resized in any direction (non-css value)
const WpCursorShapeDeviceV1ShapeAllResize = 36

// WpCursorShapeDeviceV1ErrorInvalidShape means the specified shape value is invalid
const WpCursorShapeDeviceV1ErrorInvalidShape = 1

// WpCursorShapeManagerV1 cursor shape manager
type WpCursorShapeManagerV1 struct {
	BaseProxy
}

// NewWpCursorShapeManagerV1 is a constructor for the WpCursorShapeManagerV1 object
func NewWpCursorShapeManagerV1(ctx *Context) *WpCursorShapeManagerV1 {
	ret := new(WpCursorShapeManagerV1)
	ctx.Register(ret)
	return ret
}

// Destroy destroy the manager
func (p *WpCursorShapeManagerV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// GetPointer manage the cursor shape of a pointer device
func (p *WpCursorShapeManagerV1) GetPointer(Pointer *Pointer) (*WpCursorShapeDeviceV1, error) {
	retShapeDevice := NewWpCursorShapeDeviceV1(p.Context())
	return retShapeDevice, p.Context().SendRequest(p, 1, retShapeDevice, Pointer)
}

// GetTabletToolV2 manage the cursor shape of a tablet tool device
func (p *WpCursorShapeManagerV1) GetTabletToolV2(TabletTool *ZwpTabletToolV2) (*WpCursorShapeDeviceV1, error) {
	retShapeDevice := NewWpCursorShapeDeviceV1(p.Context())
	return retShapeDevice, p.Context().SendRequest(p, 2, retShapeDevice, TabletTool)
}

// Dispatch dispatches event for object WpCursorShapeManagerV1
func (p *WpCursorShapeManagerV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// WpCursorShapeDeviceV1 cursor shape for a device
type WpCursorShapeDeviceV1 struct {
	BaseProxy
}

// NewWpCursorShapeDeviceV1 is a constructor for the WpCursorShapeDeviceV1 object
func NewWpCursorShapeDeviceV1(ctx *Context) *WpCursorShapeDeviceV1 {
	ret := new(WpCursorShapeDeviceV1)
	ctx.Register(ret)
	return ret
}

// Destroy destroy the cursor shape device
func (p *WpCursorShapeDeviceV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// SetShape set device cursor to the shape
func (p *WpCursorShapeDeviceV1) SetShape(Serial uint32, Shape uint32) error {

	return p.Context().SendRequest(p, 1, Serial, Shape)
}

// Dispatch dispatches event for object WpCursorShapeDeviceV1
func (p *WpCursorShapeDeviceV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}
