// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: ext-idle-notify-v1.xml
// Do not edit

// Package wlr implements the ext_idle_notify_v1 protocol
package wlr

import (
	"sync"
)

// ExtIdleNotifierV1 idle notification manager
type ExtIdleNotifierV1 struct {
	BaseProxy
}

// NewExtIdleNotifierV1 is a constructor for the ExtIdleNotifierV1 object
func NewExtIdleNotifierV1(ctx *Context) *ExtIdleNotifierV1 {
	ret := new(ExtIdleNotifierV1)
	ctx.Register(ret)
	return ret
}

// Destroy destroy the manager
func (p *ExtIdleNotifierV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// GetIdleNotification create a notification object
func (p *ExtIdleNotifierV1) GetIdleNotification(Timeout uint32, Seat *Seat) (*ExtIdleNotificationV1, error) {
	retId := NewExtIdleNotificationV1(p.Context())
	return retId, p.Context().SendRequest(p, 1, retId, Timeout, Seat)
}

// GetInputIdleNotification create a notification object
func (p *ExtIdleNotifierV1) GetInputIdleNotification(Timeout uint32, Seat *Seat) (*ExtIdleNotificationV1, error) {
	retId := NewExtIdleNotificationV1(p.Context())
	return retId, p.Context().SendRequest(p, 2, retId, Timeout, Seat)
}

// Dispatch dispatches event for object ExtIdleNotifierV1
func (p *ExtIdleNotifierV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// ExtIdleNotificationV1 idle notification
type ExtIdleNotificationV1 struct {
	BaseProxy
	mu                                   sync.RWMutex
	privateExtIdleNotificationV1Idleds   map[ExtIdleNotificationV1IdledHandler]struct{}
	privateExtIdleNotificationV1Resumeds map[ExtIdleNotificationV1ResumedHandler]struct{}
}

// initExtIdleNotificationV1 initializes the ExtIdleNotificationV1 object's handler maps
func (ret *ExtIdleNotificationV1) initExtIdleNotificationV1() {
	ret.privateExtIdleNotificationV1Idleds = make(map[ExtIdleNotificationV1IdledHandler]struct{})
	ret.privateExtIdleNotificationV1Resumeds = make(map[ExtIdleNotificationV1ResumedHandler]struct{})
}

// NewExtIdleNotificationV1 is a constructor for the ExtIdleNotificationV1 object
func NewExtIdleNotificationV1(ctx *Context) *ExtIdleNotificationV1 {
	ret := new(ExtIdleNotificationV1)
	ret.initExtIdleNotificationV1()
	ctx.Register(ret)
	return ret
}

// Destroy destroy the notification object
func (p *ExtIdleNotificationV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// Dispatch dispatches event for object ExtIdleNotificationV1
func (p *ExtIdleNotificationV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateExtIdleNotificationV1Idleds) > 0 {
			ev := ExtIdleNotificationV1IdledEvent{}
			p.mu.RLock()
			for h := range p.privateExtIdleNotificationV1Idleds {
				h.HandleExtIdleNotificationV1Idled(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateExtIdleNotificationV1Resumeds) > 0 {
			ev := ExtIdleNotificationV1ResumedEvent{}
			p.mu.RLock()
			for h := range p.privateExtIdleNotificationV1Resumeds {
				h.HandleExtIdleNotificationV1Resumed(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ExtIdleNotificationV1IdledEvent is the notification object is idle
type ExtIdleNotificationV1IdledEvent struct {
}

// ExtIdleNotificationV1ResumedEvent is the notification object is no longer idle
type ExtIdleNotificationV1ResumedEvent struct {
}

// ExtIdleNotificationV1IdledHandler is the handler interface for ExtIdleNotificationV1IdledEvent
type ExtIdleNotificationV1IdledHandler interface {
	HandleExtIdleNotificationV1Idled(ExtIdleNotificationV1IdledEvent)
}

// AddIdledHandler adds the Idled handler
func (p *ExtIdleNotificationV1) AddIdledHandler(h ExtIdleNotificationV1IdledHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateExtIdleNotificationV1Idleds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveIdledHandler removes the Idled handler
func (p *ExtIdleNotificationV1) RemoveIdledHandler(h ExtIdleNotificationV1IdledHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateExtIdleNotificationV1Idleds, h)
}

// ExtIdleNotificationV1ResumedHandler is the handler interface for ExtIdleNotificationV1ResumedEvent
type ExtIdleNotificationV1ResumedHandler interface {
	HandleExtIdleNotificationV1Resumed(ExtIdleNotificationV1ResumedEvent)
}

// AddResumedHandler adds the Resumed handler
func (p *ExtIdleNotificationV1) AddResumedHandler(h ExtIdleNotificationV1ResumedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateExtIdleNotificationV1Resumeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveResumedHandler removes the Resumed handler
func (p *ExtIdleNotificationV1) RemoveResumedHandler(h ExtIdleNotificationV1ResumedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateExtIdleNotificationV1Resumeds, h)
}
