// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: ext-data-control-v1.xml
// Do not edit

// Package wlr implements the ext_data_control_v1 protocol
package wlr

import (
	"sync"
)

// DataControlDeviceV1ErrorUsedSource means source given to set_selection or set_primary_selection was already used before
const DataControlDeviceV1ErrorUsedSource = 1

// DataControlSourceV1ErrorInvalidOffer means offer sent after ext_data_control_device.set_selection
const DataControlSourceV1ErrorInvalidOffer = 1

// DataControlManagerV1 manager to control data devices
type DataControlManagerV1 struct {
	BaseProxy
}

// NewDataControlManagerV1 is a constructor for the DataControlManagerV1 object
func NewDataControlManagerV1(ctx *Context) *DataControlManagerV1 {
	ret := new(DataControlManagerV1)
	ctx.Register(ret)
	return ret
}

// CreateDataSource create a new data source
func (p *DataControlManagerV1) CreateDataSource() (*DataControlSourceV1, error) {
	retId := NewDataControlSourceV1(p.Context())
	return retId, p.Context().SendRequest(p, 0, retId)
}

// GetDataDevice get a data device for a seat
func (p *DataControlManagerV1) GetDataDevice(Seat *Seat) (*DataControlDeviceV1, error) {
	retId := NewDataControlDeviceV1(p.Context())
	return retId, p.Context().SendRequest(p, 1, retId, Seat)
}

// Destroy destroy the manager
func (p *DataControlManagerV1) Destroy() error {

	return p.Context().SendRequest(p, 2)
}

// Dispatch dispatches event for object DataControlManagerV1
func (p *DataControlManagerV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// DataControlDeviceV1 manage a data device for a seat
type DataControlDeviceV1 struct {
	BaseProxy
	mu                                          sync.RWMutex
	privateDataControlDeviceV1DataOffers        map[DataControlDeviceV1DataOfferHandler]struct{}
	privateDataControlDeviceV1Selections        map[DataControlDeviceV1SelectionHandler]struct{}
	privateDataControlDeviceV1Finisheds         map[DataControlDeviceV1FinishedHandler]struct{}
	privateDataControlDeviceV1PrimarySelections map[DataControlDeviceV1PrimarySelectionHandler]struct{}
}

// initDataControlDeviceV1 initializes the DataControlDeviceV1 object's handler maps
func (ret *DataControlDeviceV1) initDataControlDeviceV1() {
	ret.privateDataControlDeviceV1DataOffers = make(map[DataControlDeviceV1DataOfferHandler]struct{})
	ret.privateDataControlDeviceV1Selections = make(map[DataControlDeviceV1SelectionHandler]struct{})
	ret.privateDataControlDeviceV1Finisheds = make(map[DataControlDeviceV1FinishedHandler]struct{})
	ret.privateDataControlDeviceV1PrimarySelections = make(map[DataControlDeviceV1PrimarySelectionHandler]struct{})
}

// NewDataControlDeviceV1 is a constructor for the DataControlDeviceV1 object
func NewDataControlDeviceV1(ctx *Context) *DataControlDeviceV1 {
	ret := new(DataControlDeviceV1)
	ret.initDataControlDeviceV1()
	ctx.Register(ret)
	return ret
}

// SetSelection copy data to the selection
func (p *DataControlDeviceV1) SetSelection(Source *DataControlSourceV1) error {

	return p.Context().SendRequest(p, 0, Source)
}

// Destroy destroy this data device
func (p *DataControlDeviceV1) Destroy() error {

	return p.Context().SendRequest(p, 1)
}

// SetPrimarySelection copy data to the primary selection
func (p *DataControlDeviceV1) SetPrimarySelection(Source *DataControlSourceV1) error {

	return p.Context().SendRequest(p, 2, Source)
}

// Dispatch dispatches event for object DataControlDeviceV1
func (p *DataControlDeviceV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateDataControlDeviceV1DataOffers) > 0 {
			ev := DataControlDeviceV1DataOfferEvent{}
			ev.Id = func() *DataControlOfferV1 {
				ret := new(DataControlOfferV1)
				ret.initDataControlOfferV1()
				return event.NewId(ret, p.Context()).(*DataControlOfferV1)
			}()
			p.mu.RLock()
			for h := range p.privateDataControlDeviceV1DataOffers {
				h.HandleDataControlDeviceV1DataOffer(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateDataControlDeviceV1Selections) > 0 {
			ev := DataControlDeviceV1SelectionEvent{}
			ev.Id = SafeCast[*DataControlOfferV1](event.Proxy(p.Context()))
			p.mu.RLock()
			for h := range p.privateDataControlDeviceV1Selections {
				h.HandleDataControlDeviceV1Selection(ev)
			}
			p.mu.RUnlock()
		}
	case 2:
		if len(p.privateDataControlDeviceV1Finisheds) > 0 {
			ev := DataControlDeviceV1FinishedEvent{}
			p.mu.RLock()
			for h := range p.privateDataControlDeviceV1Finisheds {
				h.HandleDataControlDeviceV1Finished(ev)
			}
			p.mu.RUnlock()
		}
	case 3:
		if len(p.privateDataControlDeviceV1PrimarySelections) > 0 {
			ev := DataControlDeviceV1PrimarySelectionEvent{}
			ev.Id = SafeCast[*DataControlOfferV1](event.Proxy(p.Context()))
			p.mu.RLock()
			for h := range p.privateDataControlDeviceV1PrimarySelections {
				h.HandleDataControlDeviceV1PrimarySelection(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// DataControlDeviceV1DataOfferEvent is the introduce a new ext_data_control_offer
type DataControlDeviceV1DataOfferEvent struct {
	// Id is the
	Id *DataControlOfferV1
}

// DataControlDeviceV1SelectionEvent is the advertise new selection
type DataControlDeviceV1SelectionEvent struct {
	// Id is the
	Id *DataControlOfferV1
}

// DataControlDeviceV1FinishedEvent is the this data control is no longer valid
type DataControlDeviceV1FinishedEvent struct {
}

// DataControlDeviceV1PrimarySelectionEvent is the advertise new primary selection
type DataControlDeviceV1PrimarySelectionEvent struct {
	// Id is the
	Id *DataControlOfferV1
}

// DataControlDeviceV1DataOfferHandler is the handler interface for DataControlDeviceV1DataOfferEvent
type DataControlDeviceV1DataOfferHandler interface {
	HandleDataControlDeviceV1DataOffer(DataControlDeviceV1DataOfferEvent)
}

// AddDataOfferHandler adds the DataOffer handler
func (p *DataControlDeviceV1) AddDataOfferHandler(h DataControlDeviceV1DataOfferHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateDataControlDeviceV1DataOffers[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveDataOfferHandler removes the DataOffer handler
func (p *DataControlDeviceV1) RemoveDataOfferHandler(h DataControlDeviceV1DataOfferHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateDataControlDeviceV1DataOffers, h)
}

// DataControlDeviceV1SelectionHandler is the handler interface for DataControlDeviceV1SelectionEvent
type DataControlDeviceV1SelectionHandler interface {
	HandleDataControlDeviceV1Selection(DataControlDeviceV1SelectionEvent)
}

// AddSelectionHandler adds the Selection handler
func (p *DataControlDeviceV1) AddSelectionHandler(h DataControlDeviceV1SelectionHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateDataControlDeviceV1Selections[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveSelectionHandler removes the Selection handler
func (p *DataControlDeviceV1) RemoveSelectionHandler(h DataControlDeviceV1SelectionHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateDataControlDeviceV1Selections, h)
}

// DataControlDeviceV1FinishedHandler is the handler interface for DataControlDeviceV1FinishedEvent
type DataControlDeviceV1FinishedHandler interface {
	HandleDataControlDeviceV1Finished(DataControlDeviceV1FinishedEvent)
}

// AddFinishedHandler adds the Finished handler
func (p *DataControlDeviceV1) AddFinishedHandler(h DataControlDeviceV1FinishedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateDataControlDeviceV1Finisheds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveFinishedHandler removes the Finished handler
func (p *DataControlDeviceV1) RemoveFinishedHandler(h DataControlDeviceV1FinishedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateDataControlDeviceV1Finisheds, h)
}

// DataControlDeviceV1PrimarySelectionHandler is the handler interface for DataControlDeviceV1PrimarySelectionEvent
type DataControlDeviceV1PrimarySelectionHandler interface {
	HandleDataControlDeviceV1PrimarySelection(DataControlDeviceV1PrimarySelectionEvent)
}

// AddPrimarySelectionHandler adds the PrimarySelection handler
func (p *DataControlDeviceV1) AddPrimarySelectionHandler(h DataControlDeviceV1PrimarySelectionHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateDataControlDeviceV1PrimarySelections[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemovePrimarySelectionHandler removes the PrimarySelection handler
func (p *DataControlDeviceV1) RemovePrimarySelectionHandler(h DataControlDeviceV1PrimarySelectionHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateDataControlDeviceV1PrimarySelections, h)
}

// DataControlSourceV1 offer to transfer data
type DataControlSourceV1 struct {
	BaseProxy
	mu                                   sync.RWMutex
	privateDataControlSourceV1Sends      map[DataControlSourceV1SendHandler]struct{}
	privateDataControlSourceV1Cancelleds map[DataControlSourceV1CancelledHandler]struct{}
}

// initDataControlSourceV1 initializes the DataControlSourceV1 object's handler maps
func (ret *DataControlSourceV1) initDataControlSourceV1() {
	ret.privateDataControlSourceV1Sends = make(map[DataControlSourceV1SendHandler]struct{})
	ret.privateDataControlSourceV1Cancelleds = make(map[DataControlSourceV1CancelledHandler]struct{})
}

// NewDataControlSourceV1 is a constructor for the DataControlSourceV1 object
func NewDataControlSourceV1(ctx *Context) *DataControlSourceV1 {
	ret := new(DataControlSourceV1)
	ret.initDataControlSourceV1()
	ctx.Register(ret)
	return ret
}

// Offer add an offered MIME type
func (p *DataControlSourceV1) Offer(MimeType string) error {

	return p.Context().SendRequest(p, 0, MimeType)
}

// Destroy destroy this source
func (p *DataControlSourceV1) Destroy() error {

	return p.Context().SendRequest(p, 1)
}

// Dispatch dispatches event for object DataControlSourceV1
func (p *DataControlSourceV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateDataControlSourceV1Sends) > 0 {
			ev := DataControlSourceV1SendEvent{}
			ev.MimeType = event.String()
			ev.Fd, ev.FdError = event.FD()
			p.mu.RLock()
			for h := range p.privateDataControlSourceV1Sends {
				h.HandleDataControlSourceV1Send(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateDataControlSourceV1Cancelleds) > 0 {
			ev := DataControlSourceV1CancelledEvent{}
			p.mu.RLock()
			for h := range p.privateDataControlSourceV1Cancelleds {
				h.HandleDataControlSourceV1Cancelled(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// DataControlSourceV1SendEvent is the send the data
type DataControlSourceV1SendEvent struct {
	// MimeType is the MIME type for the data
	MimeType string
	// Fd is the file descriptor for the data
	Fd uintptr
	// FdError is the file descriptor for the data (error)
	FdError error
}

// DataControlSourceV1CancelledEvent is the selection was cancelled
type DataControlSourceV1CancelledEvent struct {
}

// DataControlSourceV1SendHandler is the handler interface for DataControlSourceV1SendEvent
type DataControlSourceV1SendHandler interface {
	HandleDataControlSourceV1Send(DataControlSourceV1SendEvent)
}

// AddSendHandler adds the Send handler
func (p *DataControlSourceV1) AddSendHandler(h DataControlSourceV1SendHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateDataControlSourceV1Sends[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveSendHandler removes the Send handler
func (p *DataControlSourceV1) RemoveSendHandler(h DataControlSourceV1SendHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateDataControlSourceV1Sends, h)
}

// DataControlSourceV1CancelledHandler is the handler interface for DataControlSourceV1CancelledEvent
type DataControlSourceV1CancelledHandler interface {
	HandleDataControlSourceV1Cancelled(DataControlSourceV1CancelledEvent)
}

// AddCancelledHandler adds the Cancelled handler
func (p *DataControlSourceV1) AddCancelledHandler(h DataControlSourceV1CancelledHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateDataControlSourceV1Cancelleds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveCancelledHandler removes the Cancelled handler
func (p *DataControlSourceV1) RemoveCancelledHandler(h DataControlSourceV1CancelledHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateDataControlSourceV1Cancelleds, h)
}

// DataControlOfferV1 offer to transfer data
type DataControlOfferV1 struct {
	BaseProxy
	mu                              sync.RWMutex
	privateDataControlOfferV1Offers map[DataControlOfferV1OfferHandler]struct{}
}

// initDataControlOfferV1 initializes the DataControlOfferV1 object's handler maps
func (ret *DataControlOfferV1) initDataControlOfferV1() {
	ret.privateDataControlOfferV1Offers = make(map[DataControlOfferV1OfferHandler]struct{})
}

// NewDataControlOfferV1 is a constructor for the DataControlOfferV1 object
func NewDataControlOfferV1(ctx *Context) *DataControlOfferV1 {
	ret := new(DataControlOfferV1)
	ret.initDataControlOfferV1()
	ctx.Register(ret)
	return ret
}

// Receive request that the data is transferred
func (p *DataControlOfferV1) Receive(MimeType string, Fd uintptr) error {

	return p.Context().SendRequest(p, 0, MimeType, Fd)
}

// Destroy destroy this offer
func (p *DataControlOfferV1) Destroy() error {

	return p.Context().SendRequest(p, 1)
}

// Dispatch dispatches event for object DataControlOfferV1
func (p *DataControlOfferV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateDataControlOfferV1Offers) > 0 {
			ev := DataControlOfferV1OfferEvent{}
			ev.MimeType = event.String()
			p.mu.RLock()
			for h := range p.privateDataControlOfferV1Offers {
				h.HandleDataControlOfferV1Offer(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// DataControlOfferV1OfferEvent is the advertise offered MIME type
type DataControlOfferV1OfferEvent struct {
	// MimeType is the offered MIME type
	MimeType string
}

// DataControlOfferV1OfferHandler is the handler interface for DataControlOfferV1OfferEvent
type DataControlOfferV1OfferHandler interface {
	HandleDataControlOfferV1Offer(DataControlOfferV1OfferEvent)
}

// AddOfferHandler adds the Offer handler
func (p *DataControlOfferV1) AddOfferHandler(h DataControlOfferV1OfferHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateDataControlOfferV1Offers[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveOfferHandler removes the Offer handler
func (p *DataControlOfferV1) RemoveOfferHandler(h DataControlOfferV1OfferHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateDataControlOfferV1Offers, h)
}
