// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: ext-image-copy-capture-v1.xml
// Do not edit

// Package wlr implements the ext_image_copy_capture_v1 protocol
package wlr

import (
	"sync"
)

// ImageCopyCaptureManagerV1ErrorInvalidOption means invalid option flag
const ImageCopyCaptureManagerV1ErrorInvalidOption = 1

// ImageCopyCaptureManagerV1OptionsPaintCursors means paint cursors onto captured frames
const ImageCopyCaptureManagerV1OptionsPaintCursors = 1

// ImageCopyCaptureSessionV1ErrorDuplicateFrame means create_frame sent before destroying previous frame
const ImageCopyCaptureSessionV1ErrorDuplicateFrame = 1

// ImageCopyCaptureFrameV1ErrorNoBuffer means capture sent without attach_buffer
const ImageCopyCaptureFrameV1ErrorNoBuffer = 1

// ImageCopyCaptureFrameV1ErrorInvalidBufferDamage means invalid buffer damage
const ImageCopyCaptureFrameV1ErrorInvalidBufferDamage = 2

// ImageCopyCaptureFrameV1ErrorAlreadyCaptured means capture request has been sent
const ImageCopyCaptureFrameV1ErrorAlreadyCaptured = 3

// ImageCopyCaptureFrameV1FailureReasonUnknown
const ImageCopyCaptureFrameV1FailureReasonUnknown = 0

// ImageCopyCaptureFrameV1FailureReasonBufferConstraints
const ImageCopyCaptureFrameV1FailureReasonBufferConstraints = 1

// ImageCopyCaptureFrameV1FailureReasonStopped
const ImageCopyCaptureFrameV1FailureReasonStopped = 2

// ImageCopyCaptureCursorSessionV1ErrorDuplicateSession means get_capture_session sent twice
const ImageCopyCaptureCursorSessionV1ErrorDuplicateSession = 1

// ImageCopyCaptureManagerV1 manager to inform clients and begin capturing
type ImageCopyCaptureManagerV1 struct {
	BaseProxy
}

// NewImageCopyCaptureManagerV1 is a constructor for the ImageCopyCaptureManagerV1 object
func NewImageCopyCaptureManagerV1(ctx *Context) *ImageCopyCaptureManagerV1 {
	ret := new(ImageCopyCaptureManagerV1)
	ctx.Register(ret)
	return ret
}

// CreateSession capture an image capture source
func (p *ImageCopyCaptureManagerV1) CreateSession(Source *ImageCaptureSourceV1, Options uint32) (*ImageCopyCaptureSessionV1, error) {
	retSession := NewImageCopyCaptureSessionV1(p.Context())
	return retSession, p.Context().SendRequest(p, 0, retSession, Source, Options)
}

// CreatePointerCursorSession capture the pointer cursor of an image capture source
func (p *ImageCopyCaptureManagerV1) CreatePointerCursorSession(Source *ImageCaptureSourceV1, Pointer *Pointer) (*ImageCopyCaptureCursorSessionV1, error) {
	retSession := NewImageCopyCaptureCursorSessionV1(p.Context())
	return retSession, p.Context().SendRequest(p, 1, retSession, Source, Pointer)
}

// Destroy destroy the manager
func (p *ImageCopyCaptureManagerV1) Destroy() error {

	return p.Context().SendRequest(p, 2)
}

// Dispatch dispatches event for object ImageCopyCaptureManagerV1
func (p *ImageCopyCaptureManagerV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// ImageCopyCaptureSessionV1 image copy capture session
type ImageCopyCaptureSessionV1 struct {
	BaseProxy
	mu                                            sync.RWMutex
	privateImageCopyCaptureSessionV1BufferSizes   map[ImageCopyCaptureSessionV1BufferSizeHandler]struct{}
	privateImageCopyCaptureSessionV1ShmFormats    map[ImageCopyCaptureSessionV1ShmFormatHandler]struct{}
	privateImageCopyCaptureSessionV1DmabufDevices map[ImageCopyCaptureSessionV1DmabufDeviceHandler]struct{}
	privateImageCopyCaptureSessionV1DmabufFormats map[ImageCopyCaptureSessionV1DmabufFormatHandler]struct{}
	privateImageCopyCaptureSessionV1Dones         map[ImageCopyCaptureSessionV1DoneHandler]struct{}
	privateImageCopyCaptureSessionV1Stoppeds      map[ImageCopyCaptureSessionV1StoppedHandler]struct{}
}

// initImageCopyCaptureSessionV1 initializes the ImageCopyCaptureSessionV1 object's handler maps
func (ret *ImageCopyCaptureSessionV1) initImageCopyCaptureSessionV1() {
	ret.privateImageCopyCaptureSessionV1BufferSizes = make(map[ImageCopyCaptureSessionV1BufferSizeHandler]struct{})
	ret.privateImageCopyCaptureSessionV1ShmFormats = make(map[ImageCopyCaptureSessionV1ShmFormatHandler]struct{})
	ret.privateImageCopyCaptureSessionV1DmabufDevices = make(map[ImageCopyCaptureSessionV1DmabufDeviceHandler]struct{})
	ret.privateImageCopyCaptureSessionV1DmabufFormats = make(map[ImageCopyCaptureSessionV1DmabufFormatHandler]struct{})
	ret.privateImageCopyCaptureSessionV1Dones = make(map[ImageCopyCaptureSessionV1DoneHandler]struct{})
	ret.privateImageCopyCaptureSessionV1Stoppeds = make(map[ImageCopyCaptureSessionV1StoppedHandler]struct{})
}

// NewImageCopyCaptureSessionV1 is a constructor for the ImageCopyCaptureSessionV1 object
func NewImageCopyCaptureSessionV1(ctx *Context) *ImageCopyCaptureSessionV1 {
	ret := new(ImageCopyCaptureSessionV1)
	ret.initImageCopyCaptureSessionV1()
	ctx.Register(ret)
	return ret
}

// CreateFrame create a frame
func (p *ImageCopyCaptureSessionV1) CreateFrame() (*ImageCopyCaptureFrameV1, error) {
	retFrame := NewImageCopyCaptureFrameV1(p.Context())
	return retFrame, p.Context().SendRequest(p, 0, retFrame)
}

// Destroy delete this object
func (p *ImageCopyCaptureSessionV1) Destroy() error {

	return p.Context().SendRequest(p, 1)
}

// Dispatch dispatches event for object ImageCopyCaptureSessionV1
func (p *ImageCopyCaptureSessionV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateImageCopyCaptureSessionV1BufferSizes) > 0 {
			ev := ImageCopyCaptureSessionV1BufferSizeEvent{}
			ev.Width = event.Uint32()
			ev.Height = event.Uint32()
			p.mu.RLock()
			for h := range p.privateImageCopyCaptureSessionV1BufferSizes {
				h.HandleImageCopyCaptureSessionV1BufferSize(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateImageCopyCaptureSessionV1ShmFormats) > 0 {
			ev := ImageCopyCaptureSessionV1ShmFormatEvent{}
			ev.Format = event.Uint32()
			p.mu.RLock()
			for h := range p.privateImageCopyCaptureSessionV1ShmFormats {
				h.HandleImageCopyCaptureSessionV1ShmFormat(ev)
			}
			p.mu.RUnlock()
		}
	case 2:
		if len(p.privateImageCopyCaptureSessionV1DmabufDevices) > 0 {
			ev := ImageCopyCaptureSessionV1DmabufDeviceEvent{}
			ev.Device = event.Array()
			p.mu.RLock()
			for h := range p.privateImageCopyCaptureSessionV1DmabufDevices {
				h.HandleImageCopyCaptureSessionV1DmabufDevice(ev)
			}
			p.mu.RUnlock()
		}
	case 3:
		if len(p.privateImageCopyCaptureSessionV1DmabufFormats) > 0 {
			ev := ImageCopyCaptureSessionV1DmabufFormatEvent{}
			ev.Format = event.Uint32()
			ev.Modifiers = event.Array()
			p.mu.RLock()
			for h := range p.privateImageCopyCaptureSessionV1DmabufFormats {
				h.HandleImageCopyCaptureSessionV1DmabufFormat(ev)
			}
			p.mu.RUnlock()
		}
	case 4:
		if len(p.privateImageCopyCaptureSessionV1Dones) > 0 {
			ev := ImageCopyCaptureSessionV1DoneEvent{}
			p.mu.RLock()
			for h := range p.privateImageCopyCaptureSessionV1Dones {
				h.HandleImageCopyCaptureSessionV1Done(ev)
			}
			p.mu.RUnlock()
		}
	case 5:
		if len(p.privateImageCopyCaptureSessionV1Stoppeds) > 0 {
			ev := ImageCopyCaptureSessionV1StoppedEvent{}
			p.mu.RLock()
			for h := range p.privateImageCopyCaptureSessionV1Stoppeds {
				h.HandleImageCopyCaptureSessionV1Stopped(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ImageCopyCaptureSessionV1BufferSizeEvent is the image capture source dimensions
type ImageCopyCaptureSessionV1BufferSizeEvent struct {
	// Width is the buffer width
	Width uint32
	// Height is the buffer height
	Height uint32
}

// ImageCopyCaptureSessionV1ShmFormatEvent is the shm buffer format
type ImageCopyCaptureSessionV1ShmFormatEvent struct {
	// Format is the shm format
	Format uint32
}

// ImageCopyCaptureSessionV1DmabufDeviceEvent is the dma-buf device
type ImageCopyCaptureSessionV1DmabufDeviceEvent struct {
	// Device is the device dev_t value
	Device []int32
}

// ImageCopyCaptureSessionV1DmabufFormatEvent is the dma-buf format
type ImageCopyCaptureSessionV1DmabufFormatEvent struct {
	// Format is the drm format code
	Format uint32
	// Modifiers is the drm format modifiers
	Modifiers []int32
}

// ImageCopyCaptureSessionV1DoneEvent is the all constraints have been sent
type ImageCopyCaptureSessionV1DoneEvent struct {
}

// ImageCopyCaptureSessionV1StoppedEvent is the session is no longer available
type ImageCopyCaptureSessionV1StoppedEvent struct {
}

// ImageCopyCaptureSessionV1BufferSizeHandler is the handler interface for ImageCopyCaptureSessionV1BufferSizeEvent
type ImageCopyCaptureSessionV1BufferSizeHandler interface {
	HandleImageCopyCaptureSessionV1BufferSize(ImageCopyCaptureSessionV1BufferSizeEvent)
}

// AddBufferSizeHandler adds the BufferSize handler
func (p *ImageCopyCaptureSessionV1) AddBufferSizeHandler(h ImageCopyCaptureSessionV1BufferSizeHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateImageCopyCaptureSessionV1BufferSizes[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveBufferSizeHandler removes the BufferSize handler
func (p *ImageCopyCaptureSessionV1) RemoveBufferSizeHandler(h ImageCopyCaptureSessionV1BufferSizeHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateImageCopyCaptureSessionV1BufferSizes, h)
}

// ImageCopyCaptureSessionV1ShmFormatHandler is the handler interface for ImageCopyCaptureSessionV1ShmFormatEvent
type ImageCopyCaptureSessionV1ShmFormatHandler interface {
	HandleImageCopyCaptureSessionV1ShmFormat(ImageCopyCaptureSessionV1ShmFormatEvent)
}

// AddShmFormatHandler adds the ShmFormat handler
func (p *ImageCopyCaptureSessionV1) AddShmFormatHandler(h ImageCopyCaptureSessionV1ShmFormatHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateImageCopyCaptureSessionV1ShmFormats[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveShmFormatHandler removes the ShmFormat handler
func (p *ImageCopyCaptureSessionV1) RemoveShmFormatHandler(h ImageCopyCaptureSessionV1ShmFormatHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateImageCopyCaptureSessionV1ShmFormats, h)
}

// ImageCopyCaptureSessionV1DmabufDeviceHandler is the handler interface for ImageCopyCaptureSessionV1DmabufDeviceEvent
type ImageCopyCaptureSessionV1DmabufDeviceHandler interface {
	HandleImageCopyCaptureSessionV1DmabufDevice(ImageCopyCaptureSessionV1DmabufDeviceEvent)
}

// AddDmabufDeviceHandler adds the DmabufDevice handler
func (p *ImageCopyCaptureSessionV1) AddDmabufDeviceHandler(h ImageCopyCaptureSessionV1DmabufDeviceHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateImageCopyCaptureSessionV1DmabufDevices[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveDmabufDeviceHandler removes the DmabufDevice handler
func (p *ImageCopyCaptureSessionV1) RemoveDmabufDeviceHandler(h ImageCopyCaptureSessionV1DmabufDeviceHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateImageCopyCaptureSessionV1DmabufDevices, h)
}

// ImageCopyCaptureSessionV1DmabufFormatHandler is the handler interface for ImageCopyCaptureSessionV1DmabufFormatEvent
type ImageCopyCaptureSessionV1DmabufFormatHandler interface {
	HandleImageCopyCaptureSessionV1DmabufFormat(ImageCopyCaptureSessionV1DmabufFormatEvent)
}

// AddDmabufFormatHandler adds the DmabufFormat handler
func (p *ImageCopyCaptureSessionV1) AddDmabufFormatHandler(h ImageCopyCaptureSessionV1DmabufFormatHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateImageCopyCaptureSessionV1DmabufFormats[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveDmabufFormatHandler removes the DmabufFormat handler
func (p *ImageCopyCaptureSessionV1) RemoveDmabufFormatHandler(h ImageCopyCaptureSessionV1DmabufFormatHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateImageCopyCaptureSessionV1DmabufFormats, h)
}

// ImageCopyCaptureSessionV1DoneHandler is the handler interface for ImageCopyCaptureSessionV1DoneEvent
type ImageCopyCaptureSessionV1DoneHandler interface {
	HandleImageCopyCaptureSessionV1Done(ImageCopyCaptureSessionV1DoneEvent)
}

// AddDoneHandler adds the Done handler
func (p *ImageCopyCaptureSessionV1) AddDoneHandler(h ImageCopyCaptureSessionV1DoneHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateImageCopyCaptureSessionV1Dones[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveDoneHandler removes the Done handler
func (p *ImageCopyCaptureSessionV1) RemoveDoneHandler(h ImageCopyCaptureSessionV1DoneHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateImageCopyCaptureSessionV1Dones, h)
}

// ImageCopyCaptureSessionV1StoppedHandler is the handler interface for ImageCopyCaptureSessionV1StoppedEvent
type ImageCopyCaptureSessionV1StoppedHandler interface {
	HandleImageCopyCaptureSessionV1Stopped(ImageCopyCaptureSessionV1StoppedEvent)
}

// AddStoppedHandler adds the Stopped handler
func (p *ImageCopyCaptureSessionV1) AddStoppedHandler(h ImageCopyCaptureSessionV1StoppedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateImageCopyCaptureSessionV1Stoppeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveStoppedHandler removes the Stopped handler
func (p *ImageCopyCaptureSessionV1) RemoveStoppedHandler(h ImageCopyCaptureSessionV1StoppedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateImageCopyCaptureSessionV1Stoppeds, h)
}

// ImageCopyCaptureFrameV1 image capture frame
type ImageCopyCaptureFrameV1 struct {
	BaseProxy
	mu                                              sync.RWMutex
	privateImageCopyCaptureFrameV1Transforms        map[ImageCopyCaptureFrameV1TransformHandler]struct{}
	privateImageCopyCaptureFrameV1Damages           map[ImageCopyCaptureFrameV1DamageHandler]struct{}
	privateImageCopyCaptureFrameV1PresentationTimes map[ImageCopyCaptureFrameV1PresentationTimeHandler]struct{}
	privateImageCopyCaptureFrameV1Readys            map[ImageCopyCaptureFrameV1ReadyHandler]struct{}
	privateImageCopyCaptureFrameV1Faileds           map[ImageCopyCaptureFrameV1FailedHandler]struct{}
}

// initImageCopyCaptureFrameV1 initializes the ImageCopyCaptureFrameV1 object's handler maps
func (ret *ImageCopyCaptureFrameV1) initImageCopyCaptureFrameV1() {
	ret.privateImageCopyCaptureFrameV1Transforms = make(map[ImageCopyCaptureFrameV1TransformHandler]struct{})
	ret.privateImageCopyCaptureFrameV1Damages = make(map[ImageCopyCaptureFrameV1DamageHandler]struct{})
	ret.privateImageCopyCaptureFrameV1PresentationTimes = make(map[ImageCopyCaptureFrameV1PresentationTimeHandler]struct{})
	ret.privateImageCopyCaptureFrameV1Readys = make(map[ImageCopyCaptureFrameV1ReadyHandler]struct{})
	ret.privateImageCopyCaptureFrameV1Faileds = make(map[ImageCopyCaptureFrameV1FailedHandler]struct{})
}

// NewImageCopyCaptureFrameV1 is a constructor for the ImageCopyCaptureFrameV1 object
func NewImageCopyCaptureFrameV1(ctx *Context) *ImageCopyCaptureFrameV1 {
	ret := new(ImageCopyCaptureFrameV1)
	ret.initImageCopyCaptureFrameV1()
	ctx.Register(ret)
	return ret
}

// Destroy destroy this object
func (p *ImageCopyCaptureFrameV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// AttachBuffer attach buffer to session
func (p *ImageCopyCaptureFrameV1) AttachBuffer(Buffer *Buffer) error {

	return p.Context().SendRequest(p, 1, Buffer)
}

// DamageBuffer damage buffer
func (p *ImageCopyCaptureFrameV1) DamageBuffer(X int32, Y int32, Width int32, Height int32) error {

	return p.Context().SendRequest(p, 2, X, Y, Width, Height)
}

// Capture capture a frame
func (p *ImageCopyCaptureFrameV1) Capture() error {

	return p.Context().SendRequest(p, 3)
}

// Dispatch dispatches event for object ImageCopyCaptureFrameV1
func (p *ImageCopyCaptureFrameV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateImageCopyCaptureFrameV1Transforms) > 0 {
			ev := ImageCopyCaptureFrameV1TransformEvent{}
			ev.Transform = event.Uint32()
			p.mu.RLock()
			for h := range p.privateImageCopyCaptureFrameV1Transforms {
				h.HandleImageCopyCaptureFrameV1Transform(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateImageCopyCaptureFrameV1Damages) > 0 {
			ev := ImageCopyCaptureFrameV1DamageEvent{}
			ev.X = event.Int32()
			ev.Y = event.Int32()
			ev.Width = event.Int32()
			ev.Height = event.Int32()
			p.mu.RLock()
			for h := range p.privateImageCopyCaptureFrameV1Damages {
				h.HandleImageCopyCaptureFrameV1Damage(ev)
			}
			p.mu.RUnlock()
		}
	case 2:
		if len(p.privateImageCopyCaptureFrameV1PresentationTimes) > 0 {
			ev := ImageCopyCaptureFrameV1PresentationTimeEvent{}
			ev.TvSecHi = event.Uint32()
			ev.TvSecLo = event.Uint32()
			ev.TvNsec = event.Uint32()
			p.mu.RLock()
			for h := range p.privateImageCopyCaptureFrameV1PresentationTimes {
				h.HandleImageCopyCaptureFrameV1PresentationTime(ev)
			}
			p.mu.RUnlock()
		}
	case 3:
		if len(p.privateImageCopyCaptureFrameV1Readys) > 0 {
			ev := ImageCopyCaptureFrameV1ReadyEvent{}
			p.mu.RLock()
			for h := range p.privateImageCopyCaptureFrameV1Readys {
				h.HandleImageCopyCaptureFrameV1Ready(ev)
			}
			p.mu.RUnlock()
		}
	case 4:
		if len(p.privateImageCopyCaptureFrameV1Faileds) > 0 {
			ev := ImageCopyCaptureFrameV1FailedEvent{}
			ev.Reason = event.Uint32()
			p.mu.RLock()
			for h := range p.privateImageCopyCaptureFrameV1Faileds {
				h.HandleImageCopyCaptureFrameV1Failed(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ImageCopyCaptureFrameV1TransformEvent is the buffer transform
type ImageCopyCaptureFrameV1TransformEvent struct {
	// Transform is the
	Transform uint32
}

// ImageCopyCaptureFrameV1DamageEvent is the buffer damaged region
type ImageCopyCaptureFrameV1DamageEvent struct {
	// X is the damage x coordinate
	X int32
	// Y is the damage y coordinate
	Y int32
	// Width is the damage width
	Width int32
	// Height is the damage height
	Height int32
}

// ImageCopyCaptureFrameV1PresentationTimeEvent is the presentation time of the frame
type ImageCopyCaptureFrameV1PresentationTimeEvent struct {
	// TvSecHi is the high 32 bits of the seconds part of the timestamp
	TvSecHi uint32
	// TvSecLo is the low 32 bits of the seconds part of the timestamp
	TvSecLo uint32
	// TvNsec is the nanoseconds part of the timestamp
	TvNsec uint32
}

// ImageCopyCaptureFrameV1ReadyEvent is the frame is available for reading
type ImageCopyCaptureFrameV1ReadyEvent struct {
}

// ImageCopyCaptureFrameV1FailedEvent is the capture failed
type ImageCopyCaptureFrameV1FailedEvent struct {
	// Reason is the
	Reason uint32
}

// ImageCopyCaptureFrameV1TransformHandler is the handler interface for ImageCopyCaptureFrameV1TransformEvent
type ImageCopyCaptureFrameV1TransformHandler interface {
	HandleImageCopyCaptureFrameV1Transform(ImageCopyCaptureFrameV1TransformEvent)
}

// AddTransformHandler adds the Transform handler
func (p *ImageCopyCaptureFrameV1) AddTransformHandler(h ImageCopyCaptureFrameV1TransformHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateImageCopyCaptureFrameV1Transforms[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveTransformHandler removes the Transform handler
func (p *ImageCopyCaptureFrameV1) RemoveTransformHandler(h ImageCopyCaptureFrameV1TransformHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateImageCopyCaptureFrameV1Transforms, h)
}

// ImageCopyCaptureFrameV1DamageHandler is the handler interface for ImageCopyCaptureFrameV1DamageEvent
type ImageCopyCaptureFrameV1DamageHandler interface {
	HandleImageCopyCaptureFrameV1Damage(ImageCopyCaptureFrameV1DamageEvent)
}

// AddDamageHandler adds the Damage handler
func (p *ImageCopyCaptureFrameV1) AddDamageHandler(h ImageCopyCaptureFrameV1DamageHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateImageCopyCaptureFrameV1Damages[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveDamageHandler removes the Damage handler
func (p *ImageCopyCaptureFrameV1) RemoveDamageHandler(h ImageCopyCaptureFrameV1DamageHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateImageCopyCaptureFrameV1Damages, h)
}

// ImageCopyCaptureFrameV1PresentationTimeHandler is the handler interface for ImageCopyCaptureFrameV1PresentationTimeEvent
type ImageCopyCaptureFrameV1PresentationTimeHandler interface {
	HandleImageCopyCaptureFrameV1PresentationTime(ImageCopyCaptureFrameV1PresentationTimeEvent)
}

// AddPresentationTimeHandler adds the PresentationTime handler
func (p *ImageCopyCaptureFrameV1) AddPresentationTimeHandler(h ImageCopyCaptureFrameV1PresentationTimeHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateImageCopyCaptureFrameV1PresentationTimes[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemovePresentationTimeHandler removes the PresentationTime handler
func (p *ImageCopyCaptureFrameV1) RemovePresentationTimeHandler(h ImageCopyCaptureFrameV1PresentationTimeHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateImageCopyCaptureFrameV1PresentationTimes, h)
}

// ImageCopyCaptureFrameV1ReadyHandler is the handler interface for ImageCopyCaptureFrameV1ReadyEvent
type ImageCopyCaptureFrameV1ReadyHandler interface {
	HandleImageCopyCaptureFrameV1Ready(ImageCopyCaptureFrameV1ReadyEvent)
}

// AddReadyHandler adds the Ready handler
func (p *ImageCopyCaptureFrameV1) AddReadyHandler(h ImageCopyCaptureFrameV1ReadyHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateImageCopyCaptureFrameV1Readys[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveReadyHandler removes the Ready handler
func (p *ImageCopyCaptureFrameV1) RemoveReadyHandler(h ImageCopyCaptureFrameV1ReadyHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateImageCopyCaptureFrameV1Readys, h)
}

// ImageCopyCaptureFrameV1FailedHandler is the handler interface for ImageCopyCaptureFrameV1FailedEvent
type ImageCopyCaptureFrameV1FailedHandler interface {
	HandleImageCopyCaptureFrameV1Failed(ImageCopyCaptureFrameV1FailedEvent)
}

// AddFailedHandler adds the Failed handler
func (p *ImageCopyCaptureFrameV1) AddFailedHandler(h ImageCopyCaptureFrameV1FailedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateImageCopyCaptureFrameV1Faileds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveFailedHandler removes the Failed handler
func (p *ImageCopyCaptureFrameV1) RemoveFailedHandler(h ImageCopyCaptureFrameV1FailedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateImageCopyCaptureFrameV1Faileds, h)
}

// ImageCopyCaptureCursorSessionV1 cursor capture session
type ImageCopyCaptureCursorSessionV1 struct {
	BaseProxy
	mu                                              sync.RWMutex
	privateImageCopyCaptureCursorSessionV1Enters    map[ImageCopyCaptureCursorSessionV1EnterHandler]struct{}
	privateImageCopyCaptureCursorSessionV1Leaves    map[ImageCopyCaptureCursorSessionV1LeaveHandler]struct{}
	privateImageCopyCaptureCursorSessionV1Positions map[ImageCopyCaptureCursorSessionV1PositionHandler]struct{}
	privateImageCopyCaptureCursorSessionV1Hotspots  map[ImageCopyCaptureCursorSessionV1HotspotHandler]struct{}
}

// initImageCopyCaptureCursorSessionV1 initializes the ImageCopyCaptureCursorSessionV1 object's handler maps
func (ret *ImageCopyCaptureCursorSessionV1) initImageCopyCaptureCursorSessionV1() {
	ret.privateImageCopyCaptureCursorSessionV1Enters = make(map[ImageCopyCaptureCursorSessionV1EnterHandler]struct{})
	ret.privateImageCopyCaptureCursorSessionV1Leaves = make(map[ImageCopyCaptureCursorSessionV1LeaveHandler]struct{})
	ret.privateImageCopyCaptureCursorSessionV1Positions = make(map[ImageCopyCaptureCursorSessionV1PositionHandler]struct{})
	ret.privateImageCopyCaptureCursorSessionV1Hotspots = make(map[ImageCopyCaptureCursorSessionV1HotspotHandler]struct{})
}

// NewImageCopyCaptureCursorSessionV1 is a constructor for the ImageCopyCaptureCursorSessionV1 object
func NewImageCopyCaptureCursorSessionV1(ctx *Context) *ImageCopyCaptureCursorSessionV1 {
	ret := new(ImageCopyCaptureCursorSessionV1)
	ret.initImageCopyCaptureCursorSessionV1()
	ctx.Register(ret)
	return ret
}

// Destroy delete this object
func (p *ImageCopyCaptureCursorSessionV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// GetCaptureSession get image copy capturer session
func (p *ImageCopyCaptureCursorSessionV1) GetCaptureSession() (*ImageCopyCaptureSessionV1, error) {
	retSession := NewImageCopyCaptureSessionV1(p.Context())
	return retSession, p.Context().SendRequest(p, 1, retSession)
}

// Dispatch dispatches event for object ImageCopyCaptureCursorSessionV1
func (p *ImageCopyCaptureCursorSessionV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateImageCopyCaptureCursorSessionV1Enters) > 0 {
			ev := ImageCopyCaptureCursorSessionV1EnterEvent{}
			p.mu.RLock()
			for h := range p.privateImageCopyCaptureCursorSessionV1Enters {
				h.HandleImageCopyCaptureCursorSessionV1Enter(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateImageCopyCaptureCursorSessionV1Leaves) > 0 {
			ev := ImageCopyCaptureCursorSessionV1LeaveEvent{}
			p.mu.RLock()
			for h := range p.privateImageCopyCaptureCursorSessionV1Leaves {
				h.HandleImageCopyCaptureCursorSessionV1Leave(ev)
			}
			p.mu.RUnlock()
		}
	case 2:
		if len(p.privateImageCopyCaptureCursorSessionV1Positions) > 0 {
			ev := ImageCopyCaptureCursorSessionV1PositionEvent{}
			ev.X = event.Int32()
			ev.Y = event.Int32()
			p.mu.RLock()
			for h := range p.privateImageCopyCaptureCursorSessionV1Positions {
				h.HandleImageCopyCaptureCursorSessionV1Position(ev)
			}
			p.mu.RUnlock()
		}
	case 3:
		if len(p.privateImageCopyCaptureCursorSessionV1Hotspots) > 0 {
			ev := ImageCopyCaptureCursorSessionV1HotspotEvent{}
			ev.X = event.Int32()
			ev.Y = event.Int32()
			p.mu.RLock()
			for h := range p.privateImageCopyCaptureCursorSessionV1Hotspots {
				h.HandleImageCopyCaptureCursorSessionV1Hotspot(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ImageCopyCaptureCursorSessionV1EnterEvent is the cursor entered captured area
type ImageCopyCaptureCursorSessionV1EnterEvent struct {
}

// ImageCopyCaptureCursorSessionV1LeaveEvent is the cursor left captured area
type ImageCopyCaptureCursorSessionV1LeaveEvent struct {
}

// ImageCopyCaptureCursorSessionV1PositionEvent is the position changed
type ImageCopyCaptureCursorSessionV1PositionEvent struct {
	// X is the position x coordinates
	X int32
	// Y is the position y coordinates
	Y int32
}

// ImageCopyCaptureCursorSessionV1HotspotEvent is the hotspot changed
type ImageCopyCaptureCursorSessionV1HotspotEvent struct {
	// X is the hotspot x coordinates
	X int32
	// Y is the hotspot y coordinates
	Y int32
}

// ImageCopyCaptureCursorSessionV1EnterHandler is the handler interface for ImageCopyCaptureCursorSessionV1EnterEvent
type ImageCopyCaptureCursorSessionV1EnterHandler interface {
	HandleImageCopyCaptureCursorSessionV1Enter(ImageCopyCaptureCursorSessionV1EnterEvent)
}

// AddEnterHandler adds the Enter handler
func (p *ImageCopyCaptureCursorSessionV1) AddEnterHandler(h ImageCopyCaptureCursorSessionV1EnterHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateImageCopyCaptureCursorSessionV1Enters[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveEnterHandler removes the Enter handler
func (p *ImageCopyCaptureCursorSessionV1) RemoveEnterHandler(h ImageCopyCaptureCursorSessionV1EnterHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateImageCopyCaptureCursorSessionV1Enters, h)
}

// ImageCopyCaptureCursorSessionV1LeaveHandler is the handler interface for ImageCopyCaptureCursorSessionV1LeaveEvent
type ImageCopyCaptureCursorSessionV1LeaveHandler interface {
	HandleImageCopyCaptureCursorSessionV1Leave(ImageCopyCaptureCursorSessionV1LeaveEvent)
}

// AddLeaveHandler adds the Leave handler
func (p *ImageCopyCaptureCursorSessionV1) AddLeaveHandler(h ImageCopyCaptureCursorSessionV1LeaveHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateImageCopyCaptureCursorSessionV1Leaves[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveLeaveHandler removes the Leave handler
func (p *ImageCopyCaptureCursorSessionV1) RemoveLeaveHandler(h ImageCopyCaptureCursorSessionV1LeaveHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateImageCopyCaptureCursorSessionV1Leaves, h)
}

// ImageCopyCaptureCursorSessionV1PositionHandler is the handler interface for ImageCopyCaptureCursorSessionV1PositionEvent
type ImageCopyCaptureCursorSessionV1PositionHandler interface {
	HandleImageCopyCaptureCursorSessionV1Position(ImageCopyCaptureCursorSessionV1PositionEvent)
}

// AddPositionHandler adds the Position handler
func (p *ImageCopyCaptureCursorSessionV1) AddPositionHandler(h ImageCopyCaptureCursorSessionV1PositionHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateImageCopyCaptureCursorSessionV1Positions[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemovePositionHandler removes the Position handler
func (p *ImageCopyCaptureCursorSessionV1) RemovePositionHandler(h ImageCopyCaptureCursorSessionV1PositionHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateImageCopyCaptureCursorSessionV1Positions, h)
}

// ImageCopyCaptureCursorSessionV1HotspotHandler is the handler interface for ImageCopyCaptureCursorSessionV1HotspotEvent
type ImageCopyCaptureCursorSessionV1HotspotHandler interface {
	HandleImageCopyCaptureCursorSessionV1Hotspot(ImageCopyCaptureCursorSessionV1HotspotEvent)
}

// AddHotspotHandler adds the Hotspot handler
func (p *ImageCopyCaptureCursorSessionV1) AddHotspotHandler(h ImageCopyCaptureCursorSessionV1HotspotHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateImageCopyCaptureCursorSessionV1Hotspots[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveHotspotHandler removes the Hotspot handler
func (p *ImageCopyCaptureCursorSessionV1) RemoveHotspotHandler(h ImageCopyCaptureCursorSessionV1HotspotHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateImageCopyCaptureCursorSessionV1Hotspots, h)
}
