// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: ext-image-capture-source-v1.xml
// Do not edit

// Package wlr implements the ext_image_capture_source_v1 protocol
package wlr

import ()

// ImageCaptureSourceV1 opaque image capture source object
type ImageCaptureSourceV1 struct {
	BaseProxy
}

// NewImageCaptureSourceV1 is a constructor for the ImageCaptureSourceV1 object
func NewImageCaptureSourceV1(ctx *Context) *ImageCaptureSourceV1 {
	ret := new(ImageCaptureSourceV1)
	ctx.Register(ret)
	return ret
}

// Destroy delete this object
func (p *ImageCaptureSourceV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// Dispatch dispatches event for object ImageCaptureSourceV1
func (p *ImageCaptureSourceV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// OutputImageCaptureSourceManagerV1 image capture source manager for outputs
type OutputImageCaptureSourceManagerV1 struct {
	BaseProxy
}

// NewOutputImageCaptureSourceManagerV1 is a constructor for the OutputImageCaptureSourceManagerV1 object
func NewOutputImageCaptureSourceManagerV1(ctx *Context) *OutputImageCaptureSourceManagerV1 {
	ret := new(OutputImageCaptureSourceManagerV1)
	ctx.Register(ret)
	return ret
}

// CreateSource create source object for output
func (p *OutputImageCaptureSourceManagerV1) CreateSource(Output *Output) (*ImageCaptureSourceV1, error) {
	retSource := NewImageCaptureSourceV1(p.Context())
	return retSource, p.Context().SendRequest(p, 0, retSource, Output)
}

// Destroy delete this object
func (p *OutputImageCaptureSourceManagerV1) Destroy() error {

	return p.Context().SendRequest(p, 1)
}

// Dispatch dispatches event for object OutputImageCaptureSourceManagerV1
func (p *OutputImageCaptureSourceManagerV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// ForeignToplevelImageCaptureSourceManagerV1 image capture source manager for foreign toplevels
type ForeignToplevelImageCaptureSourceManagerV1 struct {
	BaseProxy
}

// NewForeignToplevelImageCaptureSourceManagerV1 is a constructor for the ForeignToplevelImageCaptureSourceManagerV1 object
func NewForeignToplevelImageCaptureSourceManagerV1(ctx *Context) *ForeignToplevelImageCaptureSourceManagerV1 {
	ret := new(ForeignToplevelImageCaptureSourceManagerV1)
	ctx.Register(ret)
	return ret
}

// CreateSource create source object for foreign toplevel
func (p *ForeignToplevelImageCaptureSourceManagerV1) CreateSource(ToplevelHandle *ForeignToplevelHandleV1) (*ImageCaptureSourceV1, error) {
	retSource := NewImageCaptureSourceV1(p.Context())
	return retSource, p.Context().SendRequest(p, 0, retSource, ToplevelHandle)
}

// Destroy delete this object
func (p *ForeignToplevelImageCaptureSourceManagerV1) Destroy() error {

	return p.Context().SendRequest(p, 1)
}

// Dispatch dispatches event for object ForeignToplevelImageCaptureSourceManagerV1
func (p *ForeignToplevelImageCaptureSourceManagerV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}
