// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: ext-foreign-toplevel-list-v1.xml
// Do not edit

// Package wlr implements the ext_foreign_toplevel_list_v1 protocol
package wlr

import (
	"sync"
)

// ForeignToplevelListV1 list toplevels
type ForeignToplevelListV1 struct {
	BaseProxy
	mu                                    sync.RWMutex
	privateForeignToplevelListV1Toplevels map[ForeignToplevelListV1ToplevelHandler]struct{}
	privateForeignToplevelListV1Finisheds map[ForeignToplevelListV1FinishedHandler]struct{}
}

// initForeignToplevelListV1 initializes the ForeignToplevelListV1 object's handler maps
func (ret *ForeignToplevelListV1) initForeignToplevelListV1() {
	ret.privateForeignToplevelListV1Toplevels = make(map[ForeignToplevelListV1ToplevelHandler]struct{})
	ret.privateForeignToplevelListV1Finisheds = make(map[ForeignToplevelListV1FinishedHandler]struct{})
}

// NewForeignToplevelListV1 is a constructor for the ForeignToplevelListV1 object
func NewForeignToplevelListV1(ctx *Context) *ForeignToplevelListV1 {
	ret := new(ForeignToplevelListV1)
	ret.initForeignToplevelListV1()
	ctx.Register(ret)
	return ret
}

// Stop stop sending events
func (p *ForeignToplevelListV1) Stop() error {

	return p.Context().SendRequest(p, 0)
}

// Destroy destroy the ext_foreign_toplevel_list_v1 object
func (p *ForeignToplevelListV1) Destroy() error {

	return p.Context().SendRequest(p, 1)
}

// Dispatch dispatches event for object ForeignToplevelListV1
func (p *ForeignToplevelListV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateForeignToplevelListV1Toplevels) > 0 {
			ev := ForeignToplevelListV1ToplevelEvent{}
			ev.Toplevel = func() *ForeignToplevelHandleV1 {
				ret := new(ForeignToplevelHandleV1)
				ret.initForeignToplevelHandleV1()
				return event.NewId(ret, p.Context()).(*ForeignToplevelHandleV1)
			}()
			p.mu.RLock()
			for h := range p.privateForeignToplevelListV1Toplevels {
				h.HandleForeignToplevelListV1Toplevel(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateForeignToplevelListV1Finisheds) > 0 {
			ev := ForeignToplevelListV1FinishedEvent{}
			p.mu.RLock()
			for h := range p.privateForeignToplevelListV1Finisheds {
				h.HandleForeignToplevelListV1Finished(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ForeignToplevelListV1ToplevelEvent is the a toplevel has been created
type ForeignToplevelListV1ToplevelEvent struct {
	// Toplevel is the
	Toplevel *ForeignToplevelHandleV1
}

// ForeignToplevelListV1FinishedEvent is the the compositor has finished with the toplevel manager
type ForeignToplevelListV1FinishedEvent struct {
}

// ForeignToplevelListV1ToplevelHandler is the handler interface for ForeignToplevelListV1ToplevelEvent
type ForeignToplevelListV1ToplevelHandler interface {
	HandleForeignToplevelListV1Toplevel(ForeignToplevelListV1ToplevelEvent)
}

// AddToplevelHandler adds the Toplevel handler
func (p *ForeignToplevelListV1) AddToplevelHandler(h ForeignToplevelListV1ToplevelHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateForeignToplevelListV1Toplevels[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveToplevelHandler removes the Toplevel handler
func (p *ForeignToplevelListV1) RemoveToplevelHandler(h ForeignToplevelListV1ToplevelHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateForeignToplevelListV1Toplevels, h)
}

// ForeignToplevelListV1FinishedHandler is the handler interface for ForeignToplevelListV1FinishedEvent
type ForeignToplevelListV1FinishedHandler interface {
	HandleForeignToplevelListV1Finished(ForeignToplevelListV1FinishedEvent)
}

// AddFinishedHandler adds the Finished handler
func (p *ForeignToplevelListV1) AddFinishedHandler(h ForeignToplevelListV1FinishedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateForeignToplevelListV1Finisheds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveFinishedHandler removes the Finished handler
func (p *ForeignToplevelListV1) RemoveFinishedHandler(h ForeignToplevelListV1FinishedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateForeignToplevelListV1Finisheds, h)
}

// ForeignToplevelHandleV1 a mapped toplevel
type ForeignToplevelHandleV1 struct {
	BaseProxy
	mu                                        sync.RWMutex
	privateForeignToplevelHandleV1Closeds     map[ForeignToplevelHandleV1ClosedHandler]struct{}
	privateForeignToplevelHandleV1Dones       map[ForeignToplevelHandleV1DoneHandler]struct{}
	privateForeignToplevelHandleV1Titles      map[ForeignToplevelHandleV1TitleHandler]struct{}
	privateForeignToplevelHandleV1AppIds      map[ForeignToplevelHandleV1AppIdHandler]struct{}
	privateForeignToplevelHandleV1Identifiers map[ForeignToplevelHandleV1IdentifierHandler]struct{}
}

// initForeignToplevelHandleV1 initializes the ForeignToplevelHandleV1 object's handler maps
func (ret *ForeignToplevelHandleV1) initForeignToplevelHandleV1() {
	ret.privateForeignToplevelHandleV1Closeds = make(map[ForeignToplevelHandleV1ClosedHandler]struct{})
	ret.privateForeignToplevelHandleV1Dones = make(map[ForeignToplevelHandleV1DoneHandler]struct{})
	ret.privateForeignToplevelHandleV1Titles = make(map[ForeignToplevelHandleV1TitleHandler]struct{})
	ret.privateForeignToplevelHandleV1AppIds = make(map[ForeignToplevelHandleV1AppIdHandler]struct{})
	ret.privateForeignToplevelHandleV1Identifiers = make(map[ForeignToplevelHandleV1IdentifierHandler]struct{})
}

// NewForeignToplevelHandleV1 is a constructor for the ForeignToplevelHandleV1 object
func NewForeignToplevelHandleV1(ctx *Context) *ForeignToplevelHandleV1 {
	ret := new(ForeignToplevelHandleV1)
	ret.initForeignToplevelHandleV1()
	ctx.Register(ret)
	return ret
}

// Destroy destroy the ext_foreign_toplevel_handle_v1 object
func (p *ForeignToplevelHandleV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// Dispatch dispatches event for object ForeignToplevelHandleV1
func (p *ForeignToplevelHandleV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateForeignToplevelHandleV1Closeds) > 0 {
			ev := ForeignToplevelHandleV1ClosedEvent{}
			p.mu.RLock()
			for h := range p.privateForeignToplevelHandleV1Closeds {
				h.HandleForeignToplevelHandleV1Closed(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateForeignToplevelHandleV1Dones) > 0 {
			ev := ForeignToplevelHandleV1DoneEvent{}
			p.mu.RLock()
			for h := range p.privateForeignToplevelHandleV1Dones {
				h.HandleForeignToplevelHandleV1Done(ev)
			}
			p.mu.RUnlock()
		}
	case 2:
		if len(p.privateForeignToplevelHandleV1Titles) > 0 {
			ev := ForeignToplevelHandleV1TitleEvent{}
			ev.Title = event.String()
			p.mu.RLock()
			for h := range p.privateForeignToplevelHandleV1Titles {
				h.HandleForeignToplevelHandleV1Title(ev)
			}
			p.mu.RUnlock()
		}
	case 3:
		if len(p.privateForeignToplevelHandleV1AppIds) > 0 {
			ev := ForeignToplevelHandleV1AppIdEvent{}
			ev.AppId = event.String()
			p.mu.RLock()
			for h := range p.privateForeignToplevelHandleV1AppIds {
				h.HandleForeignToplevelHandleV1AppId(ev)
			}
			p.mu.RUnlock()
		}
	case 4:
		if len(p.privateForeignToplevelHandleV1Identifiers) > 0 {
			ev := ForeignToplevelHandleV1IdentifierEvent{}
			ev.Identifier = event.String()
			p.mu.RLock()
			for h := range p.privateForeignToplevelHandleV1Identifiers {
				h.HandleForeignToplevelHandleV1Identifier(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ForeignToplevelHandleV1ClosedEvent is the the toplevel has been closed
type ForeignToplevelHandleV1ClosedEvent struct {
}

// ForeignToplevelHandleV1DoneEvent is the all information about the toplevel has been sent
type ForeignToplevelHandleV1DoneEvent struct {
}

// ForeignToplevelHandleV1TitleEvent is the title change
type ForeignToplevelHandleV1TitleEvent struct {
	// Title is the
	Title string
}

// ForeignToplevelHandleV1AppIdEvent is the app_id change
type ForeignToplevelHandleV1AppIdEvent struct {
	// AppId is the
	AppId string
}

// ForeignToplevelHandleV1IdentifierEvent is the a stable identifier for a toplevel
type ForeignToplevelHandleV1IdentifierEvent struct {
	// Identifier is the
	Identifier string
}

// ForeignToplevelHandleV1ClosedHandler is the handler interface for ForeignToplevelHandleV1ClosedEvent
type ForeignToplevelHandleV1ClosedHandler interface {
	HandleForeignToplevelHandleV1Closed(ForeignToplevelHandleV1ClosedEvent)
}

// AddClosedHandler adds the Closed handler
func (p *ForeignToplevelHandleV1) AddClosedHandler(h ForeignToplevelHandleV1ClosedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateForeignToplevelHandleV1Closeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveClosedHandler removes the Closed handler
func (p *ForeignToplevelHandleV1) RemoveClosedHandler(h ForeignToplevelHandleV1ClosedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateForeignToplevelHandleV1Closeds, h)
}

// ForeignToplevelHandleV1DoneHandler is the handler interface for ForeignToplevelHandleV1DoneEvent
type ForeignToplevelHandleV1DoneHandler interface {
	HandleForeignToplevelHandleV1Done(ForeignToplevelHandleV1DoneEvent)
}

// AddDoneHandler adds the Done handler
func (p *ForeignToplevelHandleV1) AddDoneHandler(h ForeignToplevelHandleV1DoneHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateForeignToplevelHandleV1Dones[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveDoneHandler removes the Done handler
func (p *ForeignToplevelHandleV1) RemoveDoneHandler(h ForeignToplevelHandleV1DoneHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateForeignToplevelHandleV1Dones, h)
}

// ForeignToplevelHandleV1TitleHandler is the handler interface for ForeignToplevelHandleV1TitleEvent
type ForeignToplevelHandleV1TitleHandler interface {
	HandleForeignToplevelHandleV1Title(ForeignToplevelHandleV1TitleEvent)
}

// AddTitleHandler adds the Title handler
func (p *ForeignToplevelHandleV1) AddTitleHandler(h ForeignToplevelHandleV1TitleHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateForeignToplevelHandleV1Titles[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveTitleHandler removes the Title handler
func (p *ForeignToplevelHandleV1) RemoveTitleHandler(h ForeignToplevelHandleV1TitleHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateForeignToplevelHandleV1Titles, h)
}

// ForeignToplevelHandleV1AppIdHandler is the handler interface for ForeignToplevelHandleV1AppIdEvent
type ForeignToplevelHandleV1AppIdHandler interface {
	HandleForeignToplevelHandleV1AppId(ForeignToplevelHandleV1AppIdEvent)
}

// AddAppIdHandler adds the AppId handler
func (p *ForeignToplevelHandleV1) AddAppIdHandler(h ForeignToplevelHandleV1AppIdHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateForeignToplevelHandleV1AppIds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveAppIdHandler removes the AppId handler
func (p *ForeignToplevelHandleV1) RemoveAppIdHandler(h ForeignToplevelHandleV1AppIdHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateForeignToplevelHandleV1AppIds, h)
}

// ForeignToplevelHandleV1IdentifierHandler is the handler interface for ForeignToplevelHandleV1IdentifierEvent
type ForeignToplevelHandleV1IdentifierHandler interface {
	HandleForeignToplevelHandleV1Identifier(ForeignToplevelHandleV1IdentifierEvent)
}

// AddIdentifierHandler adds the Identifier handler
func (p *ForeignToplevelHandleV1) AddIdentifierHandler(h ForeignToplevelHandleV1IdentifierHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateForeignToplevelHandleV1Identifiers[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveIdentifierHandler removes the Identifier handler
func (p *ForeignToplevelHandleV1) RemoveIdentifierHandler(h ForeignToplevelHandleV1IdentifierHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateForeignToplevelHandleV1Identifiers, h)
}
