// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: ext-session-lock-v1.xml
// Do not edit

// Package wlr implements the ext_session_lock_v1 protocol
package wlr

import (
	"sync"
)

// SessionLockV1ErrorInvalidDestroy means attempted to destroy session lock while locked
const SessionLockV1ErrorInvalidDestroy = 0

// SessionLockV1ErrorInvalidUnlock means unlock requested but locked event was never sent
const SessionLockV1ErrorInvalidUnlock = 1

// SessionLockV1ErrorRole means given wl_surface already has a role
const SessionLockV1ErrorRole = 2

// SessionLockV1ErrorDuplicateOutput means given output already has a lock surface
const SessionLockV1ErrorDuplicateOutput = 3

// SessionLockV1ErrorAlreadyConstructed means given wl_surface has a buffer attached or committed
const SessionLockV1ErrorAlreadyConstructed = 4

// SessionLockSurfaceV1ErrorCommitBeforeFirstAck means surface committed before first ack_configure request
const SessionLockSurfaceV1ErrorCommitBeforeFirstAck = 0

// SessionLockSurfaceV1ErrorNullBuffer means surface committed with a null buffer
const SessionLockSurfaceV1ErrorNullBuffer = 1

// SessionLockSurfaceV1ErrorDimensionsMismatch means failed to match ack'd width/height
const SessionLockSurfaceV1ErrorDimensionsMismatch = 2

// SessionLockSurfaceV1ErrorInvalidSerial means serial provided in ack_configure is invalid
const SessionLockSurfaceV1ErrorInvalidSerial = 3

// SessionLockManagerV1 used to lock the session
type SessionLockManagerV1 struct {
	BaseProxy
}

// NewSessionLockManagerV1 is a constructor for the SessionLockManagerV1 object
func NewSessionLockManagerV1(ctx *Context) *SessionLockManagerV1 {
	ret := new(SessionLockManagerV1)
	ctx.Register(ret)
	return ret
}

// Destroy destroy the session lock manager object
func (p *SessionLockManagerV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// Lock attempt to lock the session
func (p *SessionLockManagerV1) Lock() (*SessionLockV1, error) {
	retId := NewSessionLockV1(p.Context())
	return retId, p.Context().SendRequest(p, 1, retId)
}

// Dispatch dispatches event for object SessionLockManagerV1
func (p *SessionLockManagerV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// SessionLockV1 manage lock state and create lock surfaces
type SessionLockV1 struct {
	BaseProxy
	mu                            sync.RWMutex
	privateSessionLockV1Lockeds   map[SessionLockV1LockedHandler]struct{}
	privateSessionLockV1Finisheds map[SessionLockV1FinishedHandler]struct{}
}

// initSessionLockV1 initializes the SessionLockV1 object's handler maps
func (ret *SessionLockV1) initSessionLockV1() {
	ret.privateSessionLockV1Lockeds = make(map[SessionLockV1LockedHandler]struct{})
	ret.privateSessionLockV1Finisheds = make(map[SessionLockV1FinishedHandler]struct{})
}

// NewSessionLockV1 is a constructor for the SessionLockV1 object
func NewSessionLockV1(ctx *Context) *SessionLockV1 {
	ret := new(SessionLockV1)
	ret.initSessionLockV1()
	ctx.Register(ret)
	return ret
}

// Destroy destroy the session lock
func (p *SessionLockV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// GetLockSurface create a lock surface for a given output
func (p *SessionLockV1) GetLockSurface(Surface *Surface, Output *Output) (*SessionLockSurfaceV1, error) {
	retId := NewSessionLockSurfaceV1(p.Context())
	return retId, p.Context().SendRequest(p, 1, retId, Surface, Output)
}

// UnlockAndDestroy unlock the session, destroying the object
func (p *SessionLockV1) UnlockAndDestroy() error {

	return p.Context().SendRequest(p, 2)
}

// Dispatch dispatches event for object SessionLockV1
func (p *SessionLockV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateSessionLockV1Lockeds) > 0 {
			ev := SessionLockV1LockedEvent{}
			p.mu.RLock()
			for h := range p.privateSessionLockV1Lockeds {
				h.HandleSessionLockV1Locked(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateSessionLockV1Finisheds) > 0 {
			ev := SessionLockV1FinishedEvent{}
			p.mu.RLock()
			for h := range p.privateSessionLockV1Finisheds {
				h.HandleSessionLockV1Finished(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// SessionLockV1LockedEvent is the session successfully locked
type SessionLockV1LockedEvent struct {
}

// SessionLockV1FinishedEvent is the the session lock object should be destroyed
type SessionLockV1FinishedEvent struct {
}

// SessionLockV1LockedHandler is the handler interface for SessionLockV1LockedEvent
type SessionLockV1LockedHandler interface {
	HandleSessionLockV1Locked(SessionLockV1LockedEvent)
}

// AddLockedHandler adds the Locked handler
func (p *SessionLockV1) AddLockedHandler(h SessionLockV1LockedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateSessionLockV1Lockeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveLockedHandler removes the Locked handler
func (p *SessionLockV1) RemoveLockedHandler(h SessionLockV1LockedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateSessionLockV1Lockeds, h)
}

// SessionLockV1FinishedHandler is the handler interface for SessionLockV1FinishedEvent
type SessionLockV1FinishedHandler interface {
	HandleSessionLockV1Finished(SessionLockV1FinishedEvent)
}

// AddFinishedHandler adds the Finished handler
func (p *SessionLockV1) AddFinishedHandler(h SessionLockV1FinishedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateSessionLockV1Finisheds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveFinishedHandler removes the Finished handler
func (p *SessionLockV1) RemoveFinishedHandler(h SessionLockV1FinishedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateSessionLockV1Finisheds, h)
}

// SessionLockSurfaceV1 a surface displayed while the session is locked
type SessionLockSurfaceV1 struct {
	BaseProxy
	mu                                    sync.RWMutex
	privateSessionLockSurfaceV1Configures map[SessionLockSurfaceV1ConfigureHandler]struct{}
}

// initSessionLockSurfaceV1 initializes the SessionLockSurfaceV1 object's handler maps
func (ret *SessionLockSurfaceV1) initSessionLockSurfaceV1() {
	ret.privateSessionLockSurfaceV1Configures = make(map[SessionLockSurfaceV1ConfigureHandler]struct{})
}

// NewSessionLockSurfaceV1 is a constructor for the SessionLockSurfaceV1 object
func NewSessionLockSurfaceV1(ctx *Context) *SessionLockSurfaceV1 {
	ret := new(SessionLockSurfaceV1)
	ret.initSessionLockSurfaceV1()
	ctx.Register(ret)
	return ret
}

// Destroy destroy the lock surface object
func (p *SessionLockSurfaceV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// AckConfigure ack a configure event
func (p *SessionLockSurfaceV1) AckConfigure(Serial uint32) error {

	return p.Context().SendRequest(p, 1, Serial)
}

// Dispatch dispatches event for object SessionLockSurfaceV1
func (p *SessionLockSurfaceV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateSessionLockSurfaceV1Configures) > 0 {
			ev := SessionLockSurfaceV1ConfigureEvent{}
			ev.Serial = event.Uint32()
			ev.Width = event.Uint32()
			ev.Height = event.Uint32()
			p.mu.RLock()
			for h := range p.privateSessionLockSurfaceV1Configures {
				h.HandleSessionLockSurfaceV1Configure(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// SessionLockSurfaceV1ConfigureEvent is the the client should resize its surface
type SessionLockSurfaceV1ConfigureEvent struct {
	// Serial is the serial for use in ack_configure
	Serial uint32
	// Width is the
	Width uint32
	// Height is the
	Height uint32
}

// SessionLockSurfaceV1ConfigureHandler is the handler interface for SessionLockSurfaceV1ConfigureEvent
type SessionLockSurfaceV1ConfigureHandler interface {
	HandleSessionLockSurfaceV1Configure(SessionLockSurfaceV1ConfigureEvent)
}

// AddConfigureHandler adds the Configure handler
func (p *SessionLockSurfaceV1) AddConfigureHandler(h SessionLockSurfaceV1ConfigureHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateSessionLockSurfaceV1Configures[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveConfigureHandler removes the Configure handler
func (p *SessionLockSurfaceV1) RemoveConfigureHandler(h SessionLockSurfaceV1ConfigureHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateSessionLockSurfaceV1Configures, h)
}
