// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: hyprland-global-shortcuts-v1.xml
// Do not edit

// Package wlr implements the hyprland_global_shortcuts_v1 protocol
package wlr

import (
	"sync"
)

// GlobalShortcutsManagerV1ErrorAlreadyTaken means the app_id + id combination has already been registered.
const GlobalShortcutsManagerV1ErrorAlreadyTaken = 0

// GlobalShortcutsManagerV1 manager to register global shortcuts
type GlobalShortcutsManagerV1 struct {
	BaseProxy
}

// NewGlobalShortcutsManagerV1 is a constructor for the GlobalShortcutsManagerV1 object
func NewGlobalShortcutsManagerV1(ctx *Context) *GlobalShortcutsManagerV1 {
	ret := new(GlobalShortcutsManagerV1)
	ctx.Register(ret)
	return ret
}

// RegisterShortcut register a shortcut
func (p *GlobalShortcutsManagerV1) RegisterShortcut(Id string, AppId string, Description string, TriggerDescription string) (*GlobalShortcutV1, error) {
	retShortcut := NewGlobalShortcutV1(p.Context())
	return retShortcut, p.Context().SendRequest(p, 0, retShortcut, Id, AppId, Description, TriggerDescription)
}

// Destroy destroy the manager
func (p *GlobalShortcutsManagerV1) Destroy() error {

	return p.Context().SendRequest(p, 1)
}

// Dispatch dispatches event for object GlobalShortcutsManagerV1
func (p *GlobalShortcutsManagerV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// GlobalShortcutV1 a shortcut
type GlobalShortcutV1 struct {
	BaseProxy
	mu                               sync.RWMutex
	privateGlobalShortcutV1Presseds  map[GlobalShortcutV1PressedHandler]struct{}
	privateGlobalShortcutV1Releaseds map[GlobalShortcutV1ReleasedHandler]struct{}
}

// initGlobalShortcutV1 initializes the GlobalShortcutV1 object's handler maps
func (ret *GlobalShortcutV1) initGlobalShortcutV1() {
	ret.privateGlobalShortcutV1Presseds = make(map[GlobalShortcutV1PressedHandler]struct{})
	ret.privateGlobalShortcutV1Releaseds = make(map[GlobalShortcutV1ReleasedHandler]struct{})
}

// NewGlobalShortcutV1 is a constructor for the GlobalShortcutV1 object
func NewGlobalShortcutV1(ctx *Context) *GlobalShortcutV1 {
	ret := new(GlobalShortcutV1)
	ret.initGlobalShortcutV1()
	ctx.Register(ret)
	return ret
}

// Destroy delete this object, used or not
func (p *GlobalShortcutV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// Dispatch dispatches event for object GlobalShortcutV1
func (p *GlobalShortcutV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateGlobalShortcutV1Presseds) > 0 {
			ev := GlobalShortcutV1PressedEvent{}
			ev.TvSecHi = event.Uint32()
			ev.TvSecLo = event.Uint32()
			ev.TvNsec = event.Uint32()
			p.mu.RLock()
			for h := range p.privateGlobalShortcutV1Presseds {
				h.HandleGlobalShortcutV1Pressed(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateGlobalShortcutV1Releaseds) > 0 {
			ev := GlobalShortcutV1ReleasedEvent{}
			ev.TvSecHi = event.Uint32()
			ev.TvSecLo = event.Uint32()
			ev.TvNsec = event.Uint32()
			p.mu.RLock()
			for h := range p.privateGlobalShortcutV1Releaseds {
				h.HandleGlobalShortcutV1Released(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// GlobalShortcutV1PressedEvent is the keystroke pressed
type GlobalShortcutV1PressedEvent struct {
	// TvSecHi is the high 32 bits of the seconds part of the timestamp
	TvSecHi uint32
	// TvSecLo is the low 32 bits of the seconds part of the timestamp
	TvSecLo uint32
	// TvNsec is the nanoseconds part of the timestamp
	TvNsec uint32
}

// GlobalShortcutV1ReleasedEvent is the keystroke released
type GlobalShortcutV1ReleasedEvent struct {
	// TvSecHi is the high 32 bits of the seconds part of the timestamp
	TvSecHi uint32
	// TvSecLo is the low 32 bits of the seconds part of the timestamp
	TvSecLo uint32
	// TvNsec is the nanoseconds part of the timestamp
	TvNsec uint32
}

// GlobalShortcutV1PressedHandler is the handler interface for GlobalShortcutV1PressedEvent
type GlobalShortcutV1PressedHandler interface {
	HandleGlobalShortcutV1Pressed(GlobalShortcutV1PressedEvent)
}

// AddPressedHandler adds the Pressed handler
func (p *GlobalShortcutV1) AddPressedHandler(h GlobalShortcutV1PressedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateGlobalShortcutV1Presseds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemovePressedHandler removes the Pressed handler
func (p *GlobalShortcutV1) RemovePressedHandler(h GlobalShortcutV1PressedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateGlobalShortcutV1Presseds, h)
}

// GlobalShortcutV1ReleasedHandler is the handler interface for GlobalShortcutV1ReleasedEvent
type GlobalShortcutV1ReleasedHandler interface {
	HandleGlobalShortcutV1Released(GlobalShortcutV1ReleasedEvent)
}

// AddReleasedHandler adds the Released handler
func (p *GlobalShortcutV1) AddReleasedHandler(h GlobalShortcutV1ReleasedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateGlobalShortcutV1Releaseds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveReleasedHandler removes the Released handler
func (p *GlobalShortcutV1) RemoveReleasedHandler(h GlobalShortcutV1ReleasedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateGlobalShortcutV1Releaseds, h)
}
