// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: hyprland-toplevel-export-v1.xml
// Do not edit

// Package wlr implements the hyprland_toplevel_export_v1 protocol
package wlr

import (
	"sync"
)

// ToplevelExportFrameV1ErrorAlreadyUsed means the object has already been used to copy a wl_buffer
const ToplevelExportFrameV1ErrorAlreadyUsed = 0

// ToplevelExportFrameV1ErrorInvalidBuffer means buffer attributes are invalid
const ToplevelExportFrameV1ErrorInvalidBuffer = 1

// ToplevelExportFrameV1FlagsYInvert means contents are y-inverted
const ToplevelExportFrameV1FlagsYInvert = 1

// ToplevelExportManagerV1 manager to inform clients and begin capturing
type ToplevelExportManagerV1 struct {
	BaseProxy
}

// NewToplevelExportManagerV1 is a constructor for the ToplevelExportManagerV1 object
func NewToplevelExportManagerV1(ctx *Context) *ToplevelExportManagerV1 {
	ret := new(ToplevelExportManagerV1)
	ctx.Register(ret)
	return ret
}

// CaptureToplevel capture a toplevel
func (p *ToplevelExportManagerV1) CaptureToplevel(OverlayCursor int32, Handle uint32) (*ToplevelExportFrameV1, error) {
	retFrame := NewToplevelExportFrameV1(p.Context())
	return retFrame, p.Context().SendRequest(p, 0, retFrame, OverlayCursor, Handle)
}

// Destroy destroy the manager
func (p *ToplevelExportManagerV1) Destroy() error {

	return p.Context().SendRequest(p, 1)
}

// CaptureToplevelWithWlrToplevelHandle capture a toplevel
func (p *ToplevelExportManagerV1) CaptureToplevelWithWlrToplevelHandle(OverlayCursor int32, Handle *ZwlrForeignToplevelHandleV1) (*ToplevelExportFrameV1, error) {
	retFrame := NewToplevelExportFrameV1(p.Context())
	return retFrame, p.Context().SendRequest(p, 2, retFrame, OverlayCursor, Handle)
}

// Dispatch dispatches event for object ToplevelExportManagerV1
func (p *ToplevelExportManagerV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// ToplevelExportFrameV1 a frame ready for copy
type ToplevelExportFrameV1 struct {
	BaseProxy
	mu                                       sync.RWMutex
	privateToplevelExportFrameV1Buffers      map[ToplevelExportFrameV1BufferHandler]struct{}
	privateToplevelExportFrameV1Damages      map[ToplevelExportFrameV1DamageHandler]struct{}
	privateToplevelExportFrameV1Flagss       map[ToplevelExportFrameV1FlagsHandler]struct{}
	privateToplevelExportFrameV1Readys       map[ToplevelExportFrameV1ReadyHandler]struct{}
	privateToplevelExportFrameV1Faileds      map[ToplevelExportFrameV1FailedHandler]struct{}
	privateToplevelExportFrameV1LinuxDmabufs map[ToplevelExportFrameV1LinuxDmabufHandler]struct{}
	privateToplevelExportFrameV1BufferDones  map[ToplevelExportFrameV1BufferDoneHandler]struct{}
}

// initToplevelExportFrameV1 initializes the ToplevelExportFrameV1 object's handler maps
func (ret *ToplevelExportFrameV1) initToplevelExportFrameV1() {
	ret.privateToplevelExportFrameV1Buffers = make(map[ToplevelExportFrameV1BufferHandler]struct{})
	ret.privateToplevelExportFrameV1Damages = make(map[ToplevelExportFrameV1DamageHandler]struct{})
	ret.privateToplevelExportFrameV1Flagss = make(map[ToplevelExportFrameV1FlagsHandler]struct{})
	ret.privateToplevelExportFrameV1Readys = make(map[ToplevelExportFrameV1ReadyHandler]struct{})
	ret.privateToplevelExportFrameV1Faileds = make(map[ToplevelExportFrameV1FailedHandler]struct{})
	ret.privateToplevelExportFrameV1LinuxDmabufs = make(map[ToplevelExportFrameV1LinuxDmabufHandler]struct{})
	ret.privateToplevelExportFrameV1BufferDones = make(map[ToplevelExportFrameV1BufferDoneHandler]struct{})
}

// NewToplevelExportFrameV1 is a constructor for the ToplevelExportFrameV1 object
func NewToplevelExportFrameV1(ctx *Context) *ToplevelExportFrameV1 {
	ret := new(ToplevelExportFrameV1)
	ret.initToplevelExportFrameV1()
	ctx.Register(ret)
	return ret
}

// Copy copy the frame
func (p *ToplevelExportFrameV1) Copy(Buffer *Buffer, IgnoreDamage int32) error {

	return p.Context().SendRequest(p, 0, Buffer, IgnoreDamage)
}

// Destroy delete this object, used or not
func (p *ToplevelExportFrameV1) Destroy() error {

	return p.Context().SendRequest(p, 1)
}

// Dispatch dispatches event for object ToplevelExportFrameV1
func (p *ToplevelExportFrameV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateToplevelExportFrameV1Buffers) > 0 {
			ev := ToplevelExportFrameV1BufferEvent{}
			ev.Format = event.Uint32()
			ev.Width = event.Uint32()
			ev.Height = event.Uint32()
			ev.Stride = event.Uint32()
			p.mu.RLock()
			for h := range p.privateToplevelExportFrameV1Buffers {
				h.HandleToplevelExportFrameV1Buffer(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateToplevelExportFrameV1Damages) > 0 {
			ev := ToplevelExportFrameV1DamageEvent{}
			ev.X = event.Uint32()
			ev.Y = event.Uint32()
			ev.Width = event.Uint32()
			ev.Height = event.Uint32()
			p.mu.RLock()
			for h := range p.privateToplevelExportFrameV1Damages {
				h.HandleToplevelExportFrameV1Damage(ev)
			}
			p.mu.RUnlock()
		}
	case 2:
		if len(p.privateToplevelExportFrameV1Flagss) > 0 {
			ev := ToplevelExportFrameV1FlagsEvent{}
			ev.Flags = event.Uint32()
			p.mu.RLock()
			for h := range p.privateToplevelExportFrameV1Flagss {
				h.HandleToplevelExportFrameV1Flags(ev)
			}
			p.mu.RUnlock()
		}
	case 3:
		if len(p.privateToplevelExportFrameV1Readys) > 0 {
			ev := ToplevelExportFrameV1ReadyEvent{}
			ev.TvSecHi = event.Uint32()
			ev.TvSecLo = event.Uint32()
			ev.TvNsec = event.Uint32()
			p.mu.RLock()
			for h := range p.privateToplevelExportFrameV1Readys {
				h.HandleToplevelExportFrameV1Ready(ev)
			}
			p.mu.RUnlock()
		}
	case 4:
		if len(p.privateToplevelExportFrameV1Faileds) > 0 {
			ev := ToplevelExportFrameV1FailedEvent{}
			p.mu.RLock()
			for h := range p.privateToplevelExportFrameV1Faileds {
				h.HandleToplevelExportFrameV1Failed(ev)
			}
			p.mu.RUnlock()
		}
	case 5:
		if len(p.privateToplevelExportFrameV1LinuxDmabufs) > 0 {
			ev := ToplevelExportFrameV1LinuxDmabufEvent{}
			ev.Format = event.Uint32()
			ev.Width = event.Uint32()
			ev.Height = event.Uint32()
			p.mu.RLock()
			for h := range p.privateToplevelExportFrameV1LinuxDmabufs {
				h.HandleToplevelExportFrameV1LinuxDmabuf(ev)
			}
			p.mu.RUnlock()
		}
	case 6:
		if len(p.privateToplevelExportFrameV1BufferDones) > 0 {
			ev := ToplevelExportFrameV1BufferDoneEvent{}
			p.mu.RLock()
			for h := range p.privateToplevelExportFrameV1BufferDones {
				h.HandleToplevelExportFrameV1BufferDone(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ToplevelExportFrameV1BufferEvent is the wl_shm buffer information
type ToplevelExportFrameV1BufferEvent struct {
	// Format is the buffer format
	Format uint32
	// Width is the buffer width
	Width uint32
	// Height is the buffer height
	Height uint32
	// Stride is the buffer stride
	Stride uint32
}

// ToplevelExportFrameV1DamageEvent is the carries the coordinates of the damaged region
type ToplevelExportFrameV1DamageEvent struct {
	// X is the damaged x coordinates
	X uint32
	// Y is the damaged y coordinates
	Y uint32
	// Width is the current width
	Width uint32
	// Height is the current height
	Height uint32
}

// ToplevelExportFrameV1FlagsEvent is the frame flags
type ToplevelExportFrameV1FlagsEvent struct {
	// Flags is the frame flags
	Flags uint32
}

// ToplevelExportFrameV1ReadyEvent is the indicates frame is available for reading
type ToplevelExportFrameV1ReadyEvent struct {
	// TvSecHi is the high 32 bits of the seconds part of the timestamp
	TvSecHi uint32
	// TvSecLo is the low 32 bits of the seconds part of the timestamp
	TvSecLo uint32
	// TvNsec is the nanoseconds part of the timestamp
	TvNsec uint32
}

// ToplevelExportFrameV1FailedEvent is the frame copy failed
type ToplevelExportFrameV1FailedEvent struct {
}

// ToplevelExportFrameV1LinuxDmabufEvent is the linux-dmabuf buffer information
type ToplevelExportFrameV1LinuxDmabufEvent struct {
	// Format is the fourcc pixel format
	Format uint32
	// Width is the buffer width
	Width uint32
	// Height is the buffer height
	Height uint32
}

// ToplevelExportFrameV1BufferDoneEvent is the all buffer types reported
type ToplevelExportFrameV1BufferDoneEvent struct {
}

// ToplevelExportFrameV1BufferHandler is the handler interface for ToplevelExportFrameV1BufferEvent
type ToplevelExportFrameV1BufferHandler interface {
	HandleToplevelExportFrameV1Buffer(ToplevelExportFrameV1BufferEvent)
}

// AddBufferHandler adds the Buffer handler
func (p *ToplevelExportFrameV1) AddBufferHandler(h ToplevelExportFrameV1BufferHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateToplevelExportFrameV1Buffers[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveBufferHandler removes the Buffer handler
func (p *ToplevelExportFrameV1) RemoveBufferHandler(h ToplevelExportFrameV1BufferHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateToplevelExportFrameV1Buffers, h)
}

// ToplevelExportFrameV1DamageHandler is the handler interface for ToplevelExportFrameV1DamageEvent
type ToplevelExportFrameV1DamageHandler interface {
	HandleToplevelExportFrameV1Damage(ToplevelExportFrameV1DamageEvent)
}

// AddDamageHandler adds the Damage handler
func (p *ToplevelExportFrameV1) AddDamageHandler(h ToplevelExportFrameV1DamageHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateToplevelExportFrameV1Damages[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveDamageHandler removes the Damage handler
func (p *ToplevelExportFrameV1) RemoveDamageHandler(h ToplevelExportFrameV1DamageHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateToplevelExportFrameV1Damages, h)
}

// ToplevelExportFrameV1FlagsHandler is the handler interface for ToplevelExportFrameV1FlagsEvent
type ToplevelExportFrameV1FlagsHandler interface {
	HandleToplevelExportFrameV1Flags(ToplevelExportFrameV1FlagsEvent)
}

// AddFlagsHandler adds the Flags handler
func (p *ToplevelExportFrameV1) AddFlagsHandler(h ToplevelExportFrameV1FlagsHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateToplevelExportFrameV1Flagss[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveFlagsHandler removes the Flags handler
func (p *ToplevelExportFrameV1) RemoveFlagsHandler(h ToplevelExportFrameV1FlagsHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateToplevelExportFrameV1Flagss, h)
}

// ToplevelExportFrameV1ReadyHandler is the handler interface for ToplevelExportFrameV1ReadyEvent
type ToplevelExportFrameV1ReadyHandler interface {
	HandleToplevelExportFrameV1Ready(ToplevelExportFrameV1ReadyEvent)
}

// AddReadyHandler adds the Ready handler
func (p *ToplevelExportFrameV1) AddReadyHandler(h ToplevelExportFrameV1ReadyHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateToplevelExportFrameV1Readys[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveReadyHandler removes the Ready handler
func (p *ToplevelExportFrameV1) RemoveReadyHandler(h ToplevelExportFrameV1ReadyHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateToplevelExportFrameV1Readys, h)
}

// ToplevelExportFrameV1FailedHandler is the handler interface for ToplevelExportFrameV1FailedEvent
type ToplevelExportFrameV1FailedHandler interface {
	HandleToplevelExportFrameV1Failed(ToplevelExportFrameV1FailedEvent)
}

// AddFailedHandler adds the Failed handler
func (p *ToplevelExportFrameV1) AddFailedHandler(h ToplevelExportFrameV1FailedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateToplevelExportFrameV1Faileds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveFailedHandler removes the Failed handler
func (p *ToplevelExportFrameV1) RemoveFailedHandler(h ToplevelExportFrameV1FailedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateToplevelExportFrameV1Faileds, h)
}

// ToplevelExportFrameV1LinuxDmabufHandler is the handler interface for ToplevelExportFrameV1LinuxDmabufEvent
type ToplevelExportFrameV1LinuxDmabufHandler interface {
	HandleToplevelExportFrameV1LinuxDmabuf(ToplevelExportFrameV1LinuxDmabufEvent)
}

// AddLinuxDmabufHandler adds the LinuxDmabuf handler
func (p *ToplevelExportFrameV1) AddLinuxDmabufHandler(h ToplevelExportFrameV1LinuxDmabufHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateToplevelExportFrameV1LinuxDmabufs[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveLinuxDmabufHandler removes the LinuxDmabuf handler
func (p *ToplevelExportFrameV1) RemoveLinuxDmabufHandler(h ToplevelExportFrameV1LinuxDmabufHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateToplevelExportFrameV1LinuxDmabufs, h)
}

// ToplevelExportFrameV1BufferDoneHandler is the handler interface for ToplevelExportFrameV1BufferDoneEvent
type ToplevelExportFrameV1BufferDoneHandler interface {
	HandleToplevelExportFrameV1BufferDone(ToplevelExportFrameV1BufferDoneEvent)
}

// AddBufferDoneHandler adds the BufferDone handler
func (p *ToplevelExportFrameV1) AddBufferDoneHandler(h ToplevelExportFrameV1BufferDoneHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateToplevelExportFrameV1BufferDones[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveBufferDoneHandler removes the BufferDone handler
func (p *ToplevelExportFrameV1) RemoveBufferDoneHandler(h ToplevelExportFrameV1BufferDoneHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateToplevelExportFrameV1BufferDones, h)
}
