// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: idle-inhibit-unstable-v1.xml
// Do not edit

// Package wlr implements the idle_inhibit_unstable_v1 protocol
package wlr

import ()

// ZwpInhibitManagerV1 control behavior when display idles
type ZwpInhibitManagerV1 struct {
	BaseProxy
}

// NewZwpInhibitManagerV1 is a constructor for the ZwpInhibitManagerV1 object
func NewZwpInhibitManagerV1(ctx *Context) *ZwpInhibitManagerV1 {
	ret := new(ZwpInhibitManagerV1)
	ctx.Register(ret)
	return ret
}

// Destroy destroy the idle inhibitor object
func (p *ZwpInhibitManagerV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// CreateInhibitor create a new inhibitor object
func (p *ZwpInhibitManagerV1) CreateInhibitor(Surface *Surface) (*ZwpInhibitorV1, error) {
	retId := NewZwpInhibitorV1(p.Context())
	return retId, p.Context().SendRequest(p, 1, retId, Surface)
}

// Dispatch dispatches event for object ZwpInhibitManagerV1
func (p *ZwpInhibitManagerV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// ZwpInhibitorV1 context object for inhibiting idle behavior
type ZwpInhibitorV1 struct {
	BaseProxy
}

// NewZwpInhibitorV1 is a constructor for the ZwpInhibitorV1 object
func NewZwpInhibitorV1(ctx *Context) *ZwpInhibitorV1 {
	ret := new(ZwpInhibitorV1)
	ctx.Register(ret)
	return ret
}

// Destroy destroy the idle inhibitor object
func (p *ZwpInhibitorV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// Dispatch dispatches event for object ZwpInhibitorV1
func (p *ZwpInhibitorV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}
