// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: keyboard-shortcuts-inhibit-unstable-v1.xml
// Do not edit

// Package wlr implements the keyboard_shortcuts_inhibit_unstable_v1 protocol
package wlr

import (
	"sync"
)

// ZwpShortcutsInhibitManagerV1ErrorAlreadyInhibited means the shortcuts are already inhibited for this surface
const ZwpShortcutsInhibitManagerV1ErrorAlreadyInhibited = 0

// ZwpShortcutsInhibitManagerV1 context object for keyboard grab_manager
type ZwpShortcutsInhibitManagerV1 struct {
	BaseProxy
}

// NewZwpShortcutsInhibitManagerV1 is a constructor for the ZwpShortcutsInhibitManagerV1 object
func NewZwpShortcutsInhibitManagerV1(ctx *Context) *ZwpShortcutsInhibitManagerV1 {
	ret := new(ZwpShortcutsInhibitManagerV1)
	ctx.Register(ret)
	return ret
}

// Destroy destroy the keyboard shortcuts inhibitor object
func (p *ZwpShortcutsInhibitManagerV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// InhibitShortcuts create a new keyboard shortcuts inhibitor object
func (p *ZwpShortcutsInhibitManagerV1) InhibitShortcuts(Surface *Surface, Seat *Seat) (*ZwpShortcutsInhibitorV1, error) {
	retId := NewZwpShortcutsInhibitorV1(p.Context())
	return retId, p.Context().SendRequest(p, 1, retId, Surface, Seat)
}

// Dispatch dispatches event for object ZwpShortcutsInhibitManagerV1
func (p *ZwpShortcutsInhibitManagerV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// ZwpShortcutsInhibitorV1 context object for keyboard shortcuts inhibitor
type ZwpShortcutsInhibitorV1 struct {
	BaseProxy
	mu                                      sync.RWMutex
	privateZwpShortcutsInhibitorV1Actives   map[ZwpShortcutsInhibitorV1ActiveHandler]struct{}
	privateZwpShortcutsInhibitorV1Inactives map[ZwpShortcutsInhibitorV1InactiveHandler]struct{}
}

// initZwpShortcutsInhibitorV1 initializes the ZwpShortcutsInhibitorV1 object's handler maps
func (ret *ZwpShortcutsInhibitorV1) initZwpShortcutsInhibitorV1() {
	ret.privateZwpShortcutsInhibitorV1Actives = make(map[ZwpShortcutsInhibitorV1ActiveHandler]struct{})
	ret.privateZwpShortcutsInhibitorV1Inactives = make(map[ZwpShortcutsInhibitorV1InactiveHandler]struct{})
}

// NewZwpShortcutsInhibitorV1 is a constructor for the ZwpShortcutsInhibitorV1 object
func NewZwpShortcutsInhibitorV1(ctx *Context) *ZwpShortcutsInhibitorV1 {
	ret := new(ZwpShortcutsInhibitorV1)
	ret.initZwpShortcutsInhibitorV1()
	ctx.Register(ret)
	return ret
}

// Destroy destroy the keyboard shortcuts inhibitor object
func (p *ZwpShortcutsInhibitorV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// Dispatch dispatches event for object ZwpShortcutsInhibitorV1
func (p *ZwpShortcutsInhibitorV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwpShortcutsInhibitorV1Actives) > 0 {
			ev := ZwpShortcutsInhibitorV1ActiveEvent{}
			p.mu.RLock()
			for h := range p.privateZwpShortcutsInhibitorV1Actives {
				h.HandleZwpShortcutsInhibitorV1Active(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateZwpShortcutsInhibitorV1Inactives) > 0 {
			ev := ZwpShortcutsInhibitorV1InactiveEvent{}
			p.mu.RLock()
			for h := range p.privateZwpShortcutsInhibitorV1Inactives {
				h.HandleZwpShortcutsInhibitorV1Inactive(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ZwpShortcutsInhibitorV1ActiveEvent is the shortcuts are inhibited
type ZwpShortcutsInhibitorV1ActiveEvent struct {
}

// ZwpShortcutsInhibitorV1InactiveEvent is the shortcuts are restored
type ZwpShortcutsInhibitorV1InactiveEvent struct {
}

// ZwpShortcutsInhibitorV1ActiveHandler is the handler interface for ZwpShortcutsInhibitorV1ActiveEvent
type ZwpShortcutsInhibitorV1ActiveHandler interface {
	HandleZwpShortcutsInhibitorV1Active(ZwpShortcutsInhibitorV1ActiveEvent)
}

// AddActiveHandler adds the Active handler
func (p *ZwpShortcutsInhibitorV1) AddActiveHandler(h ZwpShortcutsInhibitorV1ActiveHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpShortcutsInhibitorV1Actives[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveActiveHandler removes the Active handler
func (p *ZwpShortcutsInhibitorV1) RemoveActiveHandler(h ZwpShortcutsInhibitorV1ActiveHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpShortcutsInhibitorV1Actives, h)
}

// ZwpShortcutsInhibitorV1InactiveHandler is the handler interface for ZwpShortcutsInhibitorV1InactiveEvent
type ZwpShortcutsInhibitorV1InactiveHandler interface {
	HandleZwpShortcutsInhibitorV1Inactive(ZwpShortcutsInhibitorV1InactiveEvent)
}

// AddInactiveHandler adds the Inactive handler
func (p *ZwpShortcutsInhibitorV1) AddInactiveHandler(h ZwpShortcutsInhibitorV1InactiveHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpShortcutsInhibitorV1Inactives[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveInactiveHandler removes the Inactive handler
func (p *ZwpShortcutsInhibitorV1) RemoveInactiveHandler(h ZwpShortcutsInhibitorV1InactiveHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpShortcutsInhibitorV1Inactives, h)
}
