// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: pointer-gestures-unstable-v1.xml
// Do not edit

// Package wlr implements the pointer_gestures_unstable_v1 protocol
package wlr

import (
	"sync"
)

// ZwpGesturesV1 touchpad gestures
type ZwpGesturesV1 struct {
	BaseProxy
}

// NewZwpGesturesV1 is a constructor for the ZwpGesturesV1 object
func NewZwpGesturesV1(ctx *Context) *ZwpGesturesV1 {
	ret := new(ZwpGesturesV1)
	ctx.Register(ret)
	return ret
}

// GetSwipeGesture get swipe gesture
func (p *ZwpGesturesV1) GetSwipeGesture(Pointer *Pointer) (*ZwpGestureSwipeV1, error) {
	retId := NewZwpGestureSwipeV1(p.Context())
	return retId, p.Context().SendRequest(p, 0, retId, Pointer)
}

// GetPinchGesture get pinch gesture
func (p *ZwpGesturesV1) GetPinchGesture(Pointer *Pointer) (*ZwpGesturePinchV1, error) {
	retId := NewZwpGesturePinchV1(p.Context())
	return retId, p.Context().SendRequest(p, 1, retId, Pointer)
}

// Release destroy the pointer gesture object
func (p *ZwpGesturesV1) Release() error {

	return p.Context().SendRequest(p, 2)
}

// GetHoldGesture get hold gesture
func (p *ZwpGesturesV1) GetHoldGesture(Pointer *Pointer) (*ZwpGestureHoldV1, error) {
	retId := NewZwpGestureHoldV1(p.Context())
	return retId, p.Context().SendRequest(p, 3, retId, Pointer)
}

// Dispatch dispatches event for object ZwpGesturesV1
func (p *ZwpGesturesV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// ZwpGestureSwipeV1 a swipe gesture object
type ZwpGestureSwipeV1 struct {
	BaseProxy
	mu                              sync.RWMutex
	privateZwpGestureSwipeV1Begins  map[ZwpGestureSwipeV1BeginHandler]struct{}
	privateZwpGestureSwipeV1Updates map[ZwpGestureSwipeV1UpdateHandler]struct{}
	privateZwpGestureSwipeV1Ends    map[ZwpGestureSwipeV1EndHandler]struct{}
}

// initZwpGestureSwipeV1 initializes the ZwpGestureSwipeV1 object's handler maps
func (ret *ZwpGestureSwipeV1) initZwpGestureSwipeV1() {
	ret.privateZwpGestureSwipeV1Begins = make(map[ZwpGestureSwipeV1BeginHandler]struct{})
	ret.privateZwpGestureSwipeV1Updates = make(map[ZwpGestureSwipeV1UpdateHandler]struct{})
	ret.privateZwpGestureSwipeV1Ends = make(map[ZwpGestureSwipeV1EndHandler]struct{})
}

// NewZwpGestureSwipeV1 is a constructor for the ZwpGestureSwipeV1 object
func NewZwpGestureSwipeV1(ctx *Context) *ZwpGestureSwipeV1 {
	ret := new(ZwpGestureSwipeV1)
	ret.initZwpGestureSwipeV1()
	ctx.Register(ret)
	return ret
}

// Destroy destroy the pointer swipe gesture object
func (p *ZwpGestureSwipeV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// Dispatch dispatches event for object ZwpGestureSwipeV1
func (p *ZwpGestureSwipeV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwpGestureSwipeV1Begins) > 0 {
			ev := ZwpGestureSwipeV1BeginEvent{}
			ev.Serial = event.Uint32()
			ev.Time = event.Uint32()
			ev.Surface = SafeCast[*Surface](event.Proxy(p.Context()))
			ev.Fingers = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpGestureSwipeV1Begins {
				h.HandleZwpGestureSwipeV1Begin(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateZwpGestureSwipeV1Updates) > 0 {
			ev := ZwpGestureSwipeV1UpdateEvent{}
			ev.Time = event.Uint32()
			ev.Dx = event.Float32()
			ev.Dy = event.Float32()
			p.mu.RLock()
			for h := range p.privateZwpGestureSwipeV1Updates {
				h.HandleZwpGestureSwipeV1Update(ev)
			}
			p.mu.RUnlock()
		}
	case 2:
		if len(p.privateZwpGestureSwipeV1Ends) > 0 {
			ev := ZwpGestureSwipeV1EndEvent{}
			ev.Serial = event.Uint32()
			ev.Time = event.Uint32()
			ev.Cancelled = event.Int32()
			p.mu.RLock()
			for h := range p.privateZwpGestureSwipeV1Ends {
				h.HandleZwpGestureSwipeV1End(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ZwpGestureSwipeV1BeginEvent is the multi-finger swipe begin
type ZwpGestureSwipeV1BeginEvent struct {
	// Serial is the
	Serial uint32
	// Time is the timestamp with millisecond granularity
	Time uint32
	// Surface is the
	Surface *Surface
	// Fingers is the number of fingers
	Fingers uint32
}

// ZwpGestureSwipeV1UpdateEvent is the multi-finger swipe motion
type ZwpGestureSwipeV1UpdateEvent struct {
	// Time is the timestamp with millisecond granularity
	Time uint32
	// Dx is the delta x coordinate in surface coordinate space
	Dx float32
	// Dy is the delta y coordinate in surface coordinate space
	Dy float32
}

// ZwpGestureSwipeV1EndEvent is the multi-finger swipe end
type ZwpGestureSwipeV1EndEvent struct {
	// Serial is the
	Serial uint32
	// Time is the timestamp with millisecond granularity
	Time uint32
	// Cancelled is the 1 if the gesture was cancelled, 0 otherwise
	Cancelled int32
}

// ZwpGestureSwipeV1BeginHandler is the handler interface for ZwpGestureSwipeV1BeginEvent
type ZwpGestureSwipeV1BeginHandler interface {
	HandleZwpGestureSwipeV1Begin(ZwpGestureSwipeV1BeginEvent)
}

// AddBeginHandler adds the Begin handler
func (p *ZwpGestureSwipeV1) AddBeginHandler(h ZwpGestureSwipeV1BeginHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpGestureSwipeV1Begins[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveBeginHandler removes the Begin handler
func (p *ZwpGestureSwipeV1) RemoveBeginHandler(h ZwpGestureSwipeV1BeginHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpGestureSwipeV1Begins, h)
}

// ZwpGestureSwipeV1UpdateHandler is the handler interface for ZwpGestureSwipeV1UpdateEvent
type ZwpGestureSwipeV1UpdateHandler interface {
	HandleZwpGestureSwipeV1Update(ZwpGestureSwipeV1UpdateEvent)
}

// AddUpdateHandler adds the Update handler
func (p *ZwpGestureSwipeV1) AddUpdateHandler(h ZwpGestureSwipeV1UpdateHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpGestureSwipeV1Updates[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveUpdateHandler removes the Update handler
func (p *ZwpGestureSwipeV1) RemoveUpdateHandler(h ZwpGestureSwipeV1UpdateHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpGestureSwipeV1Updates, h)
}

// ZwpGestureSwipeV1EndHandler is the handler interface for ZwpGestureSwipeV1EndEvent
type ZwpGestureSwipeV1EndHandler interface {
	HandleZwpGestureSwipeV1End(ZwpGestureSwipeV1EndEvent)
}

// AddEndHandler adds the End handler
func (p *ZwpGestureSwipeV1) AddEndHandler(h ZwpGestureSwipeV1EndHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpGestureSwipeV1Ends[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveEndHandler removes the End handler
func (p *ZwpGestureSwipeV1) RemoveEndHandler(h ZwpGestureSwipeV1EndHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpGestureSwipeV1Ends, h)
}

// ZwpGesturePinchV1 a pinch gesture object
type ZwpGesturePinchV1 struct {
	BaseProxy
	mu                              sync.RWMutex
	privateZwpGesturePinchV1Begins  map[ZwpGesturePinchV1BeginHandler]struct{}
	privateZwpGesturePinchV1Updates map[ZwpGesturePinchV1UpdateHandler]struct{}
	privateZwpGesturePinchV1Ends    map[ZwpGesturePinchV1EndHandler]struct{}
}

// initZwpGesturePinchV1 initializes the ZwpGesturePinchV1 object's handler maps
func (ret *ZwpGesturePinchV1) initZwpGesturePinchV1() {
	ret.privateZwpGesturePinchV1Begins = make(map[ZwpGesturePinchV1BeginHandler]struct{})
	ret.privateZwpGesturePinchV1Updates = make(map[ZwpGesturePinchV1UpdateHandler]struct{})
	ret.privateZwpGesturePinchV1Ends = make(map[ZwpGesturePinchV1EndHandler]struct{})
}

// NewZwpGesturePinchV1 is a constructor for the ZwpGesturePinchV1 object
func NewZwpGesturePinchV1(ctx *Context) *ZwpGesturePinchV1 {
	ret := new(ZwpGesturePinchV1)
	ret.initZwpGesturePinchV1()
	ctx.Register(ret)
	return ret
}

// Destroy destroy the pinch gesture object
func (p *ZwpGesturePinchV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// Dispatch dispatches event for object ZwpGesturePinchV1
func (p *ZwpGesturePinchV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwpGesturePinchV1Begins) > 0 {
			ev := ZwpGesturePinchV1BeginEvent{}
			ev.Serial = event.Uint32()
			ev.Time = event.Uint32()
			ev.Surface = SafeCast[*Surface](event.Proxy(p.Context()))
			ev.Fingers = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpGesturePinchV1Begins {
				h.HandleZwpGesturePinchV1Begin(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateZwpGesturePinchV1Updates) > 0 {
			ev := ZwpGesturePinchV1UpdateEvent{}
			ev.Time = event.Uint32()
			ev.Dx = event.Float32()
			ev.Dy = event.Float32()
			ev.Scale = event.Float32()
			ev.Rotation = event.Float32()
			p.mu.RLock()
			for h := range p.privateZwpGesturePinchV1Updates {
				h.HandleZwpGesturePinchV1Update(ev)
			}
			p.mu.RUnlock()
		}
	case 2:
		if len(p.privateZwpGesturePinchV1Ends) > 0 {
			ev := ZwpGesturePinchV1EndEvent{}
			ev.Serial = event.Uint32()
			ev.Time = event.Uint32()
			ev.Cancelled = event.Int32()
			p.mu.RLock()
			for h := range p.privateZwpGesturePinchV1Ends {
				h.HandleZwpGesturePinchV1End(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ZwpGesturePinchV1BeginEvent is the multi-finger pinch begin
type ZwpGesturePinchV1BeginEvent struct {
	// Serial is the
	Serial uint32
	// Time is the timestamp with millisecond granularity
	Time uint32
	// Surface is the
	Surface *Surface
	// Fingers is the number of fingers
	Fingers uint32
}

// ZwpGesturePinchV1UpdateEvent is the multi-finger pinch motion
type ZwpGesturePinchV1UpdateEvent struct {
	// Time is the timestamp with millisecond granularity
	Time uint32
	// Dx is the delta x coordinate in surface coordinate space
	Dx float32
	// Dy is the delta y coordinate in surface coordinate space
	Dy float32
	// Scale is the scale relative to the initial finger position
	Scale float32
	// Rotation is the angle in degrees cw relative to the previous event
	Rotation float32
}

// ZwpGesturePinchV1EndEvent is the multi-finger pinch end
type ZwpGesturePinchV1EndEvent struct {
	// Serial is the
	Serial uint32
	// Time is the timestamp with millisecond granularity
	Time uint32
	// Cancelled is the 1 if the gesture was cancelled, 0 otherwise
	Cancelled int32
}

// ZwpGesturePinchV1BeginHandler is the handler interface for ZwpGesturePinchV1BeginEvent
type ZwpGesturePinchV1BeginHandler interface {
	HandleZwpGesturePinchV1Begin(ZwpGesturePinchV1BeginEvent)
}

// AddBeginHandler adds the Begin handler
func (p *ZwpGesturePinchV1) AddBeginHandler(h ZwpGesturePinchV1BeginHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpGesturePinchV1Begins[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveBeginHandler removes the Begin handler
func (p *ZwpGesturePinchV1) RemoveBeginHandler(h ZwpGesturePinchV1BeginHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpGesturePinchV1Begins, h)
}

// ZwpGesturePinchV1UpdateHandler is the handler interface for ZwpGesturePinchV1UpdateEvent
type ZwpGesturePinchV1UpdateHandler interface {
	HandleZwpGesturePinchV1Update(ZwpGesturePinchV1UpdateEvent)
}

// AddUpdateHandler adds the Update handler
func (p *ZwpGesturePinchV1) AddUpdateHandler(h ZwpGesturePinchV1UpdateHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpGesturePinchV1Updates[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveUpdateHandler removes the Update handler
func (p *ZwpGesturePinchV1) RemoveUpdateHandler(h ZwpGesturePinchV1UpdateHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpGesturePinchV1Updates, h)
}

// ZwpGesturePinchV1EndHandler is the handler interface for ZwpGesturePinchV1EndEvent
type ZwpGesturePinchV1EndHandler interface {
	HandleZwpGesturePinchV1End(ZwpGesturePinchV1EndEvent)
}

// AddEndHandler adds the End handler
func (p *ZwpGesturePinchV1) AddEndHandler(h ZwpGesturePinchV1EndHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpGesturePinchV1Ends[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveEndHandler removes the End handler
func (p *ZwpGesturePinchV1) RemoveEndHandler(h ZwpGesturePinchV1EndHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpGesturePinchV1Ends, h)
}

// ZwpGestureHoldV1 a hold gesture object
type ZwpGestureHoldV1 struct {
	BaseProxy
	mu                            sync.RWMutex
	privateZwpGestureHoldV1Begins map[ZwpGestureHoldV1BeginHandler]struct{}
	privateZwpGestureHoldV1Ends   map[ZwpGestureHoldV1EndHandler]struct{}
}

// initZwpGestureHoldV1 initializes the ZwpGestureHoldV1 object's handler maps
func (ret *ZwpGestureHoldV1) initZwpGestureHoldV1() {
	ret.privateZwpGestureHoldV1Begins = make(map[ZwpGestureHoldV1BeginHandler]struct{})
	ret.privateZwpGestureHoldV1Ends = make(map[ZwpGestureHoldV1EndHandler]struct{})
}

// NewZwpGestureHoldV1 is a constructor for the ZwpGestureHoldV1 object
func NewZwpGestureHoldV1(ctx *Context) *ZwpGestureHoldV1 {
	ret := new(ZwpGestureHoldV1)
	ret.initZwpGestureHoldV1()
	ctx.Register(ret)
	return ret
}

// Destroy destroy the hold gesture object
func (p *ZwpGestureHoldV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// Dispatch dispatches event for object ZwpGestureHoldV1
func (p *ZwpGestureHoldV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwpGestureHoldV1Begins) > 0 {
			ev := ZwpGestureHoldV1BeginEvent{}
			ev.Serial = event.Uint32()
			ev.Time = event.Uint32()
			ev.Surface = SafeCast[*Surface](event.Proxy(p.Context()))
			ev.Fingers = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpGestureHoldV1Begins {
				h.HandleZwpGestureHoldV1Begin(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateZwpGestureHoldV1Ends) > 0 {
			ev := ZwpGestureHoldV1EndEvent{}
			ev.Serial = event.Uint32()
			ev.Time = event.Uint32()
			ev.Cancelled = event.Int32()
			p.mu.RLock()
			for h := range p.privateZwpGestureHoldV1Ends {
				h.HandleZwpGestureHoldV1End(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ZwpGestureHoldV1BeginEvent is the multi-finger hold begin
type ZwpGestureHoldV1BeginEvent struct {
	// Serial is the
	Serial uint32
	// Time is the timestamp with millisecond granularity
	Time uint32
	// Surface is the
	Surface *Surface
	// Fingers is the number of fingers
	Fingers uint32
}

// ZwpGestureHoldV1EndEvent is the multi-finger hold end
type ZwpGestureHoldV1EndEvent struct {
	// Serial is the
	Serial uint32
	// Time is the timestamp with millisecond granularity
	Time uint32
	// Cancelled is the 1 if the gesture was cancelled, 0 otherwise
	Cancelled int32
}

// ZwpGestureHoldV1BeginHandler is the handler interface for ZwpGestureHoldV1BeginEvent
type ZwpGestureHoldV1BeginHandler interface {
	HandleZwpGestureHoldV1Begin(ZwpGestureHoldV1BeginEvent)
}

// AddBeginHandler adds the Begin handler
func (p *ZwpGestureHoldV1) AddBeginHandler(h ZwpGestureHoldV1BeginHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpGestureHoldV1Begins[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveBeginHandler removes the Begin handler
func (p *ZwpGestureHoldV1) RemoveBeginHandler(h ZwpGestureHoldV1BeginHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpGestureHoldV1Begins, h)
}

// ZwpGestureHoldV1EndHandler is the handler interface for ZwpGestureHoldV1EndEvent
type ZwpGestureHoldV1EndHandler interface {
	HandleZwpGestureHoldV1End(ZwpGestureHoldV1EndEvent)
}

// AddEndHandler adds the End handler
func (p *ZwpGestureHoldV1) AddEndHandler(h ZwpGestureHoldV1EndHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpGestureHoldV1Ends[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveEndHandler removes the End handler
func (p *ZwpGestureHoldV1) RemoveEndHandler(h ZwpGestureHoldV1EndHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpGestureHoldV1Ends, h)
}
