// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: pointer-constraints-unstable-v1.xml
// Do not edit

// Package wlr implements the pointer_constraints_unstable_v1 protocol
package wlr

import (
	"sync"
)

// ZwpPointerConstraintsV1ErrorAlreadyConstrained means pointer constraint already requested on that surface
const ZwpPointerConstraintsV1ErrorAlreadyConstrained = 1

// ZwpPointerConstraintsV1LifetimeOneshot
const ZwpPointerConstraintsV1LifetimeOneshot = 1

// ZwpPointerConstraintsV1LifetimePersistent
const ZwpPointerConstraintsV1LifetimePersistent = 2

// ZwpPointerConstraintsV1 constrain the movement of a pointer
type ZwpPointerConstraintsV1 struct {
	BaseProxy
}

// NewZwpPointerConstraintsV1 is a constructor for the ZwpPointerConstraintsV1 object
func NewZwpPointerConstraintsV1(ctx *Context) *ZwpPointerConstraintsV1 {
	ret := new(ZwpPointerConstraintsV1)
	ctx.Register(ret)
	return ret
}

// Destroy destroy the pointer constraints manager object
func (p *ZwpPointerConstraintsV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// LockPointer lock pointer to a position
func (p *ZwpPointerConstraintsV1) LockPointer(Surface *Surface, Pointer *Pointer, Region *Region, Lifetime uint32) (*ZwpLockedPointerV1, error) {
	retId := NewZwpLockedPointerV1(p.Context())
	return retId, p.Context().SendRequest(p, 1, retId, Surface, Pointer, Region, Lifetime)
}

// ConfinePointer confine pointer to a region
func (p *ZwpPointerConstraintsV1) ConfinePointer(Surface *Surface, Pointer *Pointer, Region *Region, Lifetime uint32) (*ZwpConfinedPointerV1, error) {
	retId := NewZwpConfinedPointerV1(p.Context())
	return retId, p.Context().SendRequest(p, 2, retId, Surface, Pointer, Region, Lifetime)
}

// Dispatch dispatches event for object ZwpPointerConstraintsV1
func (p *ZwpPointerConstraintsV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// ZwpLockedPointerV1 receive relative pointer motion events
type ZwpLockedPointerV1 struct {
	BaseProxy
	mu                                 sync.RWMutex
	privateZwpLockedPointerV1Lockeds   map[ZwpLockedPointerV1LockedHandler]struct{}
	privateZwpLockedPointerV1Unlockeds map[ZwpLockedPointerV1UnlockedHandler]struct{}
}

// initZwpLockedPointerV1 initializes the ZwpLockedPointerV1 object's handler maps
func (ret *ZwpLockedPointerV1) initZwpLockedPointerV1() {
	ret.privateZwpLockedPointerV1Lockeds = make(map[ZwpLockedPointerV1LockedHandler]struct{})
	ret.privateZwpLockedPointerV1Unlockeds = make(map[ZwpLockedPointerV1UnlockedHandler]struct{})
}

// NewZwpLockedPointerV1 is a constructor for the ZwpLockedPointerV1 object
func NewZwpLockedPointerV1(ctx *Context) *ZwpLockedPointerV1 {
	ret := new(ZwpLockedPointerV1)
	ret.initZwpLockedPointerV1()
	ctx.Register(ret)
	return ret
}

// Destroy destroy the locked pointer object
func (p *ZwpLockedPointerV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// SetCursorPositionHint set the pointer cursor position hint
func (p *ZwpLockedPointerV1) SetCursorPositionHint(SurfaceX float32, SurfaceY float32) error {

	return p.Context().SendRequest(p, 1, SurfaceX, SurfaceY)
}

// SetRegion set a new lock region
func (p *ZwpLockedPointerV1) SetRegion(Region *Region) error {

	return p.Context().SendRequest(p, 2, Region)
}

// Dispatch dispatches event for object ZwpLockedPointerV1
func (p *ZwpLockedPointerV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwpLockedPointerV1Lockeds) > 0 {
			ev := ZwpLockedPointerV1LockedEvent{}
			p.mu.RLock()
			for h := range p.privateZwpLockedPointerV1Lockeds {
				h.HandleZwpLockedPointerV1Locked(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateZwpLockedPointerV1Unlockeds) > 0 {
			ev := ZwpLockedPointerV1UnlockedEvent{}
			p.mu.RLock()
			for h := range p.privateZwpLockedPointerV1Unlockeds {
				h.HandleZwpLockedPointerV1Unlocked(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ZwpLockedPointerV1LockedEvent is the lock activation event
type ZwpLockedPointerV1LockedEvent struct {
}

// ZwpLockedPointerV1UnlockedEvent is the lock deactivation event
type ZwpLockedPointerV1UnlockedEvent struct {
}

// ZwpLockedPointerV1LockedHandler is the handler interface for ZwpLockedPointerV1LockedEvent
type ZwpLockedPointerV1LockedHandler interface {
	HandleZwpLockedPointerV1Locked(ZwpLockedPointerV1LockedEvent)
}

// AddLockedHandler adds the Locked handler
func (p *ZwpLockedPointerV1) AddLockedHandler(h ZwpLockedPointerV1LockedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpLockedPointerV1Lockeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveLockedHandler removes the Locked handler
func (p *ZwpLockedPointerV1) RemoveLockedHandler(h ZwpLockedPointerV1LockedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpLockedPointerV1Lockeds, h)
}

// ZwpLockedPointerV1UnlockedHandler is the handler interface for ZwpLockedPointerV1UnlockedEvent
type ZwpLockedPointerV1UnlockedHandler interface {
	HandleZwpLockedPointerV1Unlocked(ZwpLockedPointerV1UnlockedEvent)
}

// AddUnlockedHandler adds the Unlocked handler
func (p *ZwpLockedPointerV1) AddUnlockedHandler(h ZwpLockedPointerV1UnlockedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpLockedPointerV1Unlockeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveUnlockedHandler removes the Unlocked handler
func (p *ZwpLockedPointerV1) RemoveUnlockedHandler(h ZwpLockedPointerV1UnlockedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpLockedPointerV1Unlockeds, h)
}

// ZwpConfinedPointerV1 confined pointer object
type ZwpConfinedPointerV1 struct {
	BaseProxy
	mu                                     sync.RWMutex
	privateZwpConfinedPointerV1Confineds   map[ZwpConfinedPointerV1ConfinedHandler]struct{}
	privateZwpConfinedPointerV1Unconfineds map[ZwpConfinedPointerV1UnconfinedHandler]struct{}
}

// initZwpConfinedPointerV1 initializes the ZwpConfinedPointerV1 object's handler maps
func (ret *ZwpConfinedPointerV1) initZwpConfinedPointerV1() {
	ret.privateZwpConfinedPointerV1Confineds = make(map[ZwpConfinedPointerV1ConfinedHandler]struct{})
	ret.privateZwpConfinedPointerV1Unconfineds = make(map[ZwpConfinedPointerV1UnconfinedHandler]struct{})
}

// NewZwpConfinedPointerV1 is a constructor for the ZwpConfinedPointerV1 object
func NewZwpConfinedPointerV1(ctx *Context) *ZwpConfinedPointerV1 {
	ret := new(ZwpConfinedPointerV1)
	ret.initZwpConfinedPointerV1()
	ctx.Register(ret)
	return ret
}

// Destroy destroy the confined pointer object
func (p *ZwpConfinedPointerV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// SetRegion set a new confine region
func (p *ZwpConfinedPointerV1) SetRegion(Region *Region) error {

	return p.Context().SendRequest(p, 1, Region)
}

// Dispatch dispatches event for object ZwpConfinedPointerV1
func (p *ZwpConfinedPointerV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwpConfinedPointerV1Confineds) > 0 {
			ev := ZwpConfinedPointerV1ConfinedEvent{}
			p.mu.RLock()
			for h := range p.privateZwpConfinedPointerV1Confineds {
				h.HandleZwpConfinedPointerV1Confined(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateZwpConfinedPointerV1Unconfineds) > 0 {
			ev := ZwpConfinedPointerV1UnconfinedEvent{}
			p.mu.RLock()
			for h := range p.privateZwpConfinedPointerV1Unconfineds {
				h.HandleZwpConfinedPointerV1Unconfined(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ZwpConfinedPointerV1ConfinedEvent is the pointer confined
type ZwpConfinedPointerV1ConfinedEvent struct {
}

// ZwpConfinedPointerV1UnconfinedEvent is the pointer unconfined
type ZwpConfinedPointerV1UnconfinedEvent struct {
}

// ZwpConfinedPointerV1ConfinedHandler is the handler interface for ZwpConfinedPointerV1ConfinedEvent
type ZwpConfinedPointerV1ConfinedHandler interface {
	HandleZwpConfinedPointerV1Confined(ZwpConfinedPointerV1ConfinedEvent)
}

// AddConfinedHandler adds the Confined handler
func (p *ZwpConfinedPointerV1) AddConfinedHandler(h ZwpConfinedPointerV1ConfinedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpConfinedPointerV1Confineds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveConfinedHandler removes the Confined handler
func (p *ZwpConfinedPointerV1) RemoveConfinedHandler(h ZwpConfinedPointerV1ConfinedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpConfinedPointerV1Confineds, h)
}

// ZwpConfinedPointerV1UnconfinedHandler is the handler interface for ZwpConfinedPointerV1UnconfinedEvent
type ZwpConfinedPointerV1UnconfinedHandler interface {
	HandleZwpConfinedPointerV1Unconfined(ZwpConfinedPointerV1UnconfinedEvent)
}

// AddUnconfinedHandler adds the Unconfined handler
func (p *ZwpConfinedPointerV1) AddUnconfinedHandler(h ZwpConfinedPointerV1UnconfinedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpConfinedPointerV1Unconfineds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveUnconfinedHandler removes the Unconfined handler
func (p *ZwpConfinedPointerV1) RemoveUnconfinedHandler(h ZwpConfinedPointerV1UnconfinedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpConfinedPointerV1Unconfineds, h)
}
