// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: primary-selection-unstable-v1.xml
// Do not edit

// Package wlr implements the wp_primary_selection_unstable_v1 protocol
package wlr

import (
	"sync"
)

// ZwpPrimarySelectionDeviceManagerV1 X primary selection emulation
type ZwpPrimarySelectionDeviceManagerV1 struct {
	BaseProxy
}

// NewZwpPrimarySelectionDeviceManagerV1 is a constructor for the ZwpPrimarySelectionDeviceManagerV1 object
func NewZwpPrimarySelectionDeviceManagerV1(ctx *Context) *ZwpPrimarySelectionDeviceManagerV1 {
	ret := new(ZwpPrimarySelectionDeviceManagerV1)
	ctx.Register(ret)
	return ret
}

// CreateSource create a new primary selection source
func (p *ZwpPrimarySelectionDeviceManagerV1) CreateSource() (*ZwpPrimarySelectionSourceV1, error) {
	retId := NewZwpPrimarySelectionSourceV1(p.Context())
	return retId, p.Context().SendRequest(p, 0, retId)
}

// GetDevice create a new primary selection device
func (p *ZwpPrimarySelectionDeviceManagerV1) GetDevice(Seat *Seat) (*ZwpPrimarySelectionDeviceV1, error) {
	retId := NewZwpPrimarySelectionDeviceV1(p.Context())
	return retId, p.Context().SendRequest(p, 1, retId, Seat)
}

// Destroy destroy the primary selection device manager
func (p *ZwpPrimarySelectionDeviceManagerV1) Destroy() error {

	return p.Context().SendRequest(p, 2)
}

// Dispatch dispatches event for object ZwpPrimarySelectionDeviceManagerV1
func (p *ZwpPrimarySelectionDeviceManagerV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// ZwpPrimarySelectionDeviceV1
type ZwpPrimarySelectionDeviceV1 struct {
	BaseProxy
	mu                                           sync.RWMutex
	privateZwpPrimarySelectionDeviceV1DataOffers map[ZwpPrimarySelectionDeviceV1DataOfferHandler]struct{}
	privateZwpPrimarySelectionDeviceV1Selections map[ZwpPrimarySelectionDeviceV1SelectionHandler]struct{}
}

// initZwpPrimarySelectionDeviceV1 initializes the ZwpPrimarySelectionDeviceV1 object's handler maps
func (ret *ZwpPrimarySelectionDeviceV1) initZwpPrimarySelectionDeviceV1() {
	ret.privateZwpPrimarySelectionDeviceV1DataOffers = make(map[ZwpPrimarySelectionDeviceV1DataOfferHandler]struct{})
	ret.privateZwpPrimarySelectionDeviceV1Selections = make(map[ZwpPrimarySelectionDeviceV1SelectionHandler]struct{})
}

// NewZwpPrimarySelectionDeviceV1 is a constructor for the ZwpPrimarySelectionDeviceV1 object
func NewZwpPrimarySelectionDeviceV1(ctx *Context) *ZwpPrimarySelectionDeviceV1 {
	ret := new(ZwpPrimarySelectionDeviceV1)
	ret.initZwpPrimarySelectionDeviceV1()
	ctx.Register(ret)
	return ret
}

// SetSelection set the primary selection
func (p *ZwpPrimarySelectionDeviceV1) SetSelection(Source *ZwpPrimarySelectionSourceV1, Serial uint32) error {

	return p.Context().SendRequest(p, 0, Source, Serial)
}

// Destroy destroy the primary selection device
func (p *ZwpPrimarySelectionDeviceV1) Destroy() error {

	return p.Context().SendRequest(p, 1)
}

// Dispatch dispatches event for object ZwpPrimarySelectionDeviceV1
func (p *ZwpPrimarySelectionDeviceV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwpPrimarySelectionDeviceV1DataOffers) > 0 {
			ev := ZwpPrimarySelectionDeviceV1DataOfferEvent{}
			ev.Offer = func() *ZwpPrimarySelectionOfferV1 {
				ret := new(ZwpPrimarySelectionOfferV1)
				ret.initZwpPrimarySelectionOfferV1()
				return event.NewId(ret, p.Context()).(*ZwpPrimarySelectionOfferV1)
			}()
			p.mu.RLock()
			for h := range p.privateZwpPrimarySelectionDeviceV1DataOffers {
				h.HandleZwpPrimarySelectionDeviceV1DataOffer(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateZwpPrimarySelectionDeviceV1Selections) > 0 {
			ev := ZwpPrimarySelectionDeviceV1SelectionEvent{}
			ev.Id = SafeCast[*ZwpPrimarySelectionOfferV1](event.Proxy(p.Context()))
			p.mu.RLock()
			for h := range p.privateZwpPrimarySelectionDeviceV1Selections {
				h.HandleZwpPrimarySelectionDeviceV1Selection(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ZwpPrimarySelectionDeviceV1DataOfferEvent is the introduce a new wp_primary_selection_offer
type ZwpPrimarySelectionDeviceV1DataOfferEvent struct {
	// Offer is the
	Offer *ZwpPrimarySelectionOfferV1
}

// ZwpPrimarySelectionDeviceV1SelectionEvent is the advertise a new primary selection
type ZwpPrimarySelectionDeviceV1SelectionEvent struct {
	// Id is the
	Id *ZwpPrimarySelectionOfferV1
}

// ZwpPrimarySelectionDeviceV1DataOfferHandler is the handler interface for ZwpPrimarySelectionDeviceV1DataOfferEvent
type ZwpPrimarySelectionDeviceV1DataOfferHandler interface {
	HandleZwpPrimarySelectionDeviceV1DataOffer(ZwpPrimarySelectionDeviceV1DataOfferEvent)
}

// AddDataOfferHandler adds the DataOffer handler
func (p *ZwpPrimarySelectionDeviceV1) AddDataOfferHandler(h ZwpPrimarySelectionDeviceV1DataOfferHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpPrimarySelectionDeviceV1DataOffers[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveDataOfferHandler removes the DataOffer handler
func (p *ZwpPrimarySelectionDeviceV1) RemoveDataOfferHandler(h ZwpPrimarySelectionDeviceV1DataOfferHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpPrimarySelectionDeviceV1DataOffers, h)
}

// ZwpPrimarySelectionDeviceV1SelectionHandler is the handler interface for ZwpPrimarySelectionDeviceV1SelectionEvent
type ZwpPrimarySelectionDeviceV1SelectionHandler interface {
	HandleZwpPrimarySelectionDeviceV1Selection(ZwpPrimarySelectionDeviceV1SelectionEvent)
}

// AddSelectionHandler adds the Selection handler
func (p *ZwpPrimarySelectionDeviceV1) AddSelectionHandler(h ZwpPrimarySelectionDeviceV1SelectionHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpPrimarySelectionDeviceV1Selections[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveSelectionHandler removes the Selection handler
func (p *ZwpPrimarySelectionDeviceV1) RemoveSelectionHandler(h ZwpPrimarySelectionDeviceV1SelectionHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpPrimarySelectionDeviceV1Selections, h)
}

// ZwpPrimarySelectionOfferV1 offer to transfer primary selection contents
type ZwpPrimarySelectionOfferV1 struct {
	BaseProxy
	mu                                      sync.RWMutex
	privateZwpPrimarySelectionOfferV1Offers map[ZwpPrimarySelectionOfferV1OfferHandler]struct{}
}

// initZwpPrimarySelectionOfferV1 initializes the ZwpPrimarySelectionOfferV1 object's handler maps
func (ret *ZwpPrimarySelectionOfferV1) initZwpPrimarySelectionOfferV1() {
	ret.privateZwpPrimarySelectionOfferV1Offers = make(map[ZwpPrimarySelectionOfferV1OfferHandler]struct{})
}

// NewZwpPrimarySelectionOfferV1 is a constructor for the ZwpPrimarySelectionOfferV1 object
func NewZwpPrimarySelectionOfferV1(ctx *Context) *ZwpPrimarySelectionOfferV1 {
	ret := new(ZwpPrimarySelectionOfferV1)
	ret.initZwpPrimarySelectionOfferV1()
	ctx.Register(ret)
	return ret
}

// Receive request that the data is transferred
func (p *ZwpPrimarySelectionOfferV1) Receive(MimeType string, Fd uintptr) error {

	return p.Context().SendRequest(p, 0, MimeType, Fd)
}

// Destroy destroy the primary selection offer
func (p *ZwpPrimarySelectionOfferV1) Destroy() error {

	return p.Context().SendRequest(p, 1)
}

// Dispatch dispatches event for object ZwpPrimarySelectionOfferV1
func (p *ZwpPrimarySelectionOfferV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwpPrimarySelectionOfferV1Offers) > 0 {
			ev := ZwpPrimarySelectionOfferV1OfferEvent{}
			ev.MimeType = event.String()
			p.mu.RLock()
			for h := range p.privateZwpPrimarySelectionOfferV1Offers {
				h.HandleZwpPrimarySelectionOfferV1Offer(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ZwpPrimarySelectionOfferV1OfferEvent is the advertise offered mime type
type ZwpPrimarySelectionOfferV1OfferEvent struct {
	// MimeType is the
	MimeType string
}

// ZwpPrimarySelectionOfferV1OfferHandler is the handler interface for ZwpPrimarySelectionOfferV1OfferEvent
type ZwpPrimarySelectionOfferV1OfferHandler interface {
	HandleZwpPrimarySelectionOfferV1Offer(ZwpPrimarySelectionOfferV1OfferEvent)
}

// AddOfferHandler adds the Offer handler
func (p *ZwpPrimarySelectionOfferV1) AddOfferHandler(h ZwpPrimarySelectionOfferV1OfferHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpPrimarySelectionOfferV1Offers[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveOfferHandler removes the Offer handler
func (p *ZwpPrimarySelectionOfferV1) RemoveOfferHandler(h ZwpPrimarySelectionOfferV1OfferHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpPrimarySelectionOfferV1Offers, h)
}

// ZwpPrimarySelectionSourceV1 offer to replace the contents of the primary selection
type ZwpPrimarySelectionSourceV1 struct {
	BaseProxy
	mu                                           sync.RWMutex
	privateZwpPrimarySelectionSourceV1Sends      map[ZwpPrimarySelectionSourceV1SendHandler]struct{}
	privateZwpPrimarySelectionSourceV1Cancelleds map[ZwpPrimarySelectionSourceV1CancelledHandler]struct{}
}

// initZwpPrimarySelectionSourceV1 initializes the ZwpPrimarySelectionSourceV1 object's handler maps
func (ret *ZwpPrimarySelectionSourceV1) initZwpPrimarySelectionSourceV1() {
	ret.privateZwpPrimarySelectionSourceV1Sends = make(map[ZwpPrimarySelectionSourceV1SendHandler]struct{})
	ret.privateZwpPrimarySelectionSourceV1Cancelleds = make(map[ZwpPrimarySelectionSourceV1CancelledHandler]struct{})
}

// NewZwpPrimarySelectionSourceV1 is a constructor for the ZwpPrimarySelectionSourceV1 object
func NewZwpPrimarySelectionSourceV1(ctx *Context) *ZwpPrimarySelectionSourceV1 {
	ret := new(ZwpPrimarySelectionSourceV1)
	ret.initZwpPrimarySelectionSourceV1()
	ctx.Register(ret)
	return ret
}

// Offer add an offered mime type
func (p *ZwpPrimarySelectionSourceV1) Offer(MimeType string) error {

	return p.Context().SendRequest(p, 0, MimeType)
}

// Destroy destroy the primary selection source
func (p *ZwpPrimarySelectionSourceV1) Destroy() error {

	return p.Context().SendRequest(p, 1)
}

// Dispatch dispatches event for object ZwpPrimarySelectionSourceV1
func (p *ZwpPrimarySelectionSourceV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwpPrimarySelectionSourceV1Sends) > 0 {
			ev := ZwpPrimarySelectionSourceV1SendEvent{}
			ev.MimeType = event.String()
			ev.Fd, ev.FdError = event.FD()
			p.mu.RLock()
			for h := range p.privateZwpPrimarySelectionSourceV1Sends {
				h.HandleZwpPrimarySelectionSourceV1Send(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateZwpPrimarySelectionSourceV1Cancelleds) > 0 {
			ev := ZwpPrimarySelectionSourceV1CancelledEvent{}
			p.mu.RLock()
			for h := range p.privateZwpPrimarySelectionSourceV1Cancelleds {
				h.HandleZwpPrimarySelectionSourceV1Cancelled(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ZwpPrimarySelectionSourceV1SendEvent is the send the primary selection contents
type ZwpPrimarySelectionSourceV1SendEvent struct {
	// MimeType is the
	MimeType string
	// Fd is the
	Fd uintptr
	// FdError is the  (error)
	FdError error
}

// ZwpPrimarySelectionSourceV1CancelledEvent is the request for primary selection contents was canceled
type ZwpPrimarySelectionSourceV1CancelledEvent struct {
}

// ZwpPrimarySelectionSourceV1SendHandler is the handler interface for ZwpPrimarySelectionSourceV1SendEvent
type ZwpPrimarySelectionSourceV1SendHandler interface {
	HandleZwpPrimarySelectionSourceV1Send(ZwpPrimarySelectionSourceV1SendEvent)
}

// AddSendHandler adds the Send handler
func (p *ZwpPrimarySelectionSourceV1) AddSendHandler(h ZwpPrimarySelectionSourceV1SendHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpPrimarySelectionSourceV1Sends[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveSendHandler removes the Send handler
func (p *ZwpPrimarySelectionSourceV1) RemoveSendHandler(h ZwpPrimarySelectionSourceV1SendHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpPrimarySelectionSourceV1Sends, h)
}

// ZwpPrimarySelectionSourceV1CancelledHandler is the handler interface for ZwpPrimarySelectionSourceV1CancelledEvent
type ZwpPrimarySelectionSourceV1CancelledHandler interface {
	HandleZwpPrimarySelectionSourceV1Cancelled(ZwpPrimarySelectionSourceV1CancelledEvent)
}

// AddCancelledHandler adds the Cancelled handler
func (p *ZwpPrimarySelectionSourceV1) AddCancelledHandler(h ZwpPrimarySelectionSourceV1CancelledHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpPrimarySelectionSourceV1Cancelleds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveCancelledHandler removes the Cancelled handler
func (p *ZwpPrimarySelectionSourceV1) RemoveCancelledHandler(h ZwpPrimarySelectionSourceV1CancelledHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpPrimarySelectionSourceV1Cancelleds, h)
}
