// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: relative-pointer-unstable-v1.xml
// Do not edit

// Package wlr implements the relative_pointer_unstable_v1 protocol
package wlr

import (
	"sync"
)

// ZwpRelativePointerManagerV1 get relative pointer objects
type ZwpRelativePointerManagerV1 struct {
	BaseProxy
}

// NewZwpRelativePointerManagerV1 is a constructor for the ZwpRelativePointerManagerV1 object
func NewZwpRelativePointerManagerV1(ctx *Context) *ZwpRelativePointerManagerV1 {
	ret := new(ZwpRelativePointerManagerV1)
	ctx.Register(ret)
	return ret
}

// Destroy destroy the relative pointer manager object
func (p *ZwpRelativePointerManagerV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// GetPointer get a relative pointer object
func (p *ZwpRelativePointerManagerV1) GetPointer(Pointer *Pointer) (*ZwpRelativePointerV1, error) {
	retId := NewZwpRelativePointerV1(p.Context())
	return retId, p.Context().SendRequest(p, 1, retId, Pointer)
}

// Dispatch dispatches event for object ZwpRelativePointerManagerV1
func (p *ZwpRelativePointerManagerV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// ZwpRelativePointerV1 relative pointer object
type ZwpRelativePointerV1 struct {
	BaseProxy
	mu                                 sync.RWMutex
	privateZwpRelativePointerV1Motions map[ZwpRelativePointerV1MotionHandler]struct{}
}

// initZwpRelativePointerV1 initializes the ZwpRelativePointerV1 object's handler maps
func (ret *ZwpRelativePointerV1) initZwpRelativePointerV1() {
	ret.privateZwpRelativePointerV1Motions = make(map[ZwpRelativePointerV1MotionHandler]struct{})
}

// NewZwpRelativePointerV1 is a constructor for the ZwpRelativePointerV1 object
func NewZwpRelativePointerV1(ctx *Context) *ZwpRelativePointerV1 {
	ret := new(ZwpRelativePointerV1)
	ret.initZwpRelativePointerV1()
	ctx.Register(ret)
	return ret
}

// Destroy release the relative pointer object
func (p *ZwpRelativePointerV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// Dispatch dispatches event for object ZwpRelativePointerV1
func (p *ZwpRelativePointerV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwpRelativePointerV1Motions) > 0 {
			ev := ZwpRelativePointerV1MotionEvent{}
			ev.UtimeHi = event.Uint32()
			ev.UtimeLo = event.Uint32()
			ev.Dx = event.Float32()
			ev.Dy = event.Float32()
			ev.DxUnaccel = event.Float32()
			ev.DyUnaccel = event.Float32()
			p.mu.RLock()
			for h := range p.privateZwpRelativePointerV1Motions {
				h.HandleZwpRelativePointerV1Motion(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ZwpRelativePointerV1MotionEvent is the relative pointer motion
type ZwpRelativePointerV1MotionEvent struct {
	// UtimeHi is the high 32 bits of a 64 bit timestamp with microsecond granularity
	UtimeHi uint32
	// UtimeLo is the low 32 bits of a 64 bit timestamp with microsecond granularity
	UtimeLo uint32
	// Dx is the the x component of the motion vector
	Dx float32
	// Dy is the the y component of the motion vector
	Dy float32
	// DxUnaccel is the the x component of the unaccelerated motion vector
	DxUnaccel float32
	// DyUnaccel is the the y component of the unaccelerated motion vector
	DyUnaccel float32
}

// ZwpRelativePointerV1MotionHandler is the handler interface for ZwpRelativePointerV1MotionEvent
type ZwpRelativePointerV1MotionHandler interface {
	HandleZwpRelativePointerV1Motion(ZwpRelativePointerV1MotionEvent)
}

// AddMotionHandler adds the Motion handler
func (p *ZwpRelativePointerV1) AddMotionHandler(h ZwpRelativePointerV1MotionHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpRelativePointerV1Motions[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveMotionHandler removes the Motion handler
func (p *ZwpRelativePointerV1) RemoveMotionHandler(h ZwpRelativePointerV1MotionHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpRelativePointerV1Motions, h)
}
