// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: tablet-unstable-v2.xml
// Do not edit

// Package wlr implements the tablet_unstable_v2 protocol
package wlr

import (
	"sync"
)

// ZwpTabletToolV2TypePen means Pen
const ZwpTabletToolV2TypePen = 0x140

// ZwpTabletToolV2TypeEraser means Eraser
const ZwpTabletToolV2TypeEraser = 0x141

// ZwpTabletToolV2TypeBrush means Brush
const ZwpTabletToolV2TypeBrush = 0x142

// ZwpTabletToolV2TypePencil means Pencil
const ZwpTabletToolV2TypePencil = 0x143

// ZwpTabletToolV2TypeAirbrush means Airbrush
const ZwpTabletToolV2TypeAirbrush = 0x144

// ZwpTabletToolV2TypeFinger means Finger
const ZwpTabletToolV2TypeFinger = 0x145

// ZwpTabletToolV2TypeMouse means Mouse
const ZwpTabletToolV2TypeMouse = 0x146

// ZwpTabletToolV2TypeLens means Lens
const ZwpTabletToolV2TypeLens = 0x147

// ZwpTabletToolV2CapabilityTilt means Tilt axes
const ZwpTabletToolV2CapabilityTilt = 1

// ZwpTabletToolV2CapabilityPressure means Pressure axis
const ZwpTabletToolV2CapabilityPressure = 2

// ZwpTabletToolV2CapabilityDistance means Distance axis
const ZwpTabletToolV2CapabilityDistance = 3

// ZwpTabletToolV2CapabilityRotation means Z-rotation axis
const ZwpTabletToolV2CapabilityRotation = 4

// ZwpTabletToolV2CapabilitySlider means Slider axis
const ZwpTabletToolV2CapabilitySlider = 5

// ZwpTabletToolV2CapabilityWheel means Wheel axis
const ZwpTabletToolV2CapabilityWheel = 6

// ZwpTabletToolV2ButtonStateReleased means button is not pressed
const ZwpTabletToolV2ButtonStateReleased = 0

// ZwpTabletToolV2ButtonStatePressed means button is pressed
const ZwpTabletToolV2ButtonStatePressed = 1

// ZwpTabletToolV2ErrorRole means given wl_surface has another role
const ZwpTabletToolV2ErrorRole = 0

// ZwpTabletPadRingV2SourceFinger means finger
const ZwpTabletPadRingV2SourceFinger = 1

// ZwpTabletPadStripV2SourceFinger means finger
const ZwpTabletPadStripV2SourceFinger = 1

// ZwpTabletPadV2ButtonStateReleased means the button is not pressed
const ZwpTabletPadV2ButtonStateReleased = 0

// ZwpTabletPadV2ButtonStatePressed means the button is pressed
const ZwpTabletPadV2ButtonStatePressed = 1

// ZwpTabletManagerV2 controller object for graphic tablet devices
type ZwpTabletManagerV2 struct {
	BaseProxy
}

// NewZwpTabletManagerV2 is a constructor for the ZwpTabletManagerV2 object
func NewZwpTabletManagerV2(ctx *Context) *ZwpTabletManagerV2 {
	ret := new(ZwpTabletManagerV2)
	ctx.Register(ret)
	return ret
}

// GetSeat get the tablet seat
func (p *ZwpTabletManagerV2) GetSeat(Seat *Seat) (*ZwpTabletSeatV2, error) {
	retSeat := NewZwpTabletSeatV2(p.Context())
	return retSeat, p.Context().SendRequest(p, 0, retSeat, Seat)
}

// Destroy release the memory for the tablet manager object
func (p *ZwpTabletManagerV2) Destroy() error {

	return p.Context().SendRequest(p, 1)
}

// Dispatch dispatches event for object ZwpTabletManagerV2
func (p *ZwpTabletManagerV2) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// ZwpTabletSeatV2 controller object for graphic tablet devices of a seat
type ZwpTabletSeatV2 struct {
	BaseProxy
	mu                               sync.RWMutex
	privateZwpTabletSeatV2Addeds     map[ZwpTabletSeatV2AddedHandler]struct{}
	privateZwpTabletSeatV2ToolAddeds map[ZwpTabletSeatV2ToolAddedHandler]struct{}
	privateZwpTabletSeatV2PadAddeds  map[ZwpTabletSeatV2PadAddedHandler]struct{}
}

// initZwpTabletSeatV2 initializes the ZwpTabletSeatV2 object's handler maps
func (ret *ZwpTabletSeatV2) initZwpTabletSeatV2() {
	ret.privateZwpTabletSeatV2Addeds = make(map[ZwpTabletSeatV2AddedHandler]struct{})
	ret.privateZwpTabletSeatV2ToolAddeds = make(map[ZwpTabletSeatV2ToolAddedHandler]struct{})
	ret.privateZwpTabletSeatV2PadAddeds = make(map[ZwpTabletSeatV2PadAddedHandler]struct{})
}

// NewZwpTabletSeatV2 is a constructor for the ZwpTabletSeatV2 object
func NewZwpTabletSeatV2(ctx *Context) *ZwpTabletSeatV2 {
	ret := new(ZwpTabletSeatV2)
	ret.initZwpTabletSeatV2()
	ctx.Register(ret)
	return ret
}

// Destroy release the memory for the tablet seat object
func (p *ZwpTabletSeatV2) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// Dispatch dispatches event for object ZwpTabletSeatV2
func (p *ZwpTabletSeatV2) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwpTabletSeatV2Addeds) > 0 {
			ev := ZwpTabletSeatV2AddedEvent{}
			ev.Id = func() *ZwpTabletV2 {
				ret := new(ZwpTabletV2)
				ret.initZwpTabletV2()
				return event.NewId(ret, p.Context()).(*ZwpTabletV2)
			}()
			p.mu.RLock()
			for h := range p.privateZwpTabletSeatV2Addeds {
				h.HandleZwpTabletSeatV2Added(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateZwpTabletSeatV2ToolAddeds) > 0 {
			ev := ZwpTabletSeatV2ToolAddedEvent{}
			ev.Id = func() *ZwpTabletToolV2 {
				ret := new(ZwpTabletToolV2)
				ret.initZwpTabletToolV2()
				return event.NewId(ret, p.Context()).(*ZwpTabletToolV2)
			}()
			p.mu.RLock()
			for h := range p.privateZwpTabletSeatV2ToolAddeds {
				h.HandleZwpTabletSeatV2ToolAdded(ev)
			}
			p.mu.RUnlock()
		}
	case 2:
		if len(p.privateZwpTabletSeatV2PadAddeds) > 0 {
			ev := ZwpTabletSeatV2PadAddedEvent{}
			ev.Id = func() *ZwpTabletPadV2 {
				ret := new(ZwpTabletPadV2)
				ret.initZwpTabletPadV2()
				return event.NewId(ret, p.Context()).(*ZwpTabletPadV2)
			}()
			p.mu.RLock()
			for h := range p.privateZwpTabletSeatV2PadAddeds {
				h.HandleZwpTabletSeatV2PadAdded(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ZwpTabletSeatV2AddedEvent is the new device notification
type ZwpTabletSeatV2AddedEvent struct {
	// Id is the the newly added graphics tablet
	Id *ZwpTabletV2
}

// ZwpTabletSeatV2ToolAddedEvent is the a new tool has been used with a tablet
type ZwpTabletSeatV2ToolAddedEvent struct {
	// Id is the the newly added tablet tool
	Id *ZwpTabletToolV2
}

// ZwpTabletSeatV2PadAddedEvent is the new pad notification
type ZwpTabletSeatV2PadAddedEvent struct {
	// Id is the the newly added pad
	Id *ZwpTabletPadV2
}

// ZwpTabletSeatV2AddedHandler is the handler interface for ZwpTabletSeatV2AddedEvent
type ZwpTabletSeatV2AddedHandler interface {
	HandleZwpTabletSeatV2Added(ZwpTabletSeatV2AddedEvent)
}

// AddAddedHandler adds the Added handler
func (p *ZwpTabletSeatV2) AddAddedHandler(h ZwpTabletSeatV2AddedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletSeatV2Addeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveAddedHandler removes the Added handler
func (p *ZwpTabletSeatV2) RemoveAddedHandler(h ZwpTabletSeatV2AddedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletSeatV2Addeds, h)
}

// ZwpTabletSeatV2ToolAddedHandler is the handler interface for ZwpTabletSeatV2ToolAddedEvent
type ZwpTabletSeatV2ToolAddedHandler interface {
	HandleZwpTabletSeatV2ToolAdded(ZwpTabletSeatV2ToolAddedEvent)
}

// AddToolAddedHandler adds the ToolAdded handler
func (p *ZwpTabletSeatV2) AddToolAddedHandler(h ZwpTabletSeatV2ToolAddedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletSeatV2ToolAddeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveToolAddedHandler removes the ToolAdded handler
func (p *ZwpTabletSeatV2) RemoveToolAddedHandler(h ZwpTabletSeatV2ToolAddedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletSeatV2ToolAddeds, h)
}

// ZwpTabletSeatV2PadAddedHandler is the handler interface for ZwpTabletSeatV2PadAddedEvent
type ZwpTabletSeatV2PadAddedHandler interface {
	HandleZwpTabletSeatV2PadAdded(ZwpTabletSeatV2PadAddedEvent)
}

// AddPadAddedHandler adds the PadAdded handler
func (p *ZwpTabletSeatV2) AddPadAddedHandler(h ZwpTabletSeatV2PadAddedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletSeatV2PadAddeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemovePadAddedHandler removes the PadAdded handler
func (p *ZwpTabletSeatV2) RemovePadAddedHandler(h ZwpTabletSeatV2PadAddedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletSeatV2PadAddeds, h)
}

// ZwpTabletToolV2 a physical tablet tool
type ZwpTabletToolV2 struct {
	BaseProxy
	mu                                     sync.RWMutex
	privateZwpTabletToolV2Types            map[ZwpTabletToolV2TypeHandler]struct{}
	privateZwpTabletToolV2HardwareSerials  map[ZwpTabletToolV2HardwareSerialHandler]struct{}
	privateZwpTabletToolV2HardwareIdWacoms map[ZwpTabletToolV2HardwareIdWacomHandler]struct{}
	privateZwpTabletToolV2Capabilitys      map[ZwpTabletToolV2CapabilityHandler]struct{}
	privateZwpTabletToolV2Dones            map[ZwpTabletToolV2DoneHandler]struct{}
	privateZwpTabletToolV2Removeds         map[ZwpTabletToolV2RemovedHandler]struct{}
	privateZwpTabletToolV2ProximityIns     map[ZwpTabletToolV2ProximityInHandler]struct{}
	privateZwpTabletToolV2ProximityOuts    map[ZwpTabletToolV2ProximityOutHandler]struct{}
	privateZwpTabletToolV2Downs            map[ZwpTabletToolV2DownHandler]struct{}
	privateZwpTabletToolV2Ups              map[ZwpTabletToolV2UpHandler]struct{}
	privateZwpTabletToolV2Motions          map[ZwpTabletToolV2MotionHandler]struct{}
	privateZwpTabletToolV2Pressures        map[ZwpTabletToolV2PressureHandler]struct{}
	privateZwpTabletToolV2Distances        map[ZwpTabletToolV2DistanceHandler]struct{}
	privateZwpTabletToolV2Tilts            map[ZwpTabletToolV2TiltHandler]struct{}
	privateZwpTabletToolV2Rotations        map[ZwpTabletToolV2RotationHandler]struct{}
	privateZwpTabletToolV2Sliders          map[ZwpTabletToolV2SliderHandler]struct{}
	privateZwpTabletToolV2Wheels           map[ZwpTabletToolV2WheelHandler]struct{}
	privateZwpTabletToolV2Buttons          map[ZwpTabletToolV2ButtonHandler]struct{}
	privateZwpTabletToolV2Frames           map[ZwpTabletToolV2FrameHandler]struct{}
}

// initZwpTabletToolV2 initializes the ZwpTabletToolV2 object's handler maps
func (ret *ZwpTabletToolV2) initZwpTabletToolV2() {
	ret.privateZwpTabletToolV2Types = make(map[ZwpTabletToolV2TypeHandler]struct{})
	ret.privateZwpTabletToolV2HardwareSerials = make(map[ZwpTabletToolV2HardwareSerialHandler]struct{})
	ret.privateZwpTabletToolV2HardwareIdWacoms = make(map[ZwpTabletToolV2HardwareIdWacomHandler]struct{})
	ret.privateZwpTabletToolV2Capabilitys = make(map[ZwpTabletToolV2CapabilityHandler]struct{})
	ret.privateZwpTabletToolV2Dones = make(map[ZwpTabletToolV2DoneHandler]struct{})
	ret.privateZwpTabletToolV2Removeds = make(map[ZwpTabletToolV2RemovedHandler]struct{})
	ret.privateZwpTabletToolV2ProximityIns = make(map[ZwpTabletToolV2ProximityInHandler]struct{})
	ret.privateZwpTabletToolV2ProximityOuts = make(map[ZwpTabletToolV2ProximityOutHandler]struct{})
	ret.privateZwpTabletToolV2Downs = make(map[ZwpTabletToolV2DownHandler]struct{})
	ret.privateZwpTabletToolV2Ups = make(map[ZwpTabletToolV2UpHandler]struct{})
	ret.privateZwpTabletToolV2Motions = make(map[ZwpTabletToolV2MotionHandler]struct{})
	ret.privateZwpTabletToolV2Pressures = make(map[ZwpTabletToolV2PressureHandler]struct{})
	ret.privateZwpTabletToolV2Distances = make(map[ZwpTabletToolV2DistanceHandler]struct{})
	ret.privateZwpTabletToolV2Tilts = make(map[ZwpTabletToolV2TiltHandler]struct{})
	ret.privateZwpTabletToolV2Rotations = make(map[ZwpTabletToolV2RotationHandler]struct{})
	ret.privateZwpTabletToolV2Sliders = make(map[ZwpTabletToolV2SliderHandler]struct{})
	ret.privateZwpTabletToolV2Wheels = make(map[ZwpTabletToolV2WheelHandler]struct{})
	ret.privateZwpTabletToolV2Buttons = make(map[ZwpTabletToolV2ButtonHandler]struct{})
	ret.privateZwpTabletToolV2Frames = make(map[ZwpTabletToolV2FrameHandler]struct{})
}

// NewZwpTabletToolV2 is a constructor for the ZwpTabletToolV2 object
func NewZwpTabletToolV2(ctx *Context) *ZwpTabletToolV2 {
	ret := new(ZwpTabletToolV2)
	ret.initZwpTabletToolV2()
	ctx.Register(ret)
	return ret
}

// SetCursor set the tablet tool's surface
func (p *ZwpTabletToolV2) SetCursor(Serial uint32, Surface *Surface, HotspotX int32, HotspotY int32) error {

	return p.Context().SendRequest(p, 0, Serial, Surface, HotspotX, HotspotY)
}

// Destroy destroy the tool object
func (p *ZwpTabletToolV2) Destroy() error {

	return p.Context().SendRequest(p, 1)
}

// Dispatch dispatches event for object ZwpTabletToolV2
func (p *ZwpTabletToolV2) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwpTabletToolV2Types) > 0 {
			ev := ZwpTabletToolV2TypeEvent{}
			ev.ToolType = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpTabletToolV2Types {
				h.HandleZwpTabletToolV2Type(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateZwpTabletToolV2HardwareSerials) > 0 {
			ev := ZwpTabletToolV2HardwareSerialEvent{}
			ev.HardwareSerialHi = event.Uint32()
			ev.HardwareSerialLo = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpTabletToolV2HardwareSerials {
				h.HandleZwpTabletToolV2HardwareSerial(ev)
			}
			p.mu.RUnlock()
		}
	case 2:
		if len(p.privateZwpTabletToolV2HardwareIdWacoms) > 0 {
			ev := ZwpTabletToolV2HardwareIdWacomEvent{}
			ev.HardwareIdHi = event.Uint32()
			ev.HardwareIdLo = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpTabletToolV2HardwareIdWacoms {
				h.HandleZwpTabletToolV2HardwareIdWacom(ev)
			}
			p.mu.RUnlock()
		}
	case 3:
		if len(p.privateZwpTabletToolV2Capabilitys) > 0 {
			ev := ZwpTabletToolV2CapabilityEvent{}
			ev.Capability = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpTabletToolV2Capabilitys {
				h.HandleZwpTabletToolV2Capability(ev)
			}
			p.mu.RUnlock()
		}
	case 4:
		if len(p.privateZwpTabletToolV2Dones) > 0 {
			ev := ZwpTabletToolV2DoneEvent{}
			p.mu.RLock()
			for h := range p.privateZwpTabletToolV2Dones {
				h.HandleZwpTabletToolV2Done(ev)
			}
			p.mu.RUnlock()
		}
	case 5:
		if len(p.privateZwpTabletToolV2Removeds) > 0 {
			ev := ZwpTabletToolV2RemovedEvent{}
			p.mu.RLock()
			for h := range p.privateZwpTabletToolV2Removeds {
				h.HandleZwpTabletToolV2Removed(ev)
			}
			p.mu.RUnlock()
		}
	case 6:
		if len(p.privateZwpTabletToolV2ProximityIns) > 0 {
			ev := ZwpTabletToolV2ProximityInEvent{}
			ev.Serial = event.Uint32()
			ev.Tablet = SafeCast[*ZwpTabletV2](event.Proxy(p.Context()))
			ev.Surface = SafeCast[*Surface](event.Proxy(p.Context()))
			p.mu.RLock()
			for h := range p.privateZwpTabletToolV2ProximityIns {
				h.HandleZwpTabletToolV2ProximityIn(ev)
			}
			p.mu.RUnlock()
		}
	case 7:
		if len(p.privateZwpTabletToolV2ProximityOuts) > 0 {
			ev := ZwpTabletToolV2ProximityOutEvent{}
			p.mu.RLock()
			for h := range p.privateZwpTabletToolV2ProximityOuts {
				h.HandleZwpTabletToolV2ProximityOut(ev)
			}
			p.mu.RUnlock()
		}
	case 8:
		if len(p.privateZwpTabletToolV2Downs) > 0 {
			ev := ZwpTabletToolV2DownEvent{}
			ev.Serial = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpTabletToolV2Downs {
				h.HandleZwpTabletToolV2Down(ev)
			}
			p.mu.RUnlock()
		}
	case 9:
		if len(p.privateZwpTabletToolV2Ups) > 0 {
			ev := ZwpTabletToolV2UpEvent{}
			p.mu.RLock()
			for h := range p.privateZwpTabletToolV2Ups {
				h.HandleZwpTabletToolV2Up(ev)
			}
			p.mu.RUnlock()
		}
	case 10:
		if len(p.privateZwpTabletToolV2Motions) > 0 {
			ev := ZwpTabletToolV2MotionEvent{}
			ev.X = event.Float32()
			ev.Y = event.Float32()
			p.mu.RLock()
			for h := range p.privateZwpTabletToolV2Motions {
				h.HandleZwpTabletToolV2Motion(ev)
			}
			p.mu.RUnlock()
		}
	case 11:
		if len(p.privateZwpTabletToolV2Pressures) > 0 {
			ev := ZwpTabletToolV2PressureEvent{}
			ev.Pressure = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpTabletToolV2Pressures {
				h.HandleZwpTabletToolV2Pressure(ev)
			}
			p.mu.RUnlock()
		}
	case 12:
		if len(p.privateZwpTabletToolV2Distances) > 0 {
			ev := ZwpTabletToolV2DistanceEvent{}
			ev.Distance = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpTabletToolV2Distances {
				h.HandleZwpTabletToolV2Distance(ev)
			}
			p.mu.RUnlock()
		}
	case 13:
		if len(p.privateZwpTabletToolV2Tilts) > 0 {
			ev := ZwpTabletToolV2TiltEvent{}
			ev.TiltX = event.Float32()
			ev.TiltY = event.Float32()
			p.mu.RLock()
			for h := range p.privateZwpTabletToolV2Tilts {
				h.HandleZwpTabletToolV2Tilt(ev)
			}
			p.mu.RUnlock()
		}
	case 14:
		if len(p.privateZwpTabletToolV2Rotations) > 0 {
			ev := ZwpTabletToolV2RotationEvent{}
			ev.Degrees = event.Float32()
			p.mu.RLock()
			for h := range p.privateZwpTabletToolV2Rotations {
				h.HandleZwpTabletToolV2Rotation(ev)
			}
			p.mu.RUnlock()
		}
	case 15:
		if len(p.privateZwpTabletToolV2Sliders) > 0 {
			ev := ZwpTabletToolV2SliderEvent{}
			ev.Position = event.Int32()
			p.mu.RLock()
			for h := range p.privateZwpTabletToolV2Sliders {
				h.HandleZwpTabletToolV2Slider(ev)
			}
			p.mu.RUnlock()
		}
	case 16:
		if len(p.privateZwpTabletToolV2Wheels) > 0 {
			ev := ZwpTabletToolV2WheelEvent{}
			ev.Degrees = event.Float32()
			ev.Clicks = event.Int32()
			p.mu.RLock()
			for h := range p.privateZwpTabletToolV2Wheels {
				h.HandleZwpTabletToolV2Wheel(ev)
			}
			p.mu.RUnlock()
		}
	case 17:
		if len(p.privateZwpTabletToolV2Buttons) > 0 {
			ev := ZwpTabletToolV2ButtonEvent{}
			ev.Serial = event.Uint32()
			ev.Button = event.Uint32()
			ev.State = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpTabletToolV2Buttons {
				h.HandleZwpTabletToolV2Button(ev)
			}
			p.mu.RUnlock()
		}
	case 18:
		if len(p.privateZwpTabletToolV2Frames) > 0 {
			ev := ZwpTabletToolV2FrameEvent{}
			ev.Time = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpTabletToolV2Frames {
				h.HandleZwpTabletToolV2Frame(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ZwpTabletToolV2TypeEvent is the tool type
type ZwpTabletToolV2TypeEvent struct {
	// ToolType is the the physical tool type
	ToolType uint32
}

// ZwpTabletToolV2HardwareSerialEvent is the unique hardware serial number of the tool
type ZwpTabletToolV2HardwareSerialEvent struct {
	// HardwareSerialHi is the the unique serial number of the tool, most significant bits
	HardwareSerialHi uint32
	// HardwareSerialLo is the the unique serial number of the tool, least significant bits
	HardwareSerialLo uint32
}

// ZwpTabletToolV2HardwareIdWacomEvent is the hardware id notification in Wacom's format
type ZwpTabletToolV2HardwareIdWacomEvent struct {
	// HardwareIdHi is the the hardware id, most significant bits
	HardwareIdHi uint32
	// HardwareIdLo is the the hardware id, least significant bits
	HardwareIdLo uint32
}

// ZwpTabletToolV2CapabilityEvent is the tool capability notification
type ZwpTabletToolV2CapabilityEvent struct {
	// Capability is the the capability
	Capability uint32
}

// ZwpTabletToolV2DoneEvent is the tool description events sequence complete
type ZwpTabletToolV2DoneEvent struct {
}

// ZwpTabletToolV2RemovedEvent is the tool removed
type ZwpTabletToolV2RemovedEvent struct {
}

// ZwpTabletToolV2ProximityInEvent is the proximity in event
type ZwpTabletToolV2ProximityInEvent struct {
	// Serial is the
	Serial uint32
	// Tablet is the The tablet the tool is in proximity of
	Tablet *ZwpTabletV2
	// Surface is the The current surface the tablet tool is over
	Surface *Surface
}

// ZwpTabletToolV2ProximityOutEvent is the proximity out event
type ZwpTabletToolV2ProximityOutEvent struct {
}

// ZwpTabletToolV2DownEvent is the tablet tool is making contact
type ZwpTabletToolV2DownEvent struct {
	// Serial is the
	Serial uint32
}

// ZwpTabletToolV2UpEvent is the tablet tool is no longer making contact
type ZwpTabletToolV2UpEvent struct {
}

// ZwpTabletToolV2MotionEvent is the motion event
type ZwpTabletToolV2MotionEvent struct {
	// X is the surface-local x coordinate
	X float32
	// Y is the surface-local y coordinate
	Y float32
}

// ZwpTabletToolV2PressureEvent is the pressure change event
type ZwpTabletToolV2PressureEvent struct {
	// Pressure is the The current pressure value
	Pressure uint32
}

// ZwpTabletToolV2DistanceEvent is the distance change event
type ZwpTabletToolV2DistanceEvent struct {
	// Distance is the The current distance value
	Distance uint32
}

// ZwpTabletToolV2TiltEvent is the tilt change event
type ZwpTabletToolV2TiltEvent struct {
	// TiltX is the The current value of the X tilt axis
	TiltX float32
	// TiltY is the The current value of the Y tilt axis
	TiltY float32
}

// ZwpTabletToolV2RotationEvent is the z-rotation change event
type ZwpTabletToolV2RotationEvent struct {
	// Degrees is the The current rotation of the Z axis
	Degrees float32
}

// ZwpTabletToolV2SliderEvent is the Slider position change event
type ZwpTabletToolV2SliderEvent struct {
	// Position is the The current position of slider
	Position int32
}

// ZwpTabletToolV2WheelEvent is the Wheel delta event
type ZwpTabletToolV2WheelEvent struct {
	// Degrees is the The wheel delta in degrees
	Degrees float32
	// Clicks is the The wheel delta in discrete clicks
	Clicks int32
}

// ZwpTabletToolV2ButtonEvent is the button event
type ZwpTabletToolV2ButtonEvent struct {
	// Serial is the
	Serial uint32
	// Button is the The button whose state has changed
	Button uint32
	// State is the Whether the button was pressed or released
	State uint32
}

// ZwpTabletToolV2FrameEvent is the frame event
type ZwpTabletToolV2FrameEvent struct {
	// Time is the The time of the event with millisecond granularity
	Time uint32
}

// ZwpTabletToolV2TypeHandler is the handler interface for ZwpTabletToolV2TypeEvent
type ZwpTabletToolV2TypeHandler interface {
	HandleZwpTabletToolV2Type(ZwpTabletToolV2TypeEvent)
}

// AddTypeHandler adds the Type handler
func (p *ZwpTabletToolV2) AddTypeHandler(h ZwpTabletToolV2TypeHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletToolV2Types[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveTypeHandler removes the Type handler
func (p *ZwpTabletToolV2) RemoveTypeHandler(h ZwpTabletToolV2TypeHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletToolV2Types, h)
}

// ZwpTabletToolV2HardwareSerialHandler is the handler interface for ZwpTabletToolV2HardwareSerialEvent
type ZwpTabletToolV2HardwareSerialHandler interface {
	HandleZwpTabletToolV2HardwareSerial(ZwpTabletToolV2HardwareSerialEvent)
}

// AddHardwareSerialHandler adds the HardwareSerial handler
func (p *ZwpTabletToolV2) AddHardwareSerialHandler(h ZwpTabletToolV2HardwareSerialHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletToolV2HardwareSerials[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveHardwareSerialHandler removes the HardwareSerial handler
func (p *ZwpTabletToolV2) RemoveHardwareSerialHandler(h ZwpTabletToolV2HardwareSerialHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletToolV2HardwareSerials, h)
}

// ZwpTabletToolV2HardwareIdWacomHandler is the handler interface for ZwpTabletToolV2HardwareIdWacomEvent
type ZwpTabletToolV2HardwareIdWacomHandler interface {
	HandleZwpTabletToolV2HardwareIdWacom(ZwpTabletToolV2HardwareIdWacomEvent)
}

// AddHardwareIdWacomHandler adds the HardwareIdWacom handler
func (p *ZwpTabletToolV2) AddHardwareIdWacomHandler(h ZwpTabletToolV2HardwareIdWacomHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletToolV2HardwareIdWacoms[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveHardwareIdWacomHandler removes the HardwareIdWacom handler
func (p *ZwpTabletToolV2) RemoveHardwareIdWacomHandler(h ZwpTabletToolV2HardwareIdWacomHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletToolV2HardwareIdWacoms, h)
}

// ZwpTabletToolV2CapabilityHandler is the handler interface for ZwpTabletToolV2CapabilityEvent
type ZwpTabletToolV2CapabilityHandler interface {
	HandleZwpTabletToolV2Capability(ZwpTabletToolV2CapabilityEvent)
}

// AddCapabilityHandler adds the Capability handler
func (p *ZwpTabletToolV2) AddCapabilityHandler(h ZwpTabletToolV2CapabilityHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletToolV2Capabilitys[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveCapabilityHandler removes the Capability handler
func (p *ZwpTabletToolV2) RemoveCapabilityHandler(h ZwpTabletToolV2CapabilityHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletToolV2Capabilitys, h)
}

// ZwpTabletToolV2DoneHandler is the handler interface for ZwpTabletToolV2DoneEvent
type ZwpTabletToolV2DoneHandler interface {
	HandleZwpTabletToolV2Done(ZwpTabletToolV2DoneEvent)
}

// AddDoneHandler adds the Done handler
func (p *ZwpTabletToolV2) AddDoneHandler(h ZwpTabletToolV2DoneHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletToolV2Dones[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveDoneHandler removes the Done handler
func (p *ZwpTabletToolV2) RemoveDoneHandler(h ZwpTabletToolV2DoneHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletToolV2Dones, h)
}

// ZwpTabletToolV2RemovedHandler is the handler interface for ZwpTabletToolV2RemovedEvent
type ZwpTabletToolV2RemovedHandler interface {
	HandleZwpTabletToolV2Removed(ZwpTabletToolV2RemovedEvent)
}

// AddRemovedHandler adds the Removed handler
func (p *ZwpTabletToolV2) AddRemovedHandler(h ZwpTabletToolV2RemovedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletToolV2Removeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveRemovedHandler removes the Removed handler
func (p *ZwpTabletToolV2) RemoveRemovedHandler(h ZwpTabletToolV2RemovedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletToolV2Removeds, h)
}

// ZwpTabletToolV2ProximityInHandler is the handler interface for ZwpTabletToolV2ProximityInEvent
type ZwpTabletToolV2ProximityInHandler interface {
	HandleZwpTabletToolV2ProximityIn(ZwpTabletToolV2ProximityInEvent)
}

// AddProximityInHandler adds the ProximityIn handler
func (p *ZwpTabletToolV2) AddProximityInHandler(h ZwpTabletToolV2ProximityInHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletToolV2ProximityIns[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveProximityInHandler removes the ProximityIn handler
func (p *ZwpTabletToolV2) RemoveProximityInHandler(h ZwpTabletToolV2ProximityInHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletToolV2ProximityIns, h)
}

// ZwpTabletToolV2ProximityOutHandler is the handler interface for ZwpTabletToolV2ProximityOutEvent
type ZwpTabletToolV2ProximityOutHandler interface {
	HandleZwpTabletToolV2ProximityOut(ZwpTabletToolV2ProximityOutEvent)
}

// AddProximityOutHandler adds the ProximityOut handler
func (p *ZwpTabletToolV2) AddProximityOutHandler(h ZwpTabletToolV2ProximityOutHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletToolV2ProximityOuts[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveProximityOutHandler removes the ProximityOut handler
func (p *ZwpTabletToolV2) RemoveProximityOutHandler(h ZwpTabletToolV2ProximityOutHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletToolV2ProximityOuts, h)
}

// ZwpTabletToolV2DownHandler is the handler interface for ZwpTabletToolV2DownEvent
type ZwpTabletToolV2DownHandler interface {
	HandleZwpTabletToolV2Down(ZwpTabletToolV2DownEvent)
}

// AddDownHandler adds the Down handler
func (p *ZwpTabletToolV2) AddDownHandler(h ZwpTabletToolV2DownHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletToolV2Downs[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveDownHandler removes the Down handler
func (p *ZwpTabletToolV2) RemoveDownHandler(h ZwpTabletToolV2DownHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletToolV2Downs, h)
}

// ZwpTabletToolV2UpHandler is the handler interface for ZwpTabletToolV2UpEvent
type ZwpTabletToolV2UpHandler interface {
	HandleZwpTabletToolV2Up(ZwpTabletToolV2UpEvent)
}

// AddUpHandler adds the Up handler
func (p *ZwpTabletToolV2) AddUpHandler(h ZwpTabletToolV2UpHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletToolV2Ups[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveUpHandler removes the Up handler
func (p *ZwpTabletToolV2) RemoveUpHandler(h ZwpTabletToolV2UpHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletToolV2Ups, h)
}

// ZwpTabletToolV2MotionHandler is the handler interface for ZwpTabletToolV2MotionEvent
type ZwpTabletToolV2MotionHandler interface {
	HandleZwpTabletToolV2Motion(ZwpTabletToolV2MotionEvent)
}

// AddMotionHandler adds the Motion handler
func (p *ZwpTabletToolV2) AddMotionHandler(h ZwpTabletToolV2MotionHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletToolV2Motions[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveMotionHandler removes the Motion handler
func (p *ZwpTabletToolV2) RemoveMotionHandler(h ZwpTabletToolV2MotionHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletToolV2Motions, h)
}

// ZwpTabletToolV2PressureHandler is the handler interface for ZwpTabletToolV2PressureEvent
type ZwpTabletToolV2PressureHandler interface {
	HandleZwpTabletToolV2Pressure(ZwpTabletToolV2PressureEvent)
}

// AddPressureHandler adds the Pressure handler
func (p *ZwpTabletToolV2) AddPressureHandler(h ZwpTabletToolV2PressureHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletToolV2Pressures[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemovePressureHandler removes the Pressure handler
func (p *ZwpTabletToolV2) RemovePressureHandler(h ZwpTabletToolV2PressureHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletToolV2Pressures, h)
}

// ZwpTabletToolV2DistanceHandler is the handler interface for ZwpTabletToolV2DistanceEvent
type ZwpTabletToolV2DistanceHandler interface {
	HandleZwpTabletToolV2Distance(ZwpTabletToolV2DistanceEvent)
}

// AddDistanceHandler adds the Distance handler
func (p *ZwpTabletToolV2) AddDistanceHandler(h ZwpTabletToolV2DistanceHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletToolV2Distances[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveDistanceHandler removes the Distance handler
func (p *ZwpTabletToolV2) RemoveDistanceHandler(h ZwpTabletToolV2DistanceHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletToolV2Distances, h)
}

// ZwpTabletToolV2TiltHandler is the handler interface for ZwpTabletToolV2TiltEvent
type ZwpTabletToolV2TiltHandler interface {
	HandleZwpTabletToolV2Tilt(ZwpTabletToolV2TiltEvent)
}

// AddTiltHandler adds the Tilt handler
func (p *ZwpTabletToolV2) AddTiltHandler(h ZwpTabletToolV2TiltHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletToolV2Tilts[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveTiltHandler removes the Tilt handler
func (p *ZwpTabletToolV2) RemoveTiltHandler(h ZwpTabletToolV2TiltHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletToolV2Tilts, h)
}

// ZwpTabletToolV2RotationHandler is the handler interface for ZwpTabletToolV2RotationEvent
type ZwpTabletToolV2RotationHandler interface {
	HandleZwpTabletToolV2Rotation(ZwpTabletToolV2RotationEvent)
}

// AddRotationHandler adds the Rotation handler
func (p *ZwpTabletToolV2) AddRotationHandler(h ZwpTabletToolV2RotationHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletToolV2Rotations[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveRotationHandler removes the Rotation handler
func (p *ZwpTabletToolV2) RemoveRotationHandler(h ZwpTabletToolV2RotationHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletToolV2Rotations, h)
}

// ZwpTabletToolV2SliderHandler is the handler interface for ZwpTabletToolV2SliderEvent
type ZwpTabletToolV2SliderHandler interface {
	HandleZwpTabletToolV2Slider(ZwpTabletToolV2SliderEvent)
}

// AddSliderHandler adds the Slider handler
func (p *ZwpTabletToolV2) AddSliderHandler(h ZwpTabletToolV2SliderHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletToolV2Sliders[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveSliderHandler removes the Slider handler
func (p *ZwpTabletToolV2) RemoveSliderHandler(h ZwpTabletToolV2SliderHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletToolV2Sliders, h)
}

// ZwpTabletToolV2WheelHandler is the handler interface for ZwpTabletToolV2WheelEvent
type ZwpTabletToolV2WheelHandler interface {
	HandleZwpTabletToolV2Wheel(ZwpTabletToolV2WheelEvent)
}

// AddWheelHandler adds the Wheel handler
func (p *ZwpTabletToolV2) AddWheelHandler(h ZwpTabletToolV2WheelHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletToolV2Wheels[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveWheelHandler removes the Wheel handler
func (p *ZwpTabletToolV2) RemoveWheelHandler(h ZwpTabletToolV2WheelHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletToolV2Wheels, h)
}

// ZwpTabletToolV2ButtonHandler is the handler interface for ZwpTabletToolV2ButtonEvent
type ZwpTabletToolV2ButtonHandler interface {
	HandleZwpTabletToolV2Button(ZwpTabletToolV2ButtonEvent)
}

// AddButtonHandler adds the Button handler
func (p *ZwpTabletToolV2) AddButtonHandler(h ZwpTabletToolV2ButtonHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletToolV2Buttons[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveButtonHandler removes the Button handler
func (p *ZwpTabletToolV2) RemoveButtonHandler(h ZwpTabletToolV2ButtonHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletToolV2Buttons, h)
}

// ZwpTabletToolV2FrameHandler is the handler interface for ZwpTabletToolV2FrameEvent
type ZwpTabletToolV2FrameHandler interface {
	HandleZwpTabletToolV2Frame(ZwpTabletToolV2FrameEvent)
}

// AddFrameHandler adds the Frame handler
func (p *ZwpTabletToolV2) AddFrameHandler(h ZwpTabletToolV2FrameHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletToolV2Frames[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveFrameHandler removes the Frame handler
func (p *ZwpTabletToolV2) RemoveFrameHandler(h ZwpTabletToolV2FrameHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletToolV2Frames, h)
}

// ZwpTabletV2 graphics tablet device
type ZwpTabletV2 struct {
	BaseProxy
	mu                         sync.RWMutex
	privateZwpTabletV2Names    map[ZwpTabletV2NameHandler]struct{}
	privateZwpTabletV2Ids      map[ZwpTabletV2IdHandler]struct{}
	privateZwpTabletV2Paths    map[ZwpTabletV2PathHandler]struct{}
	privateZwpTabletV2Dones    map[ZwpTabletV2DoneHandler]struct{}
	privateZwpTabletV2Removeds map[ZwpTabletV2RemovedHandler]struct{}
}

// initZwpTabletV2 initializes the ZwpTabletV2 object's handler maps
func (ret *ZwpTabletV2) initZwpTabletV2() {
	ret.privateZwpTabletV2Names = make(map[ZwpTabletV2NameHandler]struct{})
	ret.privateZwpTabletV2Ids = make(map[ZwpTabletV2IdHandler]struct{})
	ret.privateZwpTabletV2Paths = make(map[ZwpTabletV2PathHandler]struct{})
	ret.privateZwpTabletV2Dones = make(map[ZwpTabletV2DoneHandler]struct{})
	ret.privateZwpTabletV2Removeds = make(map[ZwpTabletV2RemovedHandler]struct{})
}

// NewZwpTabletV2 is a constructor for the ZwpTabletV2 object
func NewZwpTabletV2(ctx *Context) *ZwpTabletV2 {
	ret := new(ZwpTabletV2)
	ret.initZwpTabletV2()
	ctx.Register(ret)
	return ret
}

// Destroy destroy the tablet object
func (p *ZwpTabletV2) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// Dispatch dispatches event for object ZwpTabletV2
func (p *ZwpTabletV2) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwpTabletV2Names) > 0 {
			ev := ZwpTabletV2NameEvent{}
			ev.Name = event.String()
			p.mu.RLock()
			for h := range p.privateZwpTabletV2Names {
				h.HandleZwpTabletV2Name(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateZwpTabletV2Ids) > 0 {
			ev := ZwpTabletV2IdEvent{}
			ev.Vid = event.Uint32()
			ev.Pid = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpTabletV2Ids {
				h.HandleZwpTabletV2Id(ev)
			}
			p.mu.RUnlock()
		}
	case 2:
		if len(p.privateZwpTabletV2Paths) > 0 {
			ev := ZwpTabletV2PathEvent{}
			ev.Path = event.String()
			p.mu.RLock()
			for h := range p.privateZwpTabletV2Paths {
				h.HandleZwpTabletV2Path(ev)
			}
			p.mu.RUnlock()
		}
	case 3:
		if len(p.privateZwpTabletV2Dones) > 0 {
			ev := ZwpTabletV2DoneEvent{}
			p.mu.RLock()
			for h := range p.privateZwpTabletV2Dones {
				h.HandleZwpTabletV2Done(ev)
			}
			p.mu.RUnlock()
		}
	case 4:
		if len(p.privateZwpTabletV2Removeds) > 0 {
			ev := ZwpTabletV2RemovedEvent{}
			p.mu.RLock()
			for h := range p.privateZwpTabletV2Removeds {
				h.HandleZwpTabletV2Removed(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ZwpTabletV2NameEvent is the tablet device name
type ZwpTabletV2NameEvent struct {
	// Name is the the device name
	Name string
}

// ZwpTabletV2IdEvent is the tablet device USB vendor/product id
type ZwpTabletV2IdEvent struct {
	// Vid is the USB vendor id
	Vid uint32
	// Pid is the USB product id
	Pid uint32
}

// ZwpTabletV2PathEvent is the path to the device
type ZwpTabletV2PathEvent struct {
	// Path is the path to local device
	Path string
}

// ZwpTabletV2DoneEvent is the tablet description events sequence complete
type ZwpTabletV2DoneEvent struct {
}

// ZwpTabletV2RemovedEvent is the tablet removed event
type ZwpTabletV2RemovedEvent struct {
}

// ZwpTabletV2NameHandler is the handler interface for ZwpTabletV2NameEvent
type ZwpTabletV2NameHandler interface {
	HandleZwpTabletV2Name(ZwpTabletV2NameEvent)
}

// AddNameHandler adds the Name handler
func (p *ZwpTabletV2) AddNameHandler(h ZwpTabletV2NameHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletV2Names[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveNameHandler removes the Name handler
func (p *ZwpTabletV2) RemoveNameHandler(h ZwpTabletV2NameHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletV2Names, h)
}

// ZwpTabletV2IdHandler is the handler interface for ZwpTabletV2IdEvent
type ZwpTabletV2IdHandler interface {
	HandleZwpTabletV2Id(ZwpTabletV2IdEvent)
}

// AddIdHandler adds the Id handler
func (p *ZwpTabletV2) AddIdHandler(h ZwpTabletV2IdHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletV2Ids[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveIdHandler removes the Id handler
func (p *ZwpTabletV2) RemoveIdHandler(h ZwpTabletV2IdHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletV2Ids, h)
}

// ZwpTabletV2PathHandler is the handler interface for ZwpTabletV2PathEvent
type ZwpTabletV2PathHandler interface {
	HandleZwpTabletV2Path(ZwpTabletV2PathEvent)
}

// AddPathHandler adds the Path handler
func (p *ZwpTabletV2) AddPathHandler(h ZwpTabletV2PathHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletV2Paths[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemovePathHandler removes the Path handler
func (p *ZwpTabletV2) RemovePathHandler(h ZwpTabletV2PathHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletV2Paths, h)
}

// ZwpTabletV2DoneHandler is the handler interface for ZwpTabletV2DoneEvent
type ZwpTabletV2DoneHandler interface {
	HandleZwpTabletV2Done(ZwpTabletV2DoneEvent)
}

// AddDoneHandler adds the Done handler
func (p *ZwpTabletV2) AddDoneHandler(h ZwpTabletV2DoneHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletV2Dones[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveDoneHandler removes the Done handler
func (p *ZwpTabletV2) RemoveDoneHandler(h ZwpTabletV2DoneHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletV2Dones, h)
}

// ZwpTabletV2RemovedHandler is the handler interface for ZwpTabletV2RemovedEvent
type ZwpTabletV2RemovedHandler interface {
	HandleZwpTabletV2Removed(ZwpTabletV2RemovedEvent)
}

// AddRemovedHandler adds the Removed handler
func (p *ZwpTabletV2) AddRemovedHandler(h ZwpTabletV2RemovedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletV2Removeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveRemovedHandler removes the Removed handler
func (p *ZwpTabletV2) RemoveRemovedHandler(h ZwpTabletV2RemovedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletV2Removeds, h)
}

// ZwpTabletPadRingV2 pad ring
type ZwpTabletPadRingV2 struct {
	BaseProxy
	mu                               sync.RWMutex
	privateZwpTabletPadRingV2Sources map[ZwpTabletPadRingV2SourceHandler]struct{}
	privateZwpTabletPadRingV2Angles  map[ZwpTabletPadRingV2AngleHandler]struct{}
	privateZwpTabletPadRingV2Stops   map[ZwpTabletPadRingV2StopHandler]struct{}
	privateZwpTabletPadRingV2Frames  map[ZwpTabletPadRingV2FrameHandler]struct{}
}

// initZwpTabletPadRingV2 initializes the ZwpTabletPadRingV2 object's handler maps
func (ret *ZwpTabletPadRingV2) initZwpTabletPadRingV2() {
	ret.privateZwpTabletPadRingV2Sources = make(map[ZwpTabletPadRingV2SourceHandler]struct{})
	ret.privateZwpTabletPadRingV2Angles = make(map[ZwpTabletPadRingV2AngleHandler]struct{})
	ret.privateZwpTabletPadRingV2Stops = make(map[ZwpTabletPadRingV2StopHandler]struct{})
	ret.privateZwpTabletPadRingV2Frames = make(map[ZwpTabletPadRingV2FrameHandler]struct{})
}

// NewZwpTabletPadRingV2 is a constructor for the ZwpTabletPadRingV2 object
func NewZwpTabletPadRingV2(ctx *Context) *ZwpTabletPadRingV2 {
	ret := new(ZwpTabletPadRingV2)
	ret.initZwpTabletPadRingV2()
	ctx.Register(ret)
	return ret
}

// SetFeedback set compositor feedback
func (p *ZwpTabletPadRingV2) SetFeedback(Description string, Serial uint32) error {

	return p.Context().SendRequest(p, 0, Description, Serial)
}

// Destroy destroy the ring object
func (p *ZwpTabletPadRingV2) Destroy() error {

	return p.Context().SendRequest(p, 1)
}

// Dispatch dispatches event for object ZwpTabletPadRingV2
func (p *ZwpTabletPadRingV2) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwpTabletPadRingV2Sources) > 0 {
			ev := ZwpTabletPadRingV2SourceEvent{}
			ev.Source = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpTabletPadRingV2Sources {
				h.HandleZwpTabletPadRingV2Source(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateZwpTabletPadRingV2Angles) > 0 {
			ev := ZwpTabletPadRingV2AngleEvent{}
			ev.Degrees = event.Float32()
			p.mu.RLock()
			for h := range p.privateZwpTabletPadRingV2Angles {
				h.HandleZwpTabletPadRingV2Angle(ev)
			}
			p.mu.RUnlock()
		}
	case 2:
		if len(p.privateZwpTabletPadRingV2Stops) > 0 {
			ev := ZwpTabletPadRingV2StopEvent{}
			p.mu.RLock()
			for h := range p.privateZwpTabletPadRingV2Stops {
				h.HandleZwpTabletPadRingV2Stop(ev)
			}
			p.mu.RUnlock()
		}
	case 3:
		if len(p.privateZwpTabletPadRingV2Frames) > 0 {
			ev := ZwpTabletPadRingV2FrameEvent{}
			ev.Time = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpTabletPadRingV2Frames {
				h.HandleZwpTabletPadRingV2Frame(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ZwpTabletPadRingV2SourceEvent is the ring event source
type ZwpTabletPadRingV2SourceEvent struct {
	// Source is the the event source
	Source uint32
}

// ZwpTabletPadRingV2AngleEvent is the angle changed
type ZwpTabletPadRingV2AngleEvent struct {
	// Degrees is the the current angle in degrees
	Degrees float32
}

// ZwpTabletPadRingV2StopEvent is the interaction stopped
type ZwpTabletPadRingV2StopEvent struct {
}

// ZwpTabletPadRingV2FrameEvent is the end of a ring event sequence
type ZwpTabletPadRingV2FrameEvent struct {
	// Time is the timestamp with millisecond granularity
	Time uint32
}

// ZwpTabletPadRingV2SourceHandler is the handler interface for ZwpTabletPadRingV2SourceEvent
type ZwpTabletPadRingV2SourceHandler interface {
	HandleZwpTabletPadRingV2Source(ZwpTabletPadRingV2SourceEvent)
}

// AddSourceHandler adds the Source handler
func (p *ZwpTabletPadRingV2) AddSourceHandler(h ZwpTabletPadRingV2SourceHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletPadRingV2Sources[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveSourceHandler removes the Source handler
func (p *ZwpTabletPadRingV2) RemoveSourceHandler(h ZwpTabletPadRingV2SourceHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletPadRingV2Sources, h)
}

// ZwpTabletPadRingV2AngleHandler is the handler interface for ZwpTabletPadRingV2AngleEvent
type ZwpTabletPadRingV2AngleHandler interface {
	HandleZwpTabletPadRingV2Angle(ZwpTabletPadRingV2AngleEvent)
}

// AddAngleHandler adds the Angle handler
func (p *ZwpTabletPadRingV2) AddAngleHandler(h ZwpTabletPadRingV2AngleHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletPadRingV2Angles[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveAngleHandler removes the Angle handler
func (p *ZwpTabletPadRingV2) RemoveAngleHandler(h ZwpTabletPadRingV2AngleHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletPadRingV2Angles, h)
}

// ZwpTabletPadRingV2StopHandler is the handler interface for ZwpTabletPadRingV2StopEvent
type ZwpTabletPadRingV2StopHandler interface {
	HandleZwpTabletPadRingV2Stop(ZwpTabletPadRingV2StopEvent)
}

// AddStopHandler adds the Stop handler
func (p *ZwpTabletPadRingV2) AddStopHandler(h ZwpTabletPadRingV2StopHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletPadRingV2Stops[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveStopHandler removes the Stop handler
func (p *ZwpTabletPadRingV2) RemoveStopHandler(h ZwpTabletPadRingV2StopHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletPadRingV2Stops, h)
}

// ZwpTabletPadRingV2FrameHandler is the handler interface for ZwpTabletPadRingV2FrameEvent
type ZwpTabletPadRingV2FrameHandler interface {
	HandleZwpTabletPadRingV2Frame(ZwpTabletPadRingV2FrameEvent)
}

// AddFrameHandler adds the Frame handler
func (p *ZwpTabletPadRingV2) AddFrameHandler(h ZwpTabletPadRingV2FrameHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletPadRingV2Frames[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveFrameHandler removes the Frame handler
func (p *ZwpTabletPadRingV2) RemoveFrameHandler(h ZwpTabletPadRingV2FrameHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletPadRingV2Frames, h)
}

// ZwpTabletPadStripV2 pad strip
type ZwpTabletPadStripV2 struct {
	BaseProxy
	mu                                  sync.RWMutex
	privateZwpTabletPadStripV2Sources   map[ZwpTabletPadStripV2SourceHandler]struct{}
	privateZwpTabletPadStripV2Positions map[ZwpTabletPadStripV2PositionHandler]struct{}
	privateZwpTabletPadStripV2Stops     map[ZwpTabletPadStripV2StopHandler]struct{}
	privateZwpTabletPadStripV2Frames    map[ZwpTabletPadStripV2FrameHandler]struct{}
}

// initZwpTabletPadStripV2 initializes the ZwpTabletPadStripV2 object's handler maps
func (ret *ZwpTabletPadStripV2) initZwpTabletPadStripV2() {
	ret.privateZwpTabletPadStripV2Sources = make(map[ZwpTabletPadStripV2SourceHandler]struct{})
	ret.privateZwpTabletPadStripV2Positions = make(map[ZwpTabletPadStripV2PositionHandler]struct{})
	ret.privateZwpTabletPadStripV2Stops = make(map[ZwpTabletPadStripV2StopHandler]struct{})
	ret.privateZwpTabletPadStripV2Frames = make(map[ZwpTabletPadStripV2FrameHandler]struct{})
}

// NewZwpTabletPadStripV2 is a constructor for the ZwpTabletPadStripV2 object
func NewZwpTabletPadStripV2(ctx *Context) *ZwpTabletPadStripV2 {
	ret := new(ZwpTabletPadStripV2)
	ret.initZwpTabletPadStripV2()
	ctx.Register(ret)
	return ret
}

// SetFeedback set compositor feedback
func (p *ZwpTabletPadStripV2) SetFeedback(Description string, Serial uint32) error {

	return p.Context().SendRequest(p, 0, Description, Serial)
}

// Destroy destroy the strip object
func (p *ZwpTabletPadStripV2) Destroy() error {

	return p.Context().SendRequest(p, 1)
}

// Dispatch dispatches event for object ZwpTabletPadStripV2
func (p *ZwpTabletPadStripV2) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwpTabletPadStripV2Sources) > 0 {
			ev := ZwpTabletPadStripV2SourceEvent{}
			ev.Source = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpTabletPadStripV2Sources {
				h.HandleZwpTabletPadStripV2Source(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateZwpTabletPadStripV2Positions) > 0 {
			ev := ZwpTabletPadStripV2PositionEvent{}
			ev.Position = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpTabletPadStripV2Positions {
				h.HandleZwpTabletPadStripV2Position(ev)
			}
			p.mu.RUnlock()
		}
	case 2:
		if len(p.privateZwpTabletPadStripV2Stops) > 0 {
			ev := ZwpTabletPadStripV2StopEvent{}
			p.mu.RLock()
			for h := range p.privateZwpTabletPadStripV2Stops {
				h.HandleZwpTabletPadStripV2Stop(ev)
			}
			p.mu.RUnlock()
		}
	case 3:
		if len(p.privateZwpTabletPadStripV2Frames) > 0 {
			ev := ZwpTabletPadStripV2FrameEvent{}
			ev.Time = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpTabletPadStripV2Frames {
				h.HandleZwpTabletPadStripV2Frame(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ZwpTabletPadStripV2SourceEvent is the strip event source
type ZwpTabletPadStripV2SourceEvent struct {
	// Source is the the event source
	Source uint32
}

// ZwpTabletPadStripV2PositionEvent is the position changed
type ZwpTabletPadStripV2PositionEvent struct {
	// Position is the the current position
	Position uint32
}

// ZwpTabletPadStripV2StopEvent is the interaction stopped
type ZwpTabletPadStripV2StopEvent struct {
}

// ZwpTabletPadStripV2FrameEvent is the end of a strip event sequence
type ZwpTabletPadStripV2FrameEvent struct {
	// Time is the timestamp with millisecond granularity
	Time uint32
}

// ZwpTabletPadStripV2SourceHandler is the handler interface for ZwpTabletPadStripV2SourceEvent
type ZwpTabletPadStripV2SourceHandler interface {
	HandleZwpTabletPadStripV2Source(ZwpTabletPadStripV2SourceEvent)
}

// AddSourceHandler adds the Source handler
func (p *ZwpTabletPadStripV2) AddSourceHandler(h ZwpTabletPadStripV2SourceHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletPadStripV2Sources[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveSourceHandler removes the Source handler
func (p *ZwpTabletPadStripV2) RemoveSourceHandler(h ZwpTabletPadStripV2SourceHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletPadStripV2Sources, h)
}

// ZwpTabletPadStripV2PositionHandler is the handler interface for ZwpTabletPadStripV2PositionEvent
type ZwpTabletPadStripV2PositionHandler interface {
	HandleZwpTabletPadStripV2Position(ZwpTabletPadStripV2PositionEvent)
}

// AddPositionHandler adds the Position handler
func (p *ZwpTabletPadStripV2) AddPositionHandler(h ZwpTabletPadStripV2PositionHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletPadStripV2Positions[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemovePositionHandler removes the Position handler
func (p *ZwpTabletPadStripV2) RemovePositionHandler(h ZwpTabletPadStripV2PositionHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletPadStripV2Positions, h)
}

// ZwpTabletPadStripV2StopHandler is the handler interface for ZwpTabletPadStripV2StopEvent
type ZwpTabletPadStripV2StopHandler interface {
	HandleZwpTabletPadStripV2Stop(ZwpTabletPadStripV2StopEvent)
}

// AddStopHandler adds the Stop handler
func (p *ZwpTabletPadStripV2) AddStopHandler(h ZwpTabletPadStripV2StopHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletPadStripV2Stops[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveStopHandler removes the Stop handler
func (p *ZwpTabletPadStripV2) RemoveStopHandler(h ZwpTabletPadStripV2StopHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletPadStripV2Stops, h)
}

// ZwpTabletPadStripV2FrameHandler is the handler interface for ZwpTabletPadStripV2FrameEvent
type ZwpTabletPadStripV2FrameHandler interface {
	HandleZwpTabletPadStripV2Frame(ZwpTabletPadStripV2FrameEvent)
}

// AddFrameHandler adds the Frame handler
func (p *ZwpTabletPadStripV2) AddFrameHandler(h ZwpTabletPadStripV2FrameHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletPadStripV2Frames[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveFrameHandler removes the Frame handler
func (p *ZwpTabletPadStripV2) RemoveFrameHandler(h ZwpTabletPadStripV2FrameHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletPadStripV2Frames, h)
}

// ZwpTabletPadGroupV2 a set of buttons, rings and strips
type ZwpTabletPadGroupV2 struct {
	BaseProxy
	mu                                    sync.RWMutex
	privateZwpTabletPadGroupV2Buttonss    map[ZwpTabletPadGroupV2ButtonsHandler]struct{}
	privateZwpTabletPadGroupV2Rings       map[ZwpTabletPadGroupV2RingHandler]struct{}
	privateZwpTabletPadGroupV2Strips      map[ZwpTabletPadGroupV2StripHandler]struct{}
	privateZwpTabletPadGroupV2Modess      map[ZwpTabletPadGroupV2ModesHandler]struct{}
	privateZwpTabletPadGroupV2Dones       map[ZwpTabletPadGroupV2DoneHandler]struct{}
	privateZwpTabletPadGroupV2ModeSwitchs map[ZwpTabletPadGroupV2ModeSwitchHandler]struct{}
}

// initZwpTabletPadGroupV2 initializes the ZwpTabletPadGroupV2 object's handler maps
func (ret *ZwpTabletPadGroupV2) initZwpTabletPadGroupV2() {
	ret.privateZwpTabletPadGroupV2Buttonss = make(map[ZwpTabletPadGroupV2ButtonsHandler]struct{})
	ret.privateZwpTabletPadGroupV2Rings = make(map[ZwpTabletPadGroupV2RingHandler]struct{})
	ret.privateZwpTabletPadGroupV2Strips = make(map[ZwpTabletPadGroupV2StripHandler]struct{})
	ret.privateZwpTabletPadGroupV2Modess = make(map[ZwpTabletPadGroupV2ModesHandler]struct{})
	ret.privateZwpTabletPadGroupV2Dones = make(map[ZwpTabletPadGroupV2DoneHandler]struct{})
	ret.privateZwpTabletPadGroupV2ModeSwitchs = make(map[ZwpTabletPadGroupV2ModeSwitchHandler]struct{})
}

// NewZwpTabletPadGroupV2 is a constructor for the ZwpTabletPadGroupV2 object
func NewZwpTabletPadGroupV2(ctx *Context) *ZwpTabletPadGroupV2 {
	ret := new(ZwpTabletPadGroupV2)
	ret.initZwpTabletPadGroupV2()
	ctx.Register(ret)
	return ret
}

// Destroy destroy the pad object
func (p *ZwpTabletPadGroupV2) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// Dispatch dispatches event for object ZwpTabletPadGroupV2
func (p *ZwpTabletPadGroupV2) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwpTabletPadGroupV2Buttonss) > 0 {
			ev := ZwpTabletPadGroupV2ButtonsEvent{}
			ev.Buttons = event.Array()
			p.mu.RLock()
			for h := range p.privateZwpTabletPadGroupV2Buttonss {
				h.HandleZwpTabletPadGroupV2Buttons(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateZwpTabletPadGroupV2Rings) > 0 {
			ev := ZwpTabletPadGroupV2RingEvent{}
			ev.Ring = func() *ZwpTabletPadRingV2 {
				ret := new(ZwpTabletPadRingV2)
				ret.initZwpTabletPadRingV2()
				return event.NewId(ret, p.Context()).(*ZwpTabletPadRingV2)
			}()
			p.mu.RLock()
			for h := range p.privateZwpTabletPadGroupV2Rings {
				h.HandleZwpTabletPadGroupV2Ring(ev)
			}
			p.mu.RUnlock()
		}
	case 2:
		if len(p.privateZwpTabletPadGroupV2Strips) > 0 {
			ev := ZwpTabletPadGroupV2StripEvent{}
			ev.Strip = func() *ZwpTabletPadStripV2 {
				ret := new(ZwpTabletPadStripV2)
				ret.initZwpTabletPadStripV2()
				return event.NewId(ret, p.Context()).(*ZwpTabletPadStripV2)
			}()
			p.mu.RLock()
			for h := range p.privateZwpTabletPadGroupV2Strips {
				h.HandleZwpTabletPadGroupV2Strip(ev)
			}
			p.mu.RUnlock()
		}
	case 3:
		if len(p.privateZwpTabletPadGroupV2Modess) > 0 {
			ev := ZwpTabletPadGroupV2ModesEvent{}
			ev.Modes = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpTabletPadGroupV2Modess {
				h.HandleZwpTabletPadGroupV2Modes(ev)
			}
			p.mu.RUnlock()
		}
	case 4:
		if len(p.privateZwpTabletPadGroupV2Dones) > 0 {
			ev := ZwpTabletPadGroupV2DoneEvent{}
			p.mu.RLock()
			for h := range p.privateZwpTabletPadGroupV2Dones {
				h.HandleZwpTabletPadGroupV2Done(ev)
			}
			p.mu.RUnlock()
		}
	case 5:
		if len(p.privateZwpTabletPadGroupV2ModeSwitchs) > 0 {
			ev := ZwpTabletPadGroupV2ModeSwitchEvent{}
			ev.Time = event.Uint32()
			ev.Serial = event.Uint32()
			ev.Mode = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpTabletPadGroupV2ModeSwitchs {
				h.HandleZwpTabletPadGroupV2ModeSwitch(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ZwpTabletPadGroupV2ButtonsEvent is the buttons announced
type ZwpTabletPadGroupV2ButtonsEvent struct {
	// Buttons is the buttons in this group
	Buttons []int32
}

// ZwpTabletPadGroupV2RingEvent is the ring announced
type ZwpTabletPadGroupV2RingEvent struct {
	// Ring is the
	Ring *ZwpTabletPadRingV2
}

// ZwpTabletPadGroupV2StripEvent is the strip announced
type ZwpTabletPadGroupV2StripEvent struct {
	// Strip is the
	Strip *ZwpTabletPadStripV2
}

// ZwpTabletPadGroupV2ModesEvent is the mode-switch ability announced
type ZwpTabletPadGroupV2ModesEvent struct {
	// Modes is the the number of modes
	Modes uint32
}

// ZwpTabletPadGroupV2DoneEvent is the tablet group description events sequence complete
type ZwpTabletPadGroupV2DoneEvent struct {
}

// ZwpTabletPadGroupV2ModeSwitchEvent is the mode switch event
type ZwpTabletPadGroupV2ModeSwitchEvent struct {
	// Time is the the time of the event with millisecond granularity
	Time uint32
	// Serial is the
	Serial uint32
	// Mode is the the new mode of the pad
	Mode uint32
}

// ZwpTabletPadGroupV2ButtonsHandler is the handler interface for ZwpTabletPadGroupV2ButtonsEvent
type ZwpTabletPadGroupV2ButtonsHandler interface {
	HandleZwpTabletPadGroupV2Buttons(ZwpTabletPadGroupV2ButtonsEvent)
}

// AddButtonsHandler adds the Buttons handler
func (p *ZwpTabletPadGroupV2) AddButtonsHandler(h ZwpTabletPadGroupV2ButtonsHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletPadGroupV2Buttonss[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveButtonsHandler removes the Buttons handler
func (p *ZwpTabletPadGroupV2) RemoveButtonsHandler(h ZwpTabletPadGroupV2ButtonsHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletPadGroupV2Buttonss, h)
}

// ZwpTabletPadGroupV2RingHandler is the handler interface for ZwpTabletPadGroupV2RingEvent
type ZwpTabletPadGroupV2RingHandler interface {
	HandleZwpTabletPadGroupV2Ring(ZwpTabletPadGroupV2RingEvent)
}

// AddRingHandler adds the Ring handler
func (p *ZwpTabletPadGroupV2) AddRingHandler(h ZwpTabletPadGroupV2RingHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletPadGroupV2Rings[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveRingHandler removes the Ring handler
func (p *ZwpTabletPadGroupV2) RemoveRingHandler(h ZwpTabletPadGroupV2RingHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletPadGroupV2Rings, h)
}

// ZwpTabletPadGroupV2StripHandler is the handler interface for ZwpTabletPadGroupV2StripEvent
type ZwpTabletPadGroupV2StripHandler interface {
	HandleZwpTabletPadGroupV2Strip(ZwpTabletPadGroupV2StripEvent)
}

// AddStripHandler adds the Strip handler
func (p *ZwpTabletPadGroupV2) AddStripHandler(h ZwpTabletPadGroupV2StripHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletPadGroupV2Strips[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveStripHandler removes the Strip handler
func (p *ZwpTabletPadGroupV2) RemoveStripHandler(h ZwpTabletPadGroupV2StripHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletPadGroupV2Strips, h)
}

// ZwpTabletPadGroupV2ModesHandler is the handler interface for ZwpTabletPadGroupV2ModesEvent
type ZwpTabletPadGroupV2ModesHandler interface {
	HandleZwpTabletPadGroupV2Modes(ZwpTabletPadGroupV2ModesEvent)
}

// AddModesHandler adds the Modes handler
func (p *ZwpTabletPadGroupV2) AddModesHandler(h ZwpTabletPadGroupV2ModesHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletPadGroupV2Modess[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveModesHandler removes the Modes handler
func (p *ZwpTabletPadGroupV2) RemoveModesHandler(h ZwpTabletPadGroupV2ModesHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletPadGroupV2Modess, h)
}

// ZwpTabletPadGroupV2DoneHandler is the handler interface for ZwpTabletPadGroupV2DoneEvent
type ZwpTabletPadGroupV2DoneHandler interface {
	HandleZwpTabletPadGroupV2Done(ZwpTabletPadGroupV2DoneEvent)
}

// AddDoneHandler adds the Done handler
func (p *ZwpTabletPadGroupV2) AddDoneHandler(h ZwpTabletPadGroupV2DoneHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletPadGroupV2Dones[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveDoneHandler removes the Done handler
func (p *ZwpTabletPadGroupV2) RemoveDoneHandler(h ZwpTabletPadGroupV2DoneHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletPadGroupV2Dones, h)
}

// ZwpTabletPadGroupV2ModeSwitchHandler is the handler interface for ZwpTabletPadGroupV2ModeSwitchEvent
type ZwpTabletPadGroupV2ModeSwitchHandler interface {
	HandleZwpTabletPadGroupV2ModeSwitch(ZwpTabletPadGroupV2ModeSwitchEvent)
}

// AddModeSwitchHandler adds the ModeSwitch handler
func (p *ZwpTabletPadGroupV2) AddModeSwitchHandler(h ZwpTabletPadGroupV2ModeSwitchHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletPadGroupV2ModeSwitchs[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveModeSwitchHandler removes the ModeSwitch handler
func (p *ZwpTabletPadGroupV2) RemoveModeSwitchHandler(h ZwpTabletPadGroupV2ModeSwitchHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletPadGroupV2ModeSwitchs, h)
}

// ZwpTabletPadV2 a set of buttons, rings and strips
type ZwpTabletPadV2 struct {
	BaseProxy
	mu                            sync.RWMutex
	privateZwpTabletPadV2Groups   map[ZwpTabletPadV2GroupHandler]struct{}
	privateZwpTabletPadV2Paths    map[ZwpTabletPadV2PathHandler]struct{}
	privateZwpTabletPadV2Buttonss map[ZwpTabletPadV2ButtonsHandler]struct{}
	privateZwpTabletPadV2Dones    map[ZwpTabletPadV2DoneHandler]struct{}
	privateZwpTabletPadV2Buttons  map[ZwpTabletPadV2ButtonHandler]struct{}
	privateZwpTabletPadV2Enters   map[ZwpTabletPadV2EnterHandler]struct{}
	privateZwpTabletPadV2Leaves   map[ZwpTabletPadV2LeaveHandler]struct{}
	privateZwpTabletPadV2Removeds map[ZwpTabletPadV2RemovedHandler]struct{}
}

// initZwpTabletPadV2 initializes the ZwpTabletPadV2 object's handler maps
func (ret *ZwpTabletPadV2) initZwpTabletPadV2() {
	ret.privateZwpTabletPadV2Groups = make(map[ZwpTabletPadV2GroupHandler]struct{})
	ret.privateZwpTabletPadV2Paths = make(map[ZwpTabletPadV2PathHandler]struct{})
	ret.privateZwpTabletPadV2Buttonss = make(map[ZwpTabletPadV2ButtonsHandler]struct{})
	ret.privateZwpTabletPadV2Dones = make(map[ZwpTabletPadV2DoneHandler]struct{})
	ret.privateZwpTabletPadV2Buttons = make(map[ZwpTabletPadV2ButtonHandler]struct{})
	ret.privateZwpTabletPadV2Enters = make(map[ZwpTabletPadV2EnterHandler]struct{})
	ret.privateZwpTabletPadV2Leaves = make(map[ZwpTabletPadV2LeaveHandler]struct{})
	ret.privateZwpTabletPadV2Removeds = make(map[ZwpTabletPadV2RemovedHandler]struct{})
}

// NewZwpTabletPadV2 is a constructor for the ZwpTabletPadV2 object
func NewZwpTabletPadV2(ctx *Context) *ZwpTabletPadV2 {
	ret := new(ZwpTabletPadV2)
	ret.initZwpTabletPadV2()
	ctx.Register(ret)
	return ret
}

// SetFeedback set compositor feedback
func (p *ZwpTabletPadV2) SetFeedback(Button uint32, Description string, Serial uint32) error {

	return p.Context().SendRequest(p, 0, Button, Description, Serial)
}

// Destroy destroy the pad object
func (p *ZwpTabletPadV2) Destroy() error {

	return p.Context().SendRequest(p, 1)
}

// Dispatch dispatches event for object ZwpTabletPadV2
func (p *ZwpTabletPadV2) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwpTabletPadV2Groups) > 0 {
			ev := ZwpTabletPadV2GroupEvent{}
			ev.PadGroup = func() *ZwpTabletPadGroupV2 {
				ret := new(ZwpTabletPadGroupV2)
				ret.initZwpTabletPadGroupV2()
				return event.NewId(ret, p.Context()).(*ZwpTabletPadGroupV2)
			}()
			p.mu.RLock()
			for h := range p.privateZwpTabletPadV2Groups {
				h.HandleZwpTabletPadV2Group(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateZwpTabletPadV2Paths) > 0 {
			ev := ZwpTabletPadV2PathEvent{}
			ev.Path = event.String()
			p.mu.RLock()
			for h := range p.privateZwpTabletPadV2Paths {
				h.HandleZwpTabletPadV2Path(ev)
			}
			p.mu.RUnlock()
		}
	case 2:
		if len(p.privateZwpTabletPadV2Buttonss) > 0 {
			ev := ZwpTabletPadV2ButtonsEvent{}
			ev.Buttons = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpTabletPadV2Buttonss {
				h.HandleZwpTabletPadV2Buttons(ev)
			}
			p.mu.RUnlock()
		}
	case 3:
		if len(p.privateZwpTabletPadV2Dones) > 0 {
			ev := ZwpTabletPadV2DoneEvent{}
			p.mu.RLock()
			for h := range p.privateZwpTabletPadV2Dones {
				h.HandleZwpTabletPadV2Done(ev)
			}
			p.mu.RUnlock()
		}
	case 4:
		if len(p.privateZwpTabletPadV2Buttons) > 0 {
			ev := ZwpTabletPadV2ButtonEvent{}
			ev.Time = event.Uint32()
			ev.Button = event.Uint32()
			ev.State = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpTabletPadV2Buttons {
				h.HandleZwpTabletPadV2Button(ev)
			}
			p.mu.RUnlock()
		}
	case 5:
		if len(p.privateZwpTabletPadV2Enters) > 0 {
			ev := ZwpTabletPadV2EnterEvent{}
			ev.Serial = event.Uint32()
			ev.Tablet = SafeCast[*ZwpTabletV2](event.Proxy(p.Context()))
			ev.Surface = SafeCast[*Surface](event.Proxy(p.Context()))
			p.mu.RLock()
			for h := range p.privateZwpTabletPadV2Enters {
				h.HandleZwpTabletPadV2Enter(ev)
			}
			p.mu.RUnlock()
		}
	case 6:
		if len(p.privateZwpTabletPadV2Leaves) > 0 {
			ev := ZwpTabletPadV2LeaveEvent{}
			ev.Serial = event.Uint32()
			ev.Surface = SafeCast[*Surface](event.Proxy(p.Context()))
			p.mu.RLock()
			for h := range p.privateZwpTabletPadV2Leaves {
				h.HandleZwpTabletPadV2Leave(ev)
			}
			p.mu.RUnlock()
		}
	case 7:
		if len(p.privateZwpTabletPadV2Removeds) > 0 {
			ev := ZwpTabletPadV2RemovedEvent{}
			p.mu.RLock()
			for h := range p.privateZwpTabletPadV2Removeds {
				h.HandleZwpTabletPadV2Removed(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ZwpTabletPadV2GroupEvent is the group announced
type ZwpTabletPadV2GroupEvent struct {
	// PadGroup is the
	PadGroup *ZwpTabletPadGroupV2
}

// ZwpTabletPadV2PathEvent is the path to the device
type ZwpTabletPadV2PathEvent struct {
	// Path is the path to local device
	Path string
}

// ZwpTabletPadV2ButtonsEvent is the buttons announced
type ZwpTabletPadV2ButtonsEvent struct {
	// Buttons is the the number of buttons
	Buttons uint32
}

// ZwpTabletPadV2DoneEvent is the pad description event sequence complete
type ZwpTabletPadV2DoneEvent struct {
}

// ZwpTabletPadV2ButtonEvent is the physical button state
type ZwpTabletPadV2ButtonEvent struct {
	// Time is the the time of the event with millisecond granularity
	Time uint32
	// Button is the the index of the button that changed state
	Button uint32
	// State is the
	State uint32
}

// ZwpTabletPadV2EnterEvent is the enter event
type ZwpTabletPadV2EnterEvent struct {
	// Serial is the serial number of the enter event
	Serial uint32
	// Tablet is the the tablet the pad is attached to
	Tablet *ZwpTabletV2
	// Surface is the surface the pad is focused on
	Surface *Surface
}

// ZwpTabletPadV2LeaveEvent is the leave event
type ZwpTabletPadV2LeaveEvent struct {
	// Serial is the serial number of the leave event
	Serial uint32
	// Surface is the surface the pad is no longer focused on
	Surface *Surface
}

// ZwpTabletPadV2RemovedEvent is the pad removed event
type ZwpTabletPadV2RemovedEvent struct {
}

// ZwpTabletPadV2GroupHandler is the handler interface for ZwpTabletPadV2GroupEvent
type ZwpTabletPadV2GroupHandler interface {
	HandleZwpTabletPadV2Group(ZwpTabletPadV2GroupEvent)
}

// AddGroupHandler adds the Group handler
func (p *ZwpTabletPadV2) AddGroupHandler(h ZwpTabletPadV2GroupHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletPadV2Groups[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveGroupHandler removes the Group handler
func (p *ZwpTabletPadV2) RemoveGroupHandler(h ZwpTabletPadV2GroupHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletPadV2Groups, h)
}

// ZwpTabletPadV2PathHandler is the handler interface for ZwpTabletPadV2PathEvent
type ZwpTabletPadV2PathHandler interface {
	HandleZwpTabletPadV2Path(ZwpTabletPadV2PathEvent)
}

// AddPathHandler adds the Path handler
func (p *ZwpTabletPadV2) AddPathHandler(h ZwpTabletPadV2PathHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletPadV2Paths[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemovePathHandler removes the Path handler
func (p *ZwpTabletPadV2) RemovePathHandler(h ZwpTabletPadV2PathHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletPadV2Paths, h)
}

// ZwpTabletPadV2ButtonsHandler is the handler interface for ZwpTabletPadV2ButtonsEvent
type ZwpTabletPadV2ButtonsHandler interface {
	HandleZwpTabletPadV2Buttons(ZwpTabletPadV2ButtonsEvent)
}

// AddButtonsHandler adds the Buttons handler
func (p *ZwpTabletPadV2) AddButtonsHandler(h ZwpTabletPadV2ButtonsHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletPadV2Buttonss[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveButtonsHandler removes the Buttons handler
func (p *ZwpTabletPadV2) RemoveButtonsHandler(h ZwpTabletPadV2ButtonsHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletPadV2Buttonss, h)
}

// ZwpTabletPadV2DoneHandler is the handler interface for ZwpTabletPadV2DoneEvent
type ZwpTabletPadV2DoneHandler interface {
	HandleZwpTabletPadV2Done(ZwpTabletPadV2DoneEvent)
}

// AddDoneHandler adds the Done handler
func (p *ZwpTabletPadV2) AddDoneHandler(h ZwpTabletPadV2DoneHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletPadV2Dones[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveDoneHandler removes the Done handler
func (p *ZwpTabletPadV2) RemoveDoneHandler(h ZwpTabletPadV2DoneHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletPadV2Dones, h)
}

// ZwpTabletPadV2ButtonHandler is the handler interface for ZwpTabletPadV2ButtonEvent
type ZwpTabletPadV2ButtonHandler interface {
	HandleZwpTabletPadV2Button(ZwpTabletPadV2ButtonEvent)
}

// AddButtonHandler adds the Button handler
func (p *ZwpTabletPadV2) AddButtonHandler(h ZwpTabletPadV2ButtonHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletPadV2Buttons[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveButtonHandler removes the Button handler
func (p *ZwpTabletPadV2) RemoveButtonHandler(h ZwpTabletPadV2ButtonHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletPadV2Buttons, h)
}

// ZwpTabletPadV2EnterHandler is the handler interface for ZwpTabletPadV2EnterEvent
type ZwpTabletPadV2EnterHandler interface {
	HandleZwpTabletPadV2Enter(ZwpTabletPadV2EnterEvent)
}

// AddEnterHandler adds the Enter handler
func (p *ZwpTabletPadV2) AddEnterHandler(h ZwpTabletPadV2EnterHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletPadV2Enters[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveEnterHandler removes the Enter handler
func (p *ZwpTabletPadV2) RemoveEnterHandler(h ZwpTabletPadV2EnterHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletPadV2Enters, h)
}

// ZwpTabletPadV2LeaveHandler is the handler interface for ZwpTabletPadV2LeaveEvent
type ZwpTabletPadV2LeaveHandler interface {
	HandleZwpTabletPadV2Leave(ZwpTabletPadV2LeaveEvent)
}

// AddLeaveHandler adds the Leave handler
func (p *ZwpTabletPadV2) AddLeaveHandler(h ZwpTabletPadV2LeaveHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletPadV2Leaves[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveLeaveHandler removes the Leave handler
func (p *ZwpTabletPadV2) RemoveLeaveHandler(h ZwpTabletPadV2LeaveHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletPadV2Leaves, h)
}

// ZwpTabletPadV2RemovedHandler is the handler interface for ZwpTabletPadV2RemovedEvent
type ZwpTabletPadV2RemovedHandler interface {
	HandleZwpTabletPadV2Removed(ZwpTabletPadV2RemovedEvent)
}

// AddRemovedHandler adds the Removed handler
func (p *ZwpTabletPadV2) AddRemovedHandler(h ZwpTabletPadV2RemovedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpTabletPadV2Removeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveRemovedHandler removes the Removed handler
func (p *ZwpTabletPadV2) RemoveRemovedHandler(h ZwpTabletPadV2RemovedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwpTabletPadV2Removeds, h)
}
