package wlr

//go:generate sh -c "go run github.com/neurlang/wayland/cmd/wayland-scanner -i wlr-layer-shell-unstable-v1.xml && sed -i '1i // Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.' wlr-layer-shell-unstable-v1.xml.go && gofmt -w wlr-layer-shell-unstable-v1.xml.go"

// The staging and stable protocol names below do not start with wlr_, so
// the scanner derives a package name from their first word; rename the
// clause to keep every generated file in package wlr.
//go:generate sh -c "go run github.com/neurlang/wayland/cmd/wayland-scanner -i viewporter.xml && sed -i '1i // Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.' viewporter.xml.go && sed -i -E 's/^package viewporter$/package wlr/; s|^// Package viewporter implements|// Package wlr implements|' viewporter.xml.go && gofmt -w viewporter.xml.go"
//go:generate sh -c "go run github.com/neurlang/wayland/cmd/wayland-scanner -i fractional-scale-v1.xml && sed -i '1i // Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.' fractional-scale-v1.xml.go && sed -i -E 's/^package fractional$/package wlr/; s|^// Package fractional implements|// Package wlr implements|' fractional-scale-v1.xml.go && gofmt -w fractional-scale-v1.xml.go"
//go:generate sh -c "go run github.com/neurlang/wayland/cmd/wayland-scanner -i primary-selection-unstable-v1.xml && sed -i '1i // Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.' primary-selection-unstable-v1.xml.go && sed -i -E 's/^package wp$/package wlr/; s|^// Package wp implements|// Package wlr implements|' primary-selection-unstable-v1.xml.go && gofmt -w primary-selection-unstable-v1.xml.go"

import (
	"github.com/neurlang/wayland/wl"
	"github.com/neurlang/wayland/xdg"
)

// Aliases the generated bindings in wlr-layer-shell-unstable-v1.xml.go
// reference. Keep in lockstep with the scanner's expectations.
type (
	BaseProxy = wl.BaseProxy
	Context   = wl.Context
	Event     = wl.Event
	Surface   = wl.Surface
	Output    = wl.Output
	// The primary selection device hangs off a seat.
	Seat = wl.Seat
	// Popups created from a layer surface use the xdg_popup type.
	XdgPopup = xdg.Popup
)

// SafeCast forwards wl.SafeCast for the generated event dispatch, which
// references it unqualified (see the text-input-v3 binding upstream).
func SafeCast[T any](p wl.Proxy) T { return wl.SafeCast[T](p) }
