// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: viewporter.xml
// Do not edit

// Package wlr implements the viewporter protocol
package wlr

import ()

// WpErrorViewportExists means the surface already has a viewport object associated
const WpErrorViewportExists = 0

// WpViewportErrorBadValue means negative or zero values in width or height
const WpViewportErrorBadValue = 0

// WpViewportErrorBadSize means destination size is not integer
const WpViewportErrorBadSize = 1

// WpViewportErrorOutOfBuffer means source rectangle extends outside of the content area
const WpViewportErrorOutOfBuffer = 2

// WpViewportErrorNoSurface means the wl_surface was destroyed
const WpViewportErrorNoSurface = 3

// WpViewporter surface cropping and scaling
type WpViewporter struct {
	BaseProxy
}

// NewWpViewporter is a constructor for the WpViewporter object
func NewWpViewporter(ctx *Context) *WpViewporter {
	ret := new(WpViewporter)
	ctx.Register(ret)
	return ret
}

// Destroy unbind from the cropping and scaling interface
func (p *WpViewporter) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// GetViewport extend surface interface for crop and scale
func (p *WpViewporter) GetViewport(Surface *Surface) (*WpViewport, error) {
	retId := NewWpViewport(p.Context())
	return retId, p.Context().SendRequest(p, 1, retId, Surface)
}

// Dispatch dispatches event for object WpViewporter
func (p *WpViewporter) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// WpViewport crop and scale interface to a wl_surface
type WpViewport struct {
	BaseProxy
}

// NewWpViewport is a constructor for the WpViewport object
func NewWpViewport(ctx *Context) *WpViewport {
	ret := new(WpViewport)
	ctx.Register(ret)
	return ret
}

// Destroy remove scaling and cropping from the surface
func (p *WpViewport) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// SetSource set the source rectangle for cropping
func (p *WpViewport) SetSource(X float32, Y float32, Width float32, Height float32) error {

	return p.Context().SendRequest(p, 1, X, Y, Width, Height)
}

// SetDestination set the surface size for scaling
func (p *WpViewport) SetDestination(Width int32, Height int32) error {

	return p.Context().SendRequest(p, 2, Width, Height)
}

// Dispatch dispatches event for object WpViewport
func (p *WpViewport) Dispatch(event *Event) {
	switch event.Opcode {

	}
}
