// This file is autogenerated from: wlr/wlr-layer-shell-unstable-v1.xml
// Do not edit

// Package wlr implements the wlr_layer_shell_unstable_v1 protocol
package wlr

import (
	"sync"
)

// ZwlrLayerShellV1ErrorRole means wl_surface has another role
const ZwlrLayerShellV1ErrorRole = 0

// ZwlrLayerShellV1ErrorInvalidLayer means layer value is invalid
const ZwlrLayerShellV1ErrorInvalidLayer = 1

// ZwlrLayerShellV1ErrorAlreadyConstructed means wl_surface has a buffer attached or committed
const ZwlrLayerShellV1ErrorAlreadyConstructed = 2

// ZwlrLayerShellV1LayerBackground
const ZwlrLayerShellV1LayerBackground = 0

// ZwlrLayerShellV1LayerBottom
const ZwlrLayerShellV1LayerBottom = 1

// ZwlrLayerShellV1LayerTop
const ZwlrLayerShellV1LayerTop = 2

// ZwlrLayerShellV1LayerOverlay
const ZwlrLayerShellV1LayerOverlay = 3

// ZwlrLayerSurfaceV1KeyboardInteractivityNone
const ZwlrLayerSurfaceV1KeyboardInteractivityNone = 0

// ZwlrLayerSurfaceV1KeyboardInteractivityExclusive
const ZwlrLayerSurfaceV1KeyboardInteractivityExclusive = 1

// ZwlrLayerSurfaceV1KeyboardInteractivityOnDemand
const ZwlrLayerSurfaceV1KeyboardInteractivityOnDemand = 2

// ZwlrLayerSurfaceV1ErrorInvalidSurfaceState means provided surface state is invalid
const ZwlrLayerSurfaceV1ErrorInvalidSurfaceState = 0

// ZwlrLayerSurfaceV1ErrorInvalidSize means size is invalid
const ZwlrLayerSurfaceV1ErrorInvalidSize = 1

// ZwlrLayerSurfaceV1ErrorInvalidAnchor means anchor bitfield is invalid
const ZwlrLayerSurfaceV1ErrorInvalidAnchor = 2

// ZwlrLayerSurfaceV1ErrorInvalidKeyboardInteractivity means keyboard interactivity is invalid
const ZwlrLayerSurfaceV1ErrorInvalidKeyboardInteractivity = 3

// ZwlrLayerSurfaceV1AnchorTop means the top edge of the anchor rectangle
const ZwlrLayerSurfaceV1AnchorTop = 1

// ZwlrLayerSurfaceV1AnchorBottom means the bottom edge of the anchor rectangle
const ZwlrLayerSurfaceV1AnchorBottom = 2

// ZwlrLayerSurfaceV1AnchorLeft means the left edge of the anchor rectangle
const ZwlrLayerSurfaceV1AnchorLeft = 4

// ZwlrLayerSurfaceV1AnchorRight means the right edge of the anchor rectangle
const ZwlrLayerSurfaceV1AnchorRight = 8

// ZwlrLayerShellV1 create surfaces that are layers of the desktop
type ZwlrLayerShellV1 struct {
	BaseProxy
}

// NewZwlrLayerShellV1 is a constructor for the ZwlrLayerShellV1 object
func NewZwlrLayerShellV1(ctx *Context) *ZwlrLayerShellV1 {
	ret := new(ZwlrLayerShellV1)
	ctx.Register(ret)
	return ret
}

// GetLayerSurface create a layer_surface from a surface
func (p *ZwlrLayerShellV1) GetLayerSurface(Surface *Surface, Output *Output, Layer uint32, Namespace string) (*ZwlrLayerSurfaceV1, error) {
	retId := NewZwlrLayerSurfaceV1(p.Context())
	return retId, p.Context().SendRequest(p, 0, retId, Surface, Output, Layer, Namespace)
}

// Destroy destroy the layer_shell object
func (p *ZwlrLayerShellV1) Destroy() error {

	return p.Context().SendRequest(p, 1)
}

// Dispatch dispatches event for object ZwlrLayerShellV1
func (p *ZwlrLayerShellV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// ZwlrLayerSurfaceV1 layer metadata interface
type ZwlrLayerSurfaceV1 struct {
	BaseProxy
	mu                                  sync.RWMutex
	privateZwlrLayerSurfaceV1Configures map[ZwlrLayerSurfaceV1ConfigureHandler]struct{}
	privateZwlrLayerSurfaceV1Closeds    map[ZwlrLayerSurfaceV1ClosedHandler]struct{}
}

// initZwlrLayerSurfaceV1 initializes the ZwlrLayerSurfaceV1 object's handler maps
func (ret *ZwlrLayerSurfaceV1) initZwlrLayerSurfaceV1() {
	ret.privateZwlrLayerSurfaceV1Configures = make(map[ZwlrLayerSurfaceV1ConfigureHandler]struct{})
	ret.privateZwlrLayerSurfaceV1Closeds = make(map[ZwlrLayerSurfaceV1ClosedHandler]struct{})
}

// NewZwlrLayerSurfaceV1 is a constructor for the ZwlrLayerSurfaceV1 object
func NewZwlrLayerSurfaceV1(ctx *Context) *ZwlrLayerSurfaceV1 {
	ret := new(ZwlrLayerSurfaceV1)
	ret.initZwlrLayerSurfaceV1()
	ctx.Register(ret)
	return ret
}

// SetSize sets the size of the surface
func (p *ZwlrLayerSurfaceV1) SetSize(Width uint32, Height uint32) error {

	return p.Context().SendRequest(p, 0, Width, Height)
}

// SetAnchor configures the anchor point of the surface
func (p *ZwlrLayerSurfaceV1) SetAnchor(Anchor uint32) error {

	return p.Context().SendRequest(p, 1, Anchor)
}

// SetExclusiveZone configures the exclusive geometry of this surface
func (p *ZwlrLayerSurfaceV1) SetExclusiveZone(Zone int32) error {

	return p.Context().SendRequest(p, 2, Zone)
}

// SetMargin sets a margin from the anchor point
func (p *ZwlrLayerSurfaceV1) SetMargin(Top int32, Right int32, Bottom int32, Left int32) error {

	return p.Context().SendRequest(p, 3, Top, Right, Bottom, Left)
}

// SetKeyboardInteractivity requests keyboard events
func (p *ZwlrLayerSurfaceV1) SetKeyboardInteractivity(KeyboardInteractivity uint32) error {

	return p.Context().SendRequest(p, 4, KeyboardInteractivity)
}

// GetPopup assign this layer_surface as an xdg_popup parent
func (p *ZwlrLayerSurfaceV1) GetPopup(Popup *XdgPopup) error {

	return p.Context().SendRequest(p, 5, Popup)
}

// AckConfigure ack a configure event
func (p *ZwlrLayerSurfaceV1) AckConfigure(Serial uint32) error {

	return p.Context().SendRequest(p, 6, Serial)
}

// Destroy destroy the layer_surface
func (p *ZwlrLayerSurfaceV1) Destroy() error {

	return p.Context().SendRequest(p, 7)
}

// SetLayer change the layer of the surface
func (p *ZwlrLayerSurfaceV1) SetLayer(Layer uint32) error {

	return p.Context().SendRequest(p, 8, Layer)
}

// Dispatch dispatches event for object ZwlrLayerSurfaceV1
func (p *ZwlrLayerSurfaceV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwlrLayerSurfaceV1Configures) > 0 {
			ev := ZwlrLayerSurfaceV1ConfigureEvent{}
			ev.Serial = event.Uint32()
			ev.Width = event.Uint32()
			ev.Height = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwlrLayerSurfaceV1Configures {
				h.HandleZwlrLayerSurfaceV1Configure(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateZwlrLayerSurfaceV1Closeds) > 0 {
			ev := ZwlrLayerSurfaceV1ClosedEvent{}
			p.mu.RLock()
			for h := range p.privateZwlrLayerSurfaceV1Closeds {
				h.HandleZwlrLayerSurfaceV1Closed(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ZwlrLayerSurfaceV1ConfigureEvent is the suggest a surface change
type ZwlrLayerSurfaceV1ConfigureEvent struct {
	// Serial is the
	Serial uint32
	// Width is the
	Width uint32
	// Height is the
	Height uint32
}

// ZwlrLayerSurfaceV1ClosedEvent is the surface should be closed
type ZwlrLayerSurfaceV1ClosedEvent struct {
}

// ZwlrLayerSurfaceV1ConfigureHandler is the handler interface for ZwlrLayerSurfaceV1ConfigureEvent
type ZwlrLayerSurfaceV1ConfigureHandler interface {
	HandleZwlrLayerSurfaceV1Configure(ZwlrLayerSurfaceV1ConfigureEvent)
}

// AddConfigureHandler adds the Configure handler
func (p *ZwlrLayerSurfaceV1) AddConfigureHandler(h ZwlrLayerSurfaceV1ConfigureHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwlrLayerSurfaceV1Configures[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveConfigureHandler removes the Configure handler
func (p *ZwlrLayerSurfaceV1) RemoveConfigureHandler(h ZwlrLayerSurfaceV1ConfigureHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwlrLayerSurfaceV1Configures, h)
}

// ZwlrLayerSurfaceV1ClosedHandler is the handler interface for ZwlrLayerSurfaceV1ClosedEvent
type ZwlrLayerSurfaceV1ClosedHandler interface {
	HandleZwlrLayerSurfaceV1Closed(ZwlrLayerSurfaceV1ClosedEvent)
}

// AddClosedHandler adds the Closed handler
func (p *ZwlrLayerSurfaceV1) AddClosedHandler(h ZwlrLayerSurfaceV1ClosedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwlrLayerSurfaceV1Closeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveClosedHandler removes the Closed handler
func (p *ZwlrLayerSurfaceV1) RemoveClosedHandler(h ZwlrLayerSurfaceV1ClosedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwlrLayerSurfaceV1Closeds, h)
}
