// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: wlr-screencopy-unstable-v1.xml
// Do not edit

// Package wlr implements the wlr_screencopy_unstable_v1 protocol
package wlr

import (
	"sync"
)

// ZwlrScreencopyFrameV1ErrorAlreadyUsed means the object has already been used to copy a wl_buffer
const ZwlrScreencopyFrameV1ErrorAlreadyUsed = 0

// ZwlrScreencopyFrameV1ErrorInvalidBuffer means buffer attributes are invalid
const ZwlrScreencopyFrameV1ErrorInvalidBuffer = 1

// ZwlrScreencopyFrameV1FlagsYInvert means contents are y-inverted
const ZwlrScreencopyFrameV1FlagsYInvert = 1

// ZwlrScreencopyManagerV1 manager to inform clients and begin capturing
type ZwlrScreencopyManagerV1 struct {
	BaseProxy
}

// NewZwlrScreencopyManagerV1 is a constructor for the ZwlrScreencopyManagerV1 object
func NewZwlrScreencopyManagerV1(ctx *Context) *ZwlrScreencopyManagerV1 {
	ret := new(ZwlrScreencopyManagerV1)
	ctx.Register(ret)
	return ret
}

// CaptureOutput capture an output
func (p *ZwlrScreencopyManagerV1) CaptureOutput(OverlayCursor int32, Output *Output) (*ZwlrScreencopyFrameV1, error) {
	retFrame := NewZwlrScreencopyFrameV1(p.Context())
	return retFrame, p.Context().SendRequest(p, 0, retFrame, OverlayCursor, Output)
}

// CaptureOutputRegion capture an output's region
func (p *ZwlrScreencopyManagerV1) CaptureOutputRegion(OverlayCursor int32, Output *Output, X int32, Y int32, Width int32, Height int32) (*ZwlrScreencopyFrameV1, error) {
	retFrame := NewZwlrScreencopyFrameV1(p.Context())
	return retFrame, p.Context().SendRequest(p, 1, retFrame, OverlayCursor, Output, X, Y, Width, Height)
}

// Destroy destroy the manager
func (p *ZwlrScreencopyManagerV1) Destroy() error {

	return p.Context().SendRequest(p, 2)
}

// Dispatch dispatches event for object ZwlrScreencopyManagerV1
func (p *ZwlrScreencopyManagerV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// ZwlrScreencopyFrameV1 a frame ready for copy
type ZwlrScreencopyFrameV1 struct {
	BaseProxy
	mu                                       sync.RWMutex
	privateZwlrScreencopyFrameV1Buffers      map[ZwlrScreencopyFrameV1BufferHandler]struct{}
	privateZwlrScreencopyFrameV1Flagss       map[ZwlrScreencopyFrameV1FlagsHandler]struct{}
	privateZwlrScreencopyFrameV1Readys       map[ZwlrScreencopyFrameV1ReadyHandler]struct{}
	privateZwlrScreencopyFrameV1Faileds      map[ZwlrScreencopyFrameV1FailedHandler]struct{}
	privateZwlrScreencopyFrameV1Damages      map[ZwlrScreencopyFrameV1DamageHandler]struct{}
	privateZwlrScreencopyFrameV1LinuxDmabufs map[ZwlrScreencopyFrameV1LinuxDmabufHandler]struct{}
	privateZwlrScreencopyFrameV1BufferDones  map[ZwlrScreencopyFrameV1BufferDoneHandler]struct{}
}

// initZwlrScreencopyFrameV1 initializes the ZwlrScreencopyFrameV1 object's handler maps
func (ret *ZwlrScreencopyFrameV1) initZwlrScreencopyFrameV1() {
	ret.privateZwlrScreencopyFrameV1Buffers = make(map[ZwlrScreencopyFrameV1BufferHandler]struct{})
	ret.privateZwlrScreencopyFrameV1Flagss = make(map[ZwlrScreencopyFrameV1FlagsHandler]struct{})
	ret.privateZwlrScreencopyFrameV1Readys = make(map[ZwlrScreencopyFrameV1ReadyHandler]struct{})
	ret.privateZwlrScreencopyFrameV1Faileds = make(map[ZwlrScreencopyFrameV1FailedHandler]struct{})
	ret.privateZwlrScreencopyFrameV1Damages = make(map[ZwlrScreencopyFrameV1DamageHandler]struct{})
	ret.privateZwlrScreencopyFrameV1LinuxDmabufs = make(map[ZwlrScreencopyFrameV1LinuxDmabufHandler]struct{})
	ret.privateZwlrScreencopyFrameV1BufferDones = make(map[ZwlrScreencopyFrameV1BufferDoneHandler]struct{})
}

// NewZwlrScreencopyFrameV1 is a constructor for the ZwlrScreencopyFrameV1 object
func NewZwlrScreencopyFrameV1(ctx *Context) *ZwlrScreencopyFrameV1 {
	ret := new(ZwlrScreencopyFrameV1)
	ret.initZwlrScreencopyFrameV1()
	ctx.Register(ret)
	return ret
}

// Copy copy the frame
func (p *ZwlrScreencopyFrameV1) Copy(Buffer *Buffer) error {

	return p.Context().SendRequest(p, 0, Buffer)
}

// Destroy delete this object, used or not
func (p *ZwlrScreencopyFrameV1) Destroy() error {

	return p.Context().SendRequest(p, 1)
}

// CopyWithDamage copy the frame when it's damaged
func (p *ZwlrScreencopyFrameV1) CopyWithDamage(Buffer *Buffer) error {

	return p.Context().SendRequest(p, 2, Buffer)
}

// Dispatch dispatches event for object ZwlrScreencopyFrameV1
func (p *ZwlrScreencopyFrameV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwlrScreencopyFrameV1Buffers) > 0 {
			ev := ZwlrScreencopyFrameV1BufferEvent{}
			ev.Format = event.Uint32()
			ev.Width = event.Uint32()
			ev.Height = event.Uint32()
			ev.Stride = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwlrScreencopyFrameV1Buffers {
				h.HandleZwlrScreencopyFrameV1Buffer(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateZwlrScreencopyFrameV1Flagss) > 0 {
			ev := ZwlrScreencopyFrameV1FlagsEvent{}
			ev.Flags = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwlrScreencopyFrameV1Flagss {
				h.HandleZwlrScreencopyFrameV1Flags(ev)
			}
			p.mu.RUnlock()
		}
	case 2:
		if len(p.privateZwlrScreencopyFrameV1Readys) > 0 {
			ev := ZwlrScreencopyFrameV1ReadyEvent{}
			ev.TvSecHi = event.Uint32()
			ev.TvSecLo = event.Uint32()
			ev.TvNsec = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwlrScreencopyFrameV1Readys {
				h.HandleZwlrScreencopyFrameV1Ready(ev)
			}
			p.mu.RUnlock()
		}
	case 3:
		if len(p.privateZwlrScreencopyFrameV1Faileds) > 0 {
			ev := ZwlrScreencopyFrameV1FailedEvent{}
			p.mu.RLock()
			for h := range p.privateZwlrScreencopyFrameV1Faileds {
				h.HandleZwlrScreencopyFrameV1Failed(ev)
			}
			p.mu.RUnlock()
		}
	case 4:
		if len(p.privateZwlrScreencopyFrameV1Damages) > 0 {
			ev := ZwlrScreencopyFrameV1DamageEvent{}
			ev.X = event.Uint32()
			ev.Y = event.Uint32()
			ev.Width = event.Uint32()
			ev.Height = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwlrScreencopyFrameV1Damages {
				h.HandleZwlrScreencopyFrameV1Damage(ev)
			}
			p.mu.RUnlock()
		}
	case 5:
		if len(p.privateZwlrScreencopyFrameV1LinuxDmabufs) > 0 {
			ev := ZwlrScreencopyFrameV1LinuxDmabufEvent{}
			ev.Format = event.Uint32()
			ev.Width = event.Uint32()
			ev.Height = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwlrScreencopyFrameV1LinuxDmabufs {
				h.HandleZwlrScreencopyFrameV1LinuxDmabuf(ev)
			}
			p.mu.RUnlock()
		}
	case 6:
		if len(p.privateZwlrScreencopyFrameV1BufferDones) > 0 {
			ev := ZwlrScreencopyFrameV1BufferDoneEvent{}
			p.mu.RLock()
			for h := range p.privateZwlrScreencopyFrameV1BufferDones {
				h.HandleZwlrScreencopyFrameV1BufferDone(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ZwlrScreencopyFrameV1BufferEvent is the wl_shm buffer information
type ZwlrScreencopyFrameV1BufferEvent struct {
	// Format is the buffer format
	Format uint32
	// Width is the buffer width
	Width uint32
	// Height is the buffer height
	Height uint32
	// Stride is the buffer stride
	Stride uint32
}

// ZwlrScreencopyFrameV1FlagsEvent is the frame flags
type ZwlrScreencopyFrameV1FlagsEvent struct {
	// Flags is the frame flags
	Flags uint32
}

// ZwlrScreencopyFrameV1ReadyEvent is the indicates frame is available for reading
type ZwlrScreencopyFrameV1ReadyEvent struct {
	// TvSecHi is the high 32 bits of the seconds part of the timestamp
	TvSecHi uint32
	// TvSecLo is the low 32 bits of the seconds part of the timestamp
	TvSecLo uint32
	// TvNsec is the nanoseconds part of the timestamp
	TvNsec uint32
}

// ZwlrScreencopyFrameV1FailedEvent is the frame copy failed
type ZwlrScreencopyFrameV1FailedEvent struct {
}

// ZwlrScreencopyFrameV1DamageEvent is the carries the coordinates of the damaged region
type ZwlrScreencopyFrameV1DamageEvent struct {
	// X is the damaged x coordinates
	X uint32
	// Y is the damaged y coordinates
	Y uint32
	// Width is the current width
	Width uint32
	// Height is the current height
	Height uint32
}

// ZwlrScreencopyFrameV1LinuxDmabufEvent is the linux-dmabuf buffer information
type ZwlrScreencopyFrameV1LinuxDmabufEvent struct {
	// Format is the fourcc pixel format
	Format uint32
	// Width is the buffer width
	Width uint32
	// Height is the buffer height
	Height uint32
}

// ZwlrScreencopyFrameV1BufferDoneEvent is the all buffer types reported
type ZwlrScreencopyFrameV1BufferDoneEvent struct {
}

// ZwlrScreencopyFrameV1BufferHandler is the handler interface for ZwlrScreencopyFrameV1BufferEvent
type ZwlrScreencopyFrameV1BufferHandler interface {
	HandleZwlrScreencopyFrameV1Buffer(ZwlrScreencopyFrameV1BufferEvent)
}

// AddBufferHandler adds the Buffer handler
func (p *ZwlrScreencopyFrameV1) AddBufferHandler(h ZwlrScreencopyFrameV1BufferHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwlrScreencopyFrameV1Buffers[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveBufferHandler removes the Buffer handler
func (p *ZwlrScreencopyFrameV1) RemoveBufferHandler(h ZwlrScreencopyFrameV1BufferHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwlrScreencopyFrameV1Buffers, h)
}

// ZwlrScreencopyFrameV1FlagsHandler is the handler interface for ZwlrScreencopyFrameV1FlagsEvent
type ZwlrScreencopyFrameV1FlagsHandler interface {
	HandleZwlrScreencopyFrameV1Flags(ZwlrScreencopyFrameV1FlagsEvent)
}

// AddFlagsHandler adds the Flags handler
func (p *ZwlrScreencopyFrameV1) AddFlagsHandler(h ZwlrScreencopyFrameV1FlagsHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwlrScreencopyFrameV1Flagss[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveFlagsHandler removes the Flags handler
func (p *ZwlrScreencopyFrameV1) RemoveFlagsHandler(h ZwlrScreencopyFrameV1FlagsHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwlrScreencopyFrameV1Flagss, h)
}

// ZwlrScreencopyFrameV1ReadyHandler is the handler interface for ZwlrScreencopyFrameV1ReadyEvent
type ZwlrScreencopyFrameV1ReadyHandler interface {
	HandleZwlrScreencopyFrameV1Ready(ZwlrScreencopyFrameV1ReadyEvent)
}

// AddReadyHandler adds the Ready handler
func (p *ZwlrScreencopyFrameV1) AddReadyHandler(h ZwlrScreencopyFrameV1ReadyHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwlrScreencopyFrameV1Readys[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveReadyHandler removes the Ready handler
func (p *ZwlrScreencopyFrameV1) RemoveReadyHandler(h ZwlrScreencopyFrameV1ReadyHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwlrScreencopyFrameV1Readys, h)
}

// ZwlrScreencopyFrameV1FailedHandler is the handler interface for ZwlrScreencopyFrameV1FailedEvent
type ZwlrScreencopyFrameV1FailedHandler interface {
	HandleZwlrScreencopyFrameV1Failed(ZwlrScreencopyFrameV1FailedEvent)
}

// AddFailedHandler adds the Failed handler
func (p *ZwlrScreencopyFrameV1) AddFailedHandler(h ZwlrScreencopyFrameV1FailedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwlrScreencopyFrameV1Faileds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveFailedHandler removes the Failed handler
func (p *ZwlrScreencopyFrameV1) RemoveFailedHandler(h ZwlrScreencopyFrameV1FailedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwlrScreencopyFrameV1Faileds, h)
}

// ZwlrScreencopyFrameV1DamageHandler is the handler interface for ZwlrScreencopyFrameV1DamageEvent
type ZwlrScreencopyFrameV1DamageHandler interface {
	HandleZwlrScreencopyFrameV1Damage(ZwlrScreencopyFrameV1DamageEvent)
}

// AddDamageHandler adds the Damage handler
func (p *ZwlrScreencopyFrameV1) AddDamageHandler(h ZwlrScreencopyFrameV1DamageHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwlrScreencopyFrameV1Damages[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveDamageHandler removes the Damage handler
func (p *ZwlrScreencopyFrameV1) RemoveDamageHandler(h ZwlrScreencopyFrameV1DamageHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwlrScreencopyFrameV1Damages, h)
}

// ZwlrScreencopyFrameV1LinuxDmabufHandler is the handler interface for ZwlrScreencopyFrameV1LinuxDmabufEvent
type ZwlrScreencopyFrameV1LinuxDmabufHandler interface {
	HandleZwlrScreencopyFrameV1LinuxDmabuf(ZwlrScreencopyFrameV1LinuxDmabufEvent)
}

// AddLinuxDmabufHandler adds the LinuxDmabuf handler
func (p *ZwlrScreencopyFrameV1) AddLinuxDmabufHandler(h ZwlrScreencopyFrameV1LinuxDmabufHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwlrScreencopyFrameV1LinuxDmabufs[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveLinuxDmabufHandler removes the LinuxDmabuf handler
func (p *ZwlrScreencopyFrameV1) RemoveLinuxDmabufHandler(h ZwlrScreencopyFrameV1LinuxDmabufHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwlrScreencopyFrameV1LinuxDmabufs, h)
}

// ZwlrScreencopyFrameV1BufferDoneHandler is the handler interface for ZwlrScreencopyFrameV1BufferDoneEvent
type ZwlrScreencopyFrameV1BufferDoneHandler interface {
	HandleZwlrScreencopyFrameV1BufferDone(ZwlrScreencopyFrameV1BufferDoneEvent)
}

// AddBufferDoneHandler adds the BufferDone handler
func (p *ZwlrScreencopyFrameV1) AddBufferDoneHandler(h ZwlrScreencopyFrameV1BufferDoneHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwlrScreencopyFrameV1BufferDones[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveBufferDoneHandler removes the BufferDone handler
func (p *ZwlrScreencopyFrameV1) RemoveBufferDoneHandler(h ZwlrScreencopyFrameV1BufferDoneHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwlrScreencopyFrameV1BufferDones, h)
}
