// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: wlr-foreign-toplevel-management-unstable-v1.xml
// Do not edit

// Package wlr implements the wlr_foreign_toplevel_management_unstable_v1 protocol
package wlr

import (
	"sync"
)

// ZwlrForeignToplevelHandleV1StateMaximized means the toplevel is maximized
const ZwlrForeignToplevelHandleV1StateMaximized = 0

// ZwlrForeignToplevelHandleV1StateMinimized means the toplevel is minimized
const ZwlrForeignToplevelHandleV1StateMinimized = 1

// ZwlrForeignToplevelHandleV1StateActivated means the toplevel is active
const ZwlrForeignToplevelHandleV1StateActivated = 2

// ZwlrForeignToplevelHandleV1StateFullscreen means the toplevel is fullscreen
const ZwlrForeignToplevelHandleV1StateFullscreen = 3

// ZwlrForeignToplevelHandleV1ErrorInvalidRectangle means the provided rectangle is invalid
const ZwlrForeignToplevelHandleV1ErrorInvalidRectangle = 0

// ZwlrForeignToplevelManagerV1 list and control opened apps
type ZwlrForeignToplevelManagerV1 struct {
	BaseProxy
	mu                                           sync.RWMutex
	privateZwlrForeignToplevelManagerV1Toplevels map[ZwlrForeignToplevelManagerV1ToplevelHandler]struct{}
	privateZwlrForeignToplevelManagerV1Finisheds map[ZwlrForeignToplevelManagerV1FinishedHandler]struct{}
}

// initZwlrForeignToplevelManagerV1 initializes the ZwlrForeignToplevelManagerV1 object's handler maps
func (ret *ZwlrForeignToplevelManagerV1) initZwlrForeignToplevelManagerV1() {
	ret.privateZwlrForeignToplevelManagerV1Toplevels = make(map[ZwlrForeignToplevelManagerV1ToplevelHandler]struct{})
	ret.privateZwlrForeignToplevelManagerV1Finisheds = make(map[ZwlrForeignToplevelManagerV1FinishedHandler]struct{})
}

// NewZwlrForeignToplevelManagerV1 is a constructor for the ZwlrForeignToplevelManagerV1 object
func NewZwlrForeignToplevelManagerV1(ctx *Context) *ZwlrForeignToplevelManagerV1 {
	ret := new(ZwlrForeignToplevelManagerV1)
	ret.initZwlrForeignToplevelManagerV1()
	ctx.Register(ret)
	return ret
}

// Stop stop sending events
func (p *ZwlrForeignToplevelManagerV1) Stop() error {

	return p.Context().SendRequest(p, 0)
}

// Dispatch dispatches event for object ZwlrForeignToplevelManagerV1
func (p *ZwlrForeignToplevelManagerV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwlrForeignToplevelManagerV1Toplevels) > 0 {
			ev := ZwlrForeignToplevelManagerV1ToplevelEvent{}
			ev.Toplevel = func() *ZwlrForeignToplevelHandleV1 {
				ret := new(ZwlrForeignToplevelHandleV1)
				ret.initZwlrForeignToplevelHandleV1()
				return event.NewId(ret, p.Context()).(*ZwlrForeignToplevelHandleV1)
			}()
			p.mu.RLock()
			for h := range p.privateZwlrForeignToplevelManagerV1Toplevels {
				h.HandleZwlrForeignToplevelManagerV1Toplevel(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateZwlrForeignToplevelManagerV1Finisheds) > 0 {
			ev := ZwlrForeignToplevelManagerV1FinishedEvent{}
			p.mu.RLock()
			for h := range p.privateZwlrForeignToplevelManagerV1Finisheds {
				h.HandleZwlrForeignToplevelManagerV1Finished(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ZwlrForeignToplevelManagerV1ToplevelEvent is the a toplevel has been created
type ZwlrForeignToplevelManagerV1ToplevelEvent struct {
	// Toplevel is the
	Toplevel *ZwlrForeignToplevelHandleV1
}

// ZwlrForeignToplevelManagerV1FinishedEvent is the the compositor has finished with the toplevel manager
type ZwlrForeignToplevelManagerV1FinishedEvent struct {
}

// ZwlrForeignToplevelManagerV1ToplevelHandler is the handler interface for ZwlrForeignToplevelManagerV1ToplevelEvent
type ZwlrForeignToplevelManagerV1ToplevelHandler interface {
	HandleZwlrForeignToplevelManagerV1Toplevel(ZwlrForeignToplevelManagerV1ToplevelEvent)
}

// AddToplevelHandler adds the Toplevel handler
func (p *ZwlrForeignToplevelManagerV1) AddToplevelHandler(h ZwlrForeignToplevelManagerV1ToplevelHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwlrForeignToplevelManagerV1Toplevels[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveToplevelHandler removes the Toplevel handler
func (p *ZwlrForeignToplevelManagerV1) RemoveToplevelHandler(h ZwlrForeignToplevelManagerV1ToplevelHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwlrForeignToplevelManagerV1Toplevels, h)
}

// ZwlrForeignToplevelManagerV1FinishedHandler is the handler interface for ZwlrForeignToplevelManagerV1FinishedEvent
type ZwlrForeignToplevelManagerV1FinishedHandler interface {
	HandleZwlrForeignToplevelManagerV1Finished(ZwlrForeignToplevelManagerV1FinishedEvent)
}

// AddFinishedHandler adds the Finished handler
func (p *ZwlrForeignToplevelManagerV1) AddFinishedHandler(h ZwlrForeignToplevelManagerV1FinishedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwlrForeignToplevelManagerV1Finisheds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveFinishedHandler removes the Finished handler
func (p *ZwlrForeignToplevelManagerV1) RemoveFinishedHandler(h ZwlrForeignToplevelManagerV1FinishedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwlrForeignToplevelManagerV1Finisheds, h)
}

// ZwlrForeignToplevelHandleV1 an opened toplevel
type ZwlrForeignToplevelHandleV1 struct {
	BaseProxy
	mu                                             sync.RWMutex
	privateZwlrForeignToplevelHandleV1Titles       map[ZwlrForeignToplevelHandleV1TitleHandler]struct{}
	privateZwlrForeignToplevelHandleV1AppIds       map[ZwlrForeignToplevelHandleV1AppIdHandler]struct{}
	privateZwlrForeignToplevelHandleV1OutputEnters map[ZwlrForeignToplevelHandleV1OutputEnterHandler]struct{}
	privateZwlrForeignToplevelHandleV1OutputLeaves map[ZwlrForeignToplevelHandleV1OutputLeaveHandler]struct{}
	privateZwlrForeignToplevelHandleV1States       map[ZwlrForeignToplevelHandleV1StateHandler]struct{}
	privateZwlrForeignToplevelHandleV1Dones        map[ZwlrForeignToplevelHandleV1DoneHandler]struct{}
	privateZwlrForeignToplevelHandleV1Closeds      map[ZwlrForeignToplevelHandleV1ClosedHandler]struct{}
	privateZwlrForeignToplevelHandleV1Parents      map[ZwlrForeignToplevelHandleV1ParentHandler]struct{}
}

// initZwlrForeignToplevelHandleV1 initializes the ZwlrForeignToplevelHandleV1 object's handler maps
func (ret *ZwlrForeignToplevelHandleV1) initZwlrForeignToplevelHandleV1() {
	ret.privateZwlrForeignToplevelHandleV1Titles = make(map[ZwlrForeignToplevelHandleV1TitleHandler]struct{})
	ret.privateZwlrForeignToplevelHandleV1AppIds = make(map[ZwlrForeignToplevelHandleV1AppIdHandler]struct{})
	ret.privateZwlrForeignToplevelHandleV1OutputEnters = make(map[ZwlrForeignToplevelHandleV1OutputEnterHandler]struct{})
	ret.privateZwlrForeignToplevelHandleV1OutputLeaves = make(map[ZwlrForeignToplevelHandleV1OutputLeaveHandler]struct{})
	ret.privateZwlrForeignToplevelHandleV1States = make(map[ZwlrForeignToplevelHandleV1StateHandler]struct{})
	ret.privateZwlrForeignToplevelHandleV1Dones = make(map[ZwlrForeignToplevelHandleV1DoneHandler]struct{})
	ret.privateZwlrForeignToplevelHandleV1Closeds = make(map[ZwlrForeignToplevelHandleV1ClosedHandler]struct{})
	ret.privateZwlrForeignToplevelHandleV1Parents = make(map[ZwlrForeignToplevelHandleV1ParentHandler]struct{})
}

// NewZwlrForeignToplevelHandleV1 is a constructor for the ZwlrForeignToplevelHandleV1 object
func NewZwlrForeignToplevelHandleV1(ctx *Context) *ZwlrForeignToplevelHandleV1 {
	ret := new(ZwlrForeignToplevelHandleV1)
	ret.initZwlrForeignToplevelHandleV1()
	ctx.Register(ret)
	return ret
}

// SetMaximized requests that the toplevel be maximized
func (p *ZwlrForeignToplevelHandleV1) SetMaximized() error {

	return p.Context().SendRequest(p, 0)
}

// UnsetMaximized requests that the toplevel be unmaximized
func (p *ZwlrForeignToplevelHandleV1) UnsetMaximized() error {

	return p.Context().SendRequest(p, 1)
}

// SetMinimized requests that the toplevel be minimized
func (p *ZwlrForeignToplevelHandleV1) SetMinimized() error {

	return p.Context().SendRequest(p, 2)
}

// UnsetMinimized requests that the toplevel be unminimized
func (p *ZwlrForeignToplevelHandleV1) UnsetMinimized() error {

	return p.Context().SendRequest(p, 3)
}

// Activate activate the toplevel
func (p *ZwlrForeignToplevelHandleV1) Activate(Seat *Seat) error {

	return p.Context().SendRequest(p, 4, Seat)
}

// Close request that the toplevel be closed
func (p *ZwlrForeignToplevelHandleV1) Close() error {

	return p.Context().SendRequest(p, 5)
}

// SetRectangle the rectangle which represents the toplevel
func (p *ZwlrForeignToplevelHandleV1) SetRectangle(Surface *Surface, X int32, Y int32, Width int32, Height int32) error {

	return p.Context().SendRequest(p, 6, Surface, X, Y, Width, Height)
}

// Destroy destroy the zwlr_foreign_toplevel_handle_v1 object
func (p *ZwlrForeignToplevelHandleV1) Destroy() error {

	return p.Context().SendRequest(p, 7)
}

// SetFullscreen request that the toplevel be fullscreened
func (p *ZwlrForeignToplevelHandleV1) SetFullscreen(Output *Output) error {

	return p.Context().SendRequest(p, 8, Output)
}

// UnsetFullscreen request that the toplevel be unfullscreened
func (p *ZwlrForeignToplevelHandleV1) UnsetFullscreen() error {

	return p.Context().SendRequest(p, 9)
}

// Dispatch dispatches event for object ZwlrForeignToplevelHandleV1
func (p *ZwlrForeignToplevelHandleV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwlrForeignToplevelHandleV1Titles) > 0 {
			ev := ZwlrForeignToplevelHandleV1TitleEvent{}
			ev.Title = event.String()
			p.mu.RLock()
			for h := range p.privateZwlrForeignToplevelHandleV1Titles {
				h.HandleZwlrForeignToplevelHandleV1Title(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateZwlrForeignToplevelHandleV1AppIds) > 0 {
			ev := ZwlrForeignToplevelHandleV1AppIdEvent{}
			ev.AppId = event.String()
			p.mu.RLock()
			for h := range p.privateZwlrForeignToplevelHandleV1AppIds {
				h.HandleZwlrForeignToplevelHandleV1AppId(ev)
			}
			p.mu.RUnlock()
		}
	case 2:
		if len(p.privateZwlrForeignToplevelHandleV1OutputEnters) > 0 {
			ev := ZwlrForeignToplevelHandleV1OutputEnterEvent{}
			ev.Output = SafeCast[*Output](event.Proxy(p.Context()))
			p.mu.RLock()
			for h := range p.privateZwlrForeignToplevelHandleV1OutputEnters {
				h.HandleZwlrForeignToplevelHandleV1OutputEnter(ev)
			}
			p.mu.RUnlock()
		}
	case 3:
		if len(p.privateZwlrForeignToplevelHandleV1OutputLeaves) > 0 {
			ev := ZwlrForeignToplevelHandleV1OutputLeaveEvent{}
			ev.Output = SafeCast[*Output](event.Proxy(p.Context()))
			p.mu.RLock()
			for h := range p.privateZwlrForeignToplevelHandleV1OutputLeaves {
				h.HandleZwlrForeignToplevelHandleV1OutputLeave(ev)
			}
			p.mu.RUnlock()
		}
	case 4:
		if len(p.privateZwlrForeignToplevelHandleV1States) > 0 {
			ev := ZwlrForeignToplevelHandleV1StateEvent{}
			ev.State = event.Array()
			p.mu.RLock()
			for h := range p.privateZwlrForeignToplevelHandleV1States {
				h.HandleZwlrForeignToplevelHandleV1State(ev)
			}
			p.mu.RUnlock()
		}
	case 5:
		if len(p.privateZwlrForeignToplevelHandleV1Dones) > 0 {
			ev := ZwlrForeignToplevelHandleV1DoneEvent{}
			p.mu.RLock()
			for h := range p.privateZwlrForeignToplevelHandleV1Dones {
				h.HandleZwlrForeignToplevelHandleV1Done(ev)
			}
			p.mu.RUnlock()
		}
	case 6:
		if len(p.privateZwlrForeignToplevelHandleV1Closeds) > 0 {
			ev := ZwlrForeignToplevelHandleV1ClosedEvent{}
			p.mu.RLock()
			for h := range p.privateZwlrForeignToplevelHandleV1Closeds {
				h.HandleZwlrForeignToplevelHandleV1Closed(ev)
			}
			p.mu.RUnlock()
		}
	case 7:
		if len(p.privateZwlrForeignToplevelHandleV1Parents) > 0 {
			ev := ZwlrForeignToplevelHandleV1ParentEvent{}
			ev.Parent = SafeCast[*ZwlrForeignToplevelHandleV1](event.Proxy(p.Context()))
			p.mu.RLock()
			for h := range p.privateZwlrForeignToplevelHandleV1Parents {
				h.HandleZwlrForeignToplevelHandleV1Parent(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ZwlrForeignToplevelHandleV1TitleEvent is the title change
type ZwlrForeignToplevelHandleV1TitleEvent struct {
	// Title is the
	Title string
}

// ZwlrForeignToplevelHandleV1AppIdEvent is the app-id change
type ZwlrForeignToplevelHandleV1AppIdEvent struct {
	// AppId is the
	AppId string
}

// ZwlrForeignToplevelHandleV1OutputEnterEvent is the toplevel entered an output
type ZwlrForeignToplevelHandleV1OutputEnterEvent struct {
	// Output is the
	Output *Output
}

// ZwlrForeignToplevelHandleV1OutputLeaveEvent is the toplevel left an output
type ZwlrForeignToplevelHandleV1OutputLeaveEvent struct {
	// Output is the
	Output *Output
}

// ZwlrForeignToplevelHandleV1StateEvent is the the toplevel state changed
type ZwlrForeignToplevelHandleV1StateEvent struct {
	// State is the
	State []int32
}

// ZwlrForeignToplevelHandleV1DoneEvent is the all information about the toplevel has been sent
type ZwlrForeignToplevelHandleV1DoneEvent struct {
}

// ZwlrForeignToplevelHandleV1ClosedEvent is the this toplevel has been destroyed
type ZwlrForeignToplevelHandleV1ClosedEvent struct {
}

// ZwlrForeignToplevelHandleV1ParentEvent is the parent change
type ZwlrForeignToplevelHandleV1ParentEvent struct {
	// Parent is the
	Parent *ZwlrForeignToplevelHandleV1
}

// ZwlrForeignToplevelHandleV1TitleHandler is the handler interface for ZwlrForeignToplevelHandleV1TitleEvent
type ZwlrForeignToplevelHandleV1TitleHandler interface {
	HandleZwlrForeignToplevelHandleV1Title(ZwlrForeignToplevelHandleV1TitleEvent)
}

// AddTitleHandler adds the Title handler
func (p *ZwlrForeignToplevelHandleV1) AddTitleHandler(h ZwlrForeignToplevelHandleV1TitleHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwlrForeignToplevelHandleV1Titles[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveTitleHandler removes the Title handler
func (p *ZwlrForeignToplevelHandleV1) RemoveTitleHandler(h ZwlrForeignToplevelHandleV1TitleHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwlrForeignToplevelHandleV1Titles, h)
}

// ZwlrForeignToplevelHandleV1AppIdHandler is the handler interface for ZwlrForeignToplevelHandleV1AppIdEvent
type ZwlrForeignToplevelHandleV1AppIdHandler interface {
	HandleZwlrForeignToplevelHandleV1AppId(ZwlrForeignToplevelHandleV1AppIdEvent)
}

// AddAppIdHandler adds the AppId handler
func (p *ZwlrForeignToplevelHandleV1) AddAppIdHandler(h ZwlrForeignToplevelHandleV1AppIdHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwlrForeignToplevelHandleV1AppIds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveAppIdHandler removes the AppId handler
func (p *ZwlrForeignToplevelHandleV1) RemoveAppIdHandler(h ZwlrForeignToplevelHandleV1AppIdHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwlrForeignToplevelHandleV1AppIds, h)
}

// ZwlrForeignToplevelHandleV1OutputEnterHandler is the handler interface for ZwlrForeignToplevelHandleV1OutputEnterEvent
type ZwlrForeignToplevelHandleV1OutputEnterHandler interface {
	HandleZwlrForeignToplevelHandleV1OutputEnter(ZwlrForeignToplevelHandleV1OutputEnterEvent)
}

// AddOutputEnterHandler adds the OutputEnter handler
func (p *ZwlrForeignToplevelHandleV1) AddOutputEnterHandler(h ZwlrForeignToplevelHandleV1OutputEnterHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwlrForeignToplevelHandleV1OutputEnters[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveOutputEnterHandler removes the OutputEnter handler
func (p *ZwlrForeignToplevelHandleV1) RemoveOutputEnterHandler(h ZwlrForeignToplevelHandleV1OutputEnterHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwlrForeignToplevelHandleV1OutputEnters, h)
}

// ZwlrForeignToplevelHandleV1OutputLeaveHandler is the handler interface for ZwlrForeignToplevelHandleV1OutputLeaveEvent
type ZwlrForeignToplevelHandleV1OutputLeaveHandler interface {
	HandleZwlrForeignToplevelHandleV1OutputLeave(ZwlrForeignToplevelHandleV1OutputLeaveEvent)
}

// AddOutputLeaveHandler adds the OutputLeave handler
func (p *ZwlrForeignToplevelHandleV1) AddOutputLeaveHandler(h ZwlrForeignToplevelHandleV1OutputLeaveHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwlrForeignToplevelHandleV1OutputLeaves[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveOutputLeaveHandler removes the OutputLeave handler
func (p *ZwlrForeignToplevelHandleV1) RemoveOutputLeaveHandler(h ZwlrForeignToplevelHandleV1OutputLeaveHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwlrForeignToplevelHandleV1OutputLeaves, h)
}

// ZwlrForeignToplevelHandleV1StateHandler is the handler interface for ZwlrForeignToplevelHandleV1StateEvent
type ZwlrForeignToplevelHandleV1StateHandler interface {
	HandleZwlrForeignToplevelHandleV1State(ZwlrForeignToplevelHandleV1StateEvent)
}

// AddStateHandler adds the State handler
func (p *ZwlrForeignToplevelHandleV1) AddStateHandler(h ZwlrForeignToplevelHandleV1StateHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwlrForeignToplevelHandleV1States[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveStateHandler removes the State handler
func (p *ZwlrForeignToplevelHandleV1) RemoveStateHandler(h ZwlrForeignToplevelHandleV1StateHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwlrForeignToplevelHandleV1States, h)
}

// ZwlrForeignToplevelHandleV1DoneHandler is the handler interface for ZwlrForeignToplevelHandleV1DoneEvent
type ZwlrForeignToplevelHandleV1DoneHandler interface {
	HandleZwlrForeignToplevelHandleV1Done(ZwlrForeignToplevelHandleV1DoneEvent)
}

// AddDoneHandler adds the Done handler
func (p *ZwlrForeignToplevelHandleV1) AddDoneHandler(h ZwlrForeignToplevelHandleV1DoneHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwlrForeignToplevelHandleV1Dones[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveDoneHandler removes the Done handler
func (p *ZwlrForeignToplevelHandleV1) RemoveDoneHandler(h ZwlrForeignToplevelHandleV1DoneHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwlrForeignToplevelHandleV1Dones, h)
}

// ZwlrForeignToplevelHandleV1ClosedHandler is the handler interface for ZwlrForeignToplevelHandleV1ClosedEvent
type ZwlrForeignToplevelHandleV1ClosedHandler interface {
	HandleZwlrForeignToplevelHandleV1Closed(ZwlrForeignToplevelHandleV1ClosedEvent)
}

// AddClosedHandler adds the Closed handler
func (p *ZwlrForeignToplevelHandleV1) AddClosedHandler(h ZwlrForeignToplevelHandleV1ClosedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwlrForeignToplevelHandleV1Closeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveClosedHandler removes the Closed handler
func (p *ZwlrForeignToplevelHandleV1) RemoveClosedHandler(h ZwlrForeignToplevelHandleV1ClosedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwlrForeignToplevelHandleV1Closeds, h)
}

// ZwlrForeignToplevelHandleV1ParentHandler is the handler interface for ZwlrForeignToplevelHandleV1ParentEvent
type ZwlrForeignToplevelHandleV1ParentHandler interface {
	HandleZwlrForeignToplevelHandleV1Parent(ZwlrForeignToplevelHandleV1ParentEvent)
}

// AddParentHandler adds the Parent handler
func (p *ZwlrForeignToplevelHandleV1) AddParentHandler(h ZwlrForeignToplevelHandleV1ParentHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwlrForeignToplevelHandleV1Parents[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveParentHandler removes the Parent handler
func (p *ZwlrForeignToplevelHandleV1) RemoveParentHandler(h ZwlrForeignToplevelHandleV1ParentHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwlrForeignToplevelHandleV1Parents, h)
}
