// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: wlr-data-control-unstable-v1.xml
// Do not edit

// Package wlr implements the wlr_data_control_unstable_v1 protocol
package wlr

import (
	"sync"
)

// ZwlrDataControlDeviceV1ErrorUsedSource means source given to set_selection or set_primary_selection was already used before
const ZwlrDataControlDeviceV1ErrorUsedSource = 1

// ZwlrDataControlSourceV1ErrorInvalidOffer means offer sent after wlr_data_control_device.set_selection
const ZwlrDataControlSourceV1ErrorInvalidOffer = 1

// ZwlrDataControlManagerV1 manager to control data devices
type ZwlrDataControlManagerV1 struct {
	BaseProxy
}

// NewZwlrDataControlManagerV1 is a constructor for the ZwlrDataControlManagerV1 object
func NewZwlrDataControlManagerV1(ctx *Context) *ZwlrDataControlManagerV1 {
	ret := new(ZwlrDataControlManagerV1)
	ctx.Register(ret)
	return ret
}

// CreateDataSource create a new data source
func (p *ZwlrDataControlManagerV1) CreateDataSource() (*ZwlrDataControlSourceV1, error) {
	retId := NewZwlrDataControlSourceV1(p.Context())
	return retId, p.Context().SendRequest(p, 0, retId)
}

// GetDataDevice get a data device for a seat
func (p *ZwlrDataControlManagerV1) GetDataDevice(Seat *Seat) (*ZwlrDataControlDeviceV1, error) {
	retId := NewZwlrDataControlDeviceV1(p.Context())
	return retId, p.Context().SendRequest(p, 1, retId, Seat)
}

// Destroy destroy the manager
func (p *ZwlrDataControlManagerV1) Destroy() error {

	return p.Context().SendRequest(p, 2)
}

// Dispatch dispatches event for object ZwlrDataControlManagerV1
func (p *ZwlrDataControlManagerV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// ZwlrDataControlDeviceV1 manage a data device for a seat
type ZwlrDataControlDeviceV1 struct {
	BaseProxy
	mu                                              sync.RWMutex
	privateZwlrDataControlDeviceV1DataOffers        map[ZwlrDataControlDeviceV1DataOfferHandler]struct{}
	privateZwlrDataControlDeviceV1Selections        map[ZwlrDataControlDeviceV1SelectionHandler]struct{}
	privateZwlrDataControlDeviceV1Finisheds         map[ZwlrDataControlDeviceV1FinishedHandler]struct{}
	privateZwlrDataControlDeviceV1PrimarySelections map[ZwlrDataControlDeviceV1PrimarySelectionHandler]struct{}
}

// initZwlrDataControlDeviceV1 initializes the ZwlrDataControlDeviceV1 object's handler maps
func (ret *ZwlrDataControlDeviceV1) initZwlrDataControlDeviceV1() {
	ret.privateZwlrDataControlDeviceV1DataOffers = make(map[ZwlrDataControlDeviceV1DataOfferHandler]struct{})
	ret.privateZwlrDataControlDeviceV1Selections = make(map[ZwlrDataControlDeviceV1SelectionHandler]struct{})
	ret.privateZwlrDataControlDeviceV1Finisheds = make(map[ZwlrDataControlDeviceV1FinishedHandler]struct{})
	ret.privateZwlrDataControlDeviceV1PrimarySelections = make(map[ZwlrDataControlDeviceV1PrimarySelectionHandler]struct{})
}

// NewZwlrDataControlDeviceV1 is a constructor for the ZwlrDataControlDeviceV1 object
func NewZwlrDataControlDeviceV1(ctx *Context) *ZwlrDataControlDeviceV1 {
	ret := new(ZwlrDataControlDeviceV1)
	ret.initZwlrDataControlDeviceV1()
	ctx.Register(ret)
	return ret
}

// SetSelection copy data to the selection
func (p *ZwlrDataControlDeviceV1) SetSelection(Source *ZwlrDataControlSourceV1) error {

	return p.Context().SendRequest(p, 0, Source)
}

// Destroy destroy this data device
func (p *ZwlrDataControlDeviceV1) Destroy() error {

	return p.Context().SendRequest(p, 1)
}

// SetPrimarySelection copy data to the primary selection
func (p *ZwlrDataControlDeviceV1) SetPrimarySelection(Source *ZwlrDataControlSourceV1) error {

	return p.Context().SendRequest(p, 2, Source)
}

// Dispatch dispatches event for object ZwlrDataControlDeviceV1
func (p *ZwlrDataControlDeviceV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwlrDataControlDeviceV1DataOffers) > 0 {
			ev := ZwlrDataControlDeviceV1DataOfferEvent{}
			ev.Id = func() *ZwlrDataControlOfferV1 {
				ret := new(ZwlrDataControlOfferV1)
				ret.initZwlrDataControlOfferV1()
				return event.NewId(ret, p.Context()).(*ZwlrDataControlOfferV1)
			}()
			p.mu.RLock()
			for h := range p.privateZwlrDataControlDeviceV1DataOffers {
				h.HandleZwlrDataControlDeviceV1DataOffer(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateZwlrDataControlDeviceV1Selections) > 0 {
			ev := ZwlrDataControlDeviceV1SelectionEvent{}
			ev.Id = SafeCast[*ZwlrDataControlOfferV1](event.Proxy(p.Context()))
			p.mu.RLock()
			for h := range p.privateZwlrDataControlDeviceV1Selections {
				h.HandleZwlrDataControlDeviceV1Selection(ev)
			}
			p.mu.RUnlock()
		}
	case 2:
		if len(p.privateZwlrDataControlDeviceV1Finisheds) > 0 {
			ev := ZwlrDataControlDeviceV1FinishedEvent{}
			p.mu.RLock()
			for h := range p.privateZwlrDataControlDeviceV1Finisheds {
				h.HandleZwlrDataControlDeviceV1Finished(ev)
			}
			p.mu.RUnlock()
		}
	case 3:
		if len(p.privateZwlrDataControlDeviceV1PrimarySelections) > 0 {
			ev := ZwlrDataControlDeviceV1PrimarySelectionEvent{}
			ev.Id = SafeCast[*ZwlrDataControlOfferV1](event.Proxy(p.Context()))
			p.mu.RLock()
			for h := range p.privateZwlrDataControlDeviceV1PrimarySelections {
				h.HandleZwlrDataControlDeviceV1PrimarySelection(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ZwlrDataControlDeviceV1DataOfferEvent is the introduce a new wlr_data_control_offer
type ZwlrDataControlDeviceV1DataOfferEvent struct {
	// Id is the
	Id *ZwlrDataControlOfferV1
}

// ZwlrDataControlDeviceV1SelectionEvent is the advertise new selection
type ZwlrDataControlDeviceV1SelectionEvent struct {
	// Id is the
	Id *ZwlrDataControlOfferV1
}

// ZwlrDataControlDeviceV1FinishedEvent is the this data control is no longer valid
type ZwlrDataControlDeviceV1FinishedEvent struct {
}

// ZwlrDataControlDeviceV1PrimarySelectionEvent is the advertise new primary selection
type ZwlrDataControlDeviceV1PrimarySelectionEvent struct {
	// Id is the
	Id *ZwlrDataControlOfferV1
}

// ZwlrDataControlDeviceV1DataOfferHandler is the handler interface for ZwlrDataControlDeviceV1DataOfferEvent
type ZwlrDataControlDeviceV1DataOfferHandler interface {
	HandleZwlrDataControlDeviceV1DataOffer(ZwlrDataControlDeviceV1DataOfferEvent)
}

// AddDataOfferHandler adds the DataOffer handler
func (p *ZwlrDataControlDeviceV1) AddDataOfferHandler(h ZwlrDataControlDeviceV1DataOfferHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwlrDataControlDeviceV1DataOffers[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveDataOfferHandler removes the DataOffer handler
func (p *ZwlrDataControlDeviceV1) RemoveDataOfferHandler(h ZwlrDataControlDeviceV1DataOfferHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwlrDataControlDeviceV1DataOffers, h)
}

// ZwlrDataControlDeviceV1SelectionHandler is the handler interface for ZwlrDataControlDeviceV1SelectionEvent
type ZwlrDataControlDeviceV1SelectionHandler interface {
	HandleZwlrDataControlDeviceV1Selection(ZwlrDataControlDeviceV1SelectionEvent)
}

// AddSelectionHandler adds the Selection handler
func (p *ZwlrDataControlDeviceV1) AddSelectionHandler(h ZwlrDataControlDeviceV1SelectionHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwlrDataControlDeviceV1Selections[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveSelectionHandler removes the Selection handler
func (p *ZwlrDataControlDeviceV1) RemoveSelectionHandler(h ZwlrDataControlDeviceV1SelectionHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwlrDataControlDeviceV1Selections, h)
}

// ZwlrDataControlDeviceV1FinishedHandler is the handler interface for ZwlrDataControlDeviceV1FinishedEvent
type ZwlrDataControlDeviceV1FinishedHandler interface {
	HandleZwlrDataControlDeviceV1Finished(ZwlrDataControlDeviceV1FinishedEvent)
}

// AddFinishedHandler adds the Finished handler
func (p *ZwlrDataControlDeviceV1) AddFinishedHandler(h ZwlrDataControlDeviceV1FinishedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwlrDataControlDeviceV1Finisheds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveFinishedHandler removes the Finished handler
func (p *ZwlrDataControlDeviceV1) RemoveFinishedHandler(h ZwlrDataControlDeviceV1FinishedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwlrDataControlDeviceV1Finisheds, h)
}

// ZwlrDataControlDeviceV1PrimarySelectionHandler is the handler interface for ZwlrDataControlDeviceV1PrimarySelectionEvent
type ZwlrDataControlDeviceV1PrimarySelectionHandler interface {
	HandleZwlrDataControlDeviceV1PrimarySelection(ZwlrDataControlDeviceV1PrimarySelectionEvent)
}

// AddPrimarySelectionHandler adds the PrimarySelection handler
func (p *ZwlrDataControlDeviceV1) AddPrimarySelectionHandler(h ZwlrDataControlDeviceV1PrimarySelectionHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwlrDataControlDeviceV1PrimarySelections[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemovePrimarySelectionHandler removes the PrimarySelection handler
func (p *ZwlrDataControlDeviceV1) RemovePrimarySelectionHandler(h ZwlrDataControlDeviceV1PrimarySelectionHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwlrDataControlDeviceV1PrimarySelections, h)
}

// ZwlrDataControlSourceV1 offer to transfer data
type ZwlrDataControlSourceV1 struct {
	BaseProxy
	mu                                       sync.RWMutex
	privateZwlrDataControlSourceV1Sends      map[ZwlrDataControlSourceV1SendHandler]struct{}
	privateZwlrDataControlSourceV1Cancelleds map[ZwlrDataControlSourceV1CancelledHandler]struct{}
}

// initZwlrDataControlSourceV1 initializes the ZwlrDataControlSourceV1 object's handler maps
func (ret *ZwlrDataControlSourceV1) initZwlrDataControlSourceV1() {
	ret.privateZwlrDataControlSourceV1Sends = make(map[ZwlrDataControlSourceV1SendHandler]struct{})
	ret.privateZwlrDataControlSourceV1Cancelleds = make(map[ZwlrDataControlSourceV1CancelledHandler]struct{})
}

// NewZwlrDataControlSourceV1 is a constructor for the ZwlrDataControlSourceV1 object
func NewZwlrDataControlSourceV1(ctx *Context) *ZwlrDataControlSourceV1 {
	ret := new(ZwlrDataControlSourceV1)
	ret.initZwlrDataControlSourceV1()
	ctx.Register(ret)
	return ret
}

// Offer add an offered MIME type
func (p *ZwlrDataControlSourceV1) Offer(MimeType string) error {

	return p.Context().SendRequest(p, 0, MimeType)
}

// Destroy destroy this source
func (p *ZwlrDataControlSourceV1) Destroy() error {

	return p.Context().SendRequest(p, 1)
}

// Dispatch dispatches event for object ZwlrDataControlSourceV1
func (p *ZwlrDataControlSourceV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwlrDataControlSourceV1Sends) > 0 {
			ev := ZwlrDataControlSourceV1SendEvent{}
			ev.MimeType = event.String()
			ev.Fd, ev.FdError = event.FD()
			p.mu.RLock()
			for h := range p.privateZwlrDataControlSourceV1Sends {
				h.HandleZwlrDataControlSourceV1Send(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateZwlrDataControlSourceV1Cancelleds) > 0 {
			ev := ZwlrDataControlSourceV1CancelledEvent{}
			p.mu.RLock()
			for h := range p.privateZwlrDataControlSourceV1Cancelleds {
				h.HandleZwlrDataControlSourceV1Cancelled(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ZwlrDataControlSourceV1SendEvent is the send the data
type ZwlrDataControlSourceV1SendEvent struct {
	// MimeType is the MIME type for the data
	MimeType string
	// Fd is the file descriptor for the data
	Fd uintptr
	// FdError is the file descriptor for the data (error)
	FdError error
}

// ZwlrDataControlSourceV1CancelledEvent is the selection was cancelled
type ZwlrDataControlSourceV1CancelledEvent struct {
}

// ZwlrDataControlSourceV1SendHandler is the handler interface for ZwlrDataControlSourceV1SendEvent
type ZwlrDataControlSourceV1SendHandler interface {
	HandleZwlrDataControlSourceV1Send(ZwlrDataControlSourceV1SendEvent)
}

// AddSendHandler adds the Send handler
func (p *ZwlrDataControlSourceV1) AddSendHandler(h ZwlrDataControlSourceV1SendHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwlrDataControlSourceV1Sends[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveSendHandler removes the Send handler
func (p *ZwlrDataControlSourceV1) RemoveSendHandler(h ZwlrDataControlSourceV1SendHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwlrDataControlSourceV1Sends, h)
}

// ZwlrDataControlSourceV1CancelledHandler is the handler interface for ZwlrDataControlSourceV1CancelledEvent
type ZwlrDataControlSourceV1CancelledHandler interface {
	HandleZwlrDataControlSourceV1Cancelled(ZwlrDataControlSourceV1CancelledEvent)
}

// AddCancelledHandler adds the Cancelled handler
func (p *ZwlrDataControlSourceV1) AddCancelledHandler(h ZwlrDataControlSourceV1CancelledHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwlrDataControlSourceV1Cancelleds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveCancelledHandler removes the Cancelled handler
func (p *ZwlrDataControlSourceV1) RemoveCancelledHandler(h ZwlrDataControlSourceV1CancelledHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwlrDataControlSourceV1Cancelleds, h)
}

// ZwlrDataControlOfferV1 offer to transfer data
type ZwlrDataControlOfferV1 struct {
	BaseProxy
	mu                                  sync.RWMutex
	privateZwlrDataControlOfferV1Offers map[ZwlrDataControlOfferV1OfferHandler]struct{}
}

// initZwlrDataControlOfferV1 initializes the ZwlrDataControlOfferV1 object's handler maps
func (ret *ZwlrDataControlOfferV1) initZwlrDataControlOfferV1() {
	ret.privateZwlrDataControlOfferV1Offers = make(map[ZwlrDataControlOfferV1OfferHandler]struct{})
}

// NewZwlrDataControlOfferV1 is a constructor for the ZwlrDataControlOfferV1 object
func NewZwlrDataControlOfferV1(ctx *Context) *ZwlrDataControlOfferV1 {
	ret := new(ZwlrDataControlOfferV1)
	ret.initZwlrDataControlOfferV1()
	ctx.Register(ret)
	return ret
}

// Receive request that the data is transferred
func (p *ZwlrDataControlOfferV1) Receive(MimeType string, Fd uintptr) error {

	return p.Context().SendRequest(p, 0, MimeType, Fd)
}

// Destroy destroy this offer
func (p *ZwlrDataControlOfferV1) Destroy() error {

	return p.Context().SendRequest(p, 1)
}

// Dispatch dispatches event for object ZwlrDataControlOfferV1
func (p *ZwlrDataControlOfferV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwlrDataControlOfferV1Offers) > 0 {
			ev := ZwlrDataControlOfferV1OfferEvent{}
			ev.MimeType = event.String()
			p.mu.RLock()
			for h := range p.privateZwlrDataControlOfferV1Offers {
				h.HandleZwlrDataControlOfferV1Offer(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ZwlrDataControlOfferV1OfferEvent is the advertise offered MIME type
type ZwlrDataControlOfferV1OfferEvent struct {
	// MimeType is the offered MIME type
	MimeType string
}

// ZwlrDataControlOfferV1OfferHandler is the handler interface for ZwlrDataControlOfferV1OfferEvent
type ZwlrDataControlOfferV1OfferHandler interface {
	HandleZwlrDataControlOfferV1Offer(ZwlrDataControlOfferV1OfferEvent)
}

// AddOfferHandler adds the Offer handler
func (p *ZwlrDataControlOfferV1) AddOfferHandler(h ZwlrDataControlOfferV1OfferHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwlrDataControlOfferV1Offers[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveOfferHandler removes the Offer handler
func (p *ZwlrDataControlOfferV1) RemoveOfferHandler(h ZwlrDataControlOfferV1OfferHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZwlrDataControlOfferV1Offers, h)
}
