// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: xdg-output-unstable-v1.xml
// Do not edit

// Package wlr implements the xdg_output_unstable_v1 protocol
package wlr

import (
	"sync"
)

// ZxdgOutputManagerV1 manage xdg_output objects
type ZxdgOutputManagerV1 struct {
	BaseProxy
}

// NewZxdgOutputManagerV1 is a constructor for the ZxdgOutputManagerV1 object
func NewZxdgOutputManagerV1(ctx *Context) *ZxdgOutputManagerV1 {
	ret := new(ZxdgOutputManagerV1)
	ctx.Register(ret)
	return ret
}

// Destroy destroy the xdg_output_manager object
func (p *ZxdgOutputManagerV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// GetOutput create an xdg output from a wl_output
func (p *ZxdgOutputManagerV1) GetOutput(Output *Output) (*ZxdgOutputV1, error) {
	retId := NewZxdgOutputV1(p.Context())
	return retId, p.Context().SendRequest(p, 1, retId, Output)
}

// Dispatch dispatches event for object ZxdgOutputManagerV1
func (p *ZxdgOutputManagerV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// ZxdgOutputV1 compositor logical output region
type ZxdgOutputV1 struct {
	BaseProxy
	mu                                  sync.RWMutex
	privateZxdgOutputV1LogicalPositions map[ZxdgOutputV1LogicalPositionHandler]struct{}
	privateZxdgOutputV1LogicalSizes     map[ZxdgOutputV1LogicalSizeHandler]struct{}
	privateZxdgOutputV1Dones            map[ZxdgOutputV1DoneHandler]struct{}
	privateZxdgOutputV1Names            map[ZxdgOutputV1NameHandler]struct{}
	privateZxdgOutputV1Descriptions     map[ZxdgOutputV1DescriptionHandler]struct{}
}

// initZxdgOutputV1 initializes the ZxdgOutputV1 object's handler maps
func (ret *ZxdgOutputV1) initZxdgOutputV1() {
	ret.privateZxdgOutputV1LogicalPositions = make(map[ZxdgOutputV1LogicalPositionHandler]struct{})
	ret.privateZxdgOutputV1LogicalSizes = make(map[ZxdgOutputV1LogicalSizeHandler]struct{})
	ret.privateZxdgOutputV1Dones = make(map[ZxdgOutputV1DoneHandler]struct{})
	ret.privateZxdgOutputV1Names = make(map[ZxdgOutputV1NameHandler]struct{})
	ret.privateZxdgOutputV1Descriptions = make(map[ZxdgOutputV1DescriptionHandler]struct{})
}

// NewZxdgOutputV1 is a constructor for the ZxdgOutputV1 object
func NewZxdgOutputV1(ctx *Context) *ZxdgOutputV1 {
	ret := new(ZxdgOutputV1)
	ret.initZxdgOutputV1()
	ctx.Register(ret)
	return ret
}

// Destroy destroy the xdg_output object
func (p *ZxdgOutputV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// Dispatch dispatches event for object ZxdgOutputV1
func (p *ZxdgOutputV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZxdgOutputV1LogicalPositions) > 0 {
			ev := ZxdgOutputV1LogicalPositionEvent{}
			ev.X = event.Int32()
			ev.Y = event.Int32()
			p.mu.RLock()
			for h := range p.privateZxdgOutputV1LogicalPositions {
				h.HandleZxdgOutputV1LogicalPosition(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateZxdgOutputV1LogicalSizes) > 0 {
			ev := ZxdgOutputV1LogicalSizeEvent{}
			ev.Width = event.Int32()
			ev.Height = event.Int32()
			p.mu.RLock()
			for h := range p.privateZxdgOutputV1LogicalSizes {
				h.HandleZxdgOutputV1LogicalSize(ev)
			}
			p.mu.RUnlock()
		}
	case 2:
		if len(p.privateZxdgOutputV1Dones) > 0 {
			ev := ZxdgOutputV1DoneEvent{}
			p.mu.RLock()
			for h := range p.privateZxdgOutputV1Dones {
				h.HandleZxdgOutputV1Done(ev)
			}
			p.mu.RUnlock()
		}
	case 3:
		if len(p.privateZxdgOutputV1Names) > 0 {
			ev := ZxdgOutputV1NameEvent{}
			ev.Name = event.String()
			p.mu.RLock()
			for h := range p.privateZxdgOutputV1Names {
				h.HandleZxdgOutputV1Name(ev)
			}
			p.mu.RUnlock()
		}
	case 4:
		if len(p.privateZxdgOutputV1Descriptions) > 0 {
			ev := ZxdgOutputV1DescriptionEvent{}
			ev.Description = event.String()
			p.mu.RLock()
			for h := range p.privateZxdgOutputV1Descriptions {
				h.HandleZxdgOutputV1Description(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ZxdgOutputV1LogicalPositionEvent is the position of the output within the global compositor space
type ZxdgOutputV1LogicalPositionEvent struct {
	// X is the x position within the global compositor space
	X int32
	// Y is the y position within the global compositor space
	Y int32
}

// ZxdgOutputV1LogicalSizeEvent is the size of the output in the global compositor space
type ZxdgOutputV1LogicalSizeEvent struct {
	// Width is the width in global compositor space
	Width int32
	// Height is the height in global compositor space
	Height int32
}

// ZxdgOutputV1DoneEvent is the all information about the output have been sent
type ZxdgOutputV1DoneEvent struct {
}

// ZxdgOutputV1NameEvent is the name of this output
type ZxdgOutputV1NameEvent struct {
	// Name is the output name
	Name string
}

// ZxdgOutputV1DescriptionEvent is the human-readable description of this output
type ZxdgOutputV1DescriptionEvent struct {
	// Description is the output description
	Description string
}

// ZxdgOutputV1LogicalPositionHandler is the handler interface for ZxdgOutputV1LogicalPositionEvent
type ZxdgOutputV1LogicalPositionHandler interface {
	HandleZxdgOutputV1LogicalPosition(ZxdgOutputV1LogicalPositionEvent)
}

// AddLogicalPositionHandler adds the LogicalPosition handler
func (p *ZxdgOutputV1) AddLogicalPositionHandler(h ZxdgOutputV1LogicalPositionHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZxdgOutputV1LogicalPositions[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveLogicalPositionHandler removes the LogicalPosition handler
func (p *ZxdgOutputV1) RemoveLogicalPositionHandler(h ZxdgOutputV1LogicalPositionHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZxdgOutputV1LogicalPositions, h)
}

// ZxdgOutputV1LogicalSizeHandler is the handler interface for ZxdgOutputV1LogicalSizeEvent
type ZxdgOutputV1LogicalSizeHandler interface {
	HandleZxdgOutputV1LogicalSize(ZxdgOutputV1LogicalSizeEvent)
}

// AddLogicalSizeHandler adds the LogicalSize handler
func (p *ZxdgOutputV1) AddLogicalSizeHandler(h ZxdgOutputV1LogicalSizeHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZxdgOutputV1LogicalSizes[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveLogicalSizeHandler removes the LogicalSize handler
func (p *ZxdgOutputV1) RemoveLogicalSizeHandler(h ZxdgOutputV1LogicalSizeHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZxdgOutputV1LogicalSizes, h)
}

// ZxdgOutputV1DoneHandler is the handler interface for ZxdgOutputV1DoneEvent
type ZxdgOutputV1DoneHandler interface {
	HandleZxdgOutputV1Done(ZxdgOutputV1DoneEvent)
}

// AddDoneHandler adds the Done handler
func (p *ZxdgOutputV1) AddDoneHandler(h ZxdgOutputV1DoneHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZxdgOutputV1Dones[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveDoneHandler removes the Done handler
func (p *ZxdgOutputV1) RemoveDoneHandler(h ZxdgOutputV1DoneHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZxdgOutputV1Dones, h)
}

// ZxdgOutputV1NameHandler is the handler interface for ZxdgOutputV1NameEvent
type ZxdgOutputV1NameHandler interface {
	HandleZxdgOutputV1Name(ZxdgOutputV1NameEvent)
}

// AddNameHandler adds the Name handler
func (p *ZxdgOutputV1) AddNameHandler(h ZxdgOutputV1NameHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZxdgOutputV1Names[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveNameHandler removes the Name handler
func (p *ZxdgOutputV1) RemoveNameHandler(h ZxdgOutputV1NameHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZxdgOutputV1Names, h)
}

// ZxdgOutputV1DescriptionHandler is the handler interface for ZxdgOutputV1DescriptionEvent
type ZxdgOutputV1DescriptionHandler interface {
	HandleZxdgOutputV1Description(ZxdgOutputV1DescriptionEvent)
}

// AddDescriptionHandler adds the Description handler
func (p *ZxdgOutputV1) AddDescriptionHandler(h ZxdgOutputV1DescriptionHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZxdgOutputV1Descriptions[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveDescriptionHandler removes the Description handler
func (p *ZxdgOutputV1) RemoveDescriptionHandler(h ZxdgOutputV1DescriptionHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZxdgOutputV1Descriptions, h)
}
