// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: xdg-system-bell-v1.xml
// Do not edit

// Package wlr implements the xdg_system_bell_v1 protocol
package wlr

import ()

// XdgSystemBellV1 system bell
type XdgSystemBellV1 struct {
	BaseProxy
}

// NewXdgSystemBellV1 is a constructor for the XdgSystemBellV1 object
func NewXdgSystemBellV1(ctx *Context) *XdgSystemBellV1 {
	ret := new(XdgSystemBellV1)
	ctx.Register(ret)
	return ret
}

// Destroy destroy the system bell object
func (p *XdgSystemBellV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// Ring ring the system bell
func (p *XdgSystemBellV1) Ring(Surface *Surface) error {

	return p.Context().SendRequest(p, 1, Surface)
}

// Dispatch dispatches event for object XdgSystemBellV1
func (p *XdgSystemBellV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}
