// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: xdg-toplevel-icon-v1.xml
// Do not edit

// Package wlr implements the xdg_toplevel_icon_v1 protocol
package wlr

import (
	"sync"
)

// ToplevelIconV1ErrorInvalidBuffer means the provided buffer does not satisfy requirements
const ToplevelIconV1ErrorInvalidBuffer = 1

// ToplevelIconV1ErrorImmutable means the icon has already been assigned to a toplevel and must not be changed
const ToplevelIconV1ErrorImmutable = 2

// ToplevelIconV1ErrorNoBuffer means the provided buffer has been destroyed before the toplevel icon
const ToplevelIconV1ErrorNoBuffer = 3

// ToplevelIconManagerV1 interface to manage toplevel icons
type ToplevelIconManagerV1 struct {
	BaseProxy
	mu                                    sync.RWMutex
	privateToplevelIconManagerV1IconSizes map[ToplevelIconManagerV1IconSizeHandler]struct{}
	privateToplevelIconManagerV1Dones     map[ToplevelIconManagerV1DoneHandler]struct{}
}

// initToplevelIconManagerV1 initializes the ToplevelIconManagerV1 object's handler maps
func (ret *ToplevelIconManagerV1) initToplevelIconManagerV1() {
	ret.privateToplevelIconManagerV1IconSizes = make(map[ToplevelIconManagerV1IconSizeHandler]struct{})
	ret.privateToplevelIconManagerV1Dones = make(map[ToplevelIconManagerV1DoneHandler]struct{})
}

// NewToplevelIconManagerV1 is a constructor for the ToplevelIconManagerV1 object
func NewToplevelIconManagerV1(ctx *Context) *ToplevelIconManagerV1 {
	ret := new(ToplevelIconManagerV1)
	ret.initToplevelIconManagerV1()
	ctx.Register(ret)
	return ret
}

// Destroy destroy the toplevel icon manager
func (p *ToplevelIconManagerV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// CreateIcon create a new icon instance
func (p *ToplevelIconManagerV1) CreateIcon() (*ToplevelIconV1, error) {
	retId := NewToplevelIconV1(p.Context())
	return retId, p.Context().SendRequest(p, 1, retId)
}

// SetIcon set an icon on a toplevel window
func (p *ToplevelIconManagerV1) SetIcon(Toplevel *Toplevel, Icon *ToplevelIconV1) error {

	return p.Context().SendRequest(p, 2, Toplevel, Icon)
}

// Dispatch dispatches event for object ToplevelIconManagerV1
func (p *ToplevelIconManagerV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateToplevelIconManagerV1IconSizes) > 0 {
			ev := ToplevelIconManagerV1IconSizeEvent{}
			ev.Size = event.Int32()
			p.mu.RLock()
			for h := range p.privateToplevelIconManagerV1IconSizes {
				h.HandleToplevelIconManagerV1IconSize(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateToplevelIconManagerV1Dones) > 0 {
			ev := ToplevelIconManagerV1DoneEvent{}
			p.mu.RLock()
			for h := range p.privateToplevelIconManagerV1Dones {
				h.HandleToplevelIconManagerV1Done(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ToplevelIconManagerV1IconSizeEvent is the describes a supported & preferred icon size
type ToplevelIconManagerV1IconSizeEvent struct {
	// Size is the the edge size of the square icon in surface-local coordinates, e.g. 64
	Size int32
}

// ToplevelIconManagerV1DoneEvent is the all information has been sent
type ToplevelIconManagerV1DoneEvent struct {
}

// ToplevelIconManagerV1IconSizeHandler is the handler interface for ToplevelIconManagerV1IconSizeEvent
type ToplevelIconManagerV1IconSizeHandler interface {
	HandleToplevelIconManagerV1IconSize(ToplevelIconManagerV1IconSizeEvent)
}

// AddIconSizeHandler adds the IconSize handler
func (p *ToplevelIconManagerV1) AddIconSizeHandler(h ToplevelIconManagerV1IconSizeHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateToplevelIconManagerV1IconSizes[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveIconSizeHandler removes the IconSize handler
func (p *ToplevelIconManagerV1) RemoveIconSizeHandler(h ToplevelIconManagerV1IconSizeHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateToplevelIconManagerV1IconSizes, h)
}

// ToplevelIconManagerV1DoneHandler is the handler interface for ToplevelIconManagerV1DoneEvent
type ToplevelIconManagerV1DoneHandler interface {
	HandleToplevelIconManagerV1Done(ToplevelIconManagerV1DoneEvent)
}

// AddDoneHandler adds the Done handler
func (p *ToplevelIconManagerV1) AddDoneHandler(h ToplevelIconManagerV1DoneHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateToplevelIconManagerV1Dones[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveDoneHandler removes the Done handler
func (p *ToplevelIconManagerV1) RemoveDoneHandler(h ToplevelIconManagerV1DoneHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateToplevelIconManagerV1Dones, h)
}

// ToplevelIconV1 a toplevel window icon
type ToplevelIconV1 struct {
	BaseProxy
}

// NewToplevelIconV1 is a constructor for the ToplevelIconV1 object
func NewToplevelIconV1(ctx *Context) *ToplevelIconV1 {
	ret := new(ToplevelIconV1)
	ctx.Register(ret)
	return ret
}

// Destroy destroy the icon object
func (p *ToplevelIconV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// SetName set an icon name
func (p *ToplevelIconV1) SetName(IconName string) error {

	return p.Context().SendRequest(p, 1, IconName)
}

// AddBuffer add icon data from a pixel buffer
func (p *ToplevelIconV1) AddBuffer(Buffer *Buffer, Scale int32) error {

	return p.Context().SendRequest(p, 2, Buffer, Scale)
}

// Dispatch dispatches event for object ToplevelIconV1
func (p *ToplevelIconV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}
