// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: xdg-foreign-unstable-v2.xml
// Do not edit

// Package wlr implements the xdg_foreign_unstable_v2 protocol
package wlr

import (
	"sync"
)

// ZxdgExporterV2ErrorInvalidSurface means surface is not an xdg_toplevel
const ZxdgExporterV2ErrorInvalidSurface = 0

// ZxdgImportedV2ErrorInvalidSurface means surface is not an xdg_toplevel
const ZxdgImportedV2ErrorInvalidSurface = 0

// ZxdgExporterV2 interface for exporting surfaces
type ZxdgExporterV2 struct {
	BaseProxy
}

// NewZxdgExporterV2 is a constructor for the ZxdgExporterV2 object
func NewZxdgExporterV2(ctx *Context) *ZxdgExporterV2 {
	ret := new(ZxdgExporterV2)
	ctx.Register(ret)
	return ret
}

// Destroy destroy the xdg_exporter object
func (p *ZxdgExporterV2) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// ExportToplevel export a toplevel surface
func (p *ZxdgExporterV2) ExportToplevel(Surface *Surface) (*ZxdgExportedV2, error) {
	retId := NewZxdgExportedV2(p.Context())
	return retId, p.Context().SendRequest(p, 1, retId, Surface)
}

// Dispatch dispatches event for object ZxdgExporterV2
func (p *ZxdgExporterV2) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// ZxdgImporterV2 interface for importing surfaces
type ZxdgImporterV2 struct {
	BaseProxy
}

// NewZxdgImporterV2 is a constructor for the ZxdgImporterV2 object
func NewZxdgImporterV2(ctx *Context) *ZxdgImporterV2 {
	ret := new(ZxdgImporterV2)
	ctx.Register(ret)
	return ret
}

// Destroy destroy the xdg_importer object
func (p *ZxdgImporterV2) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// ImportToplevel import a toplevel surface
func (p *ZxdgImporterV2) ImportToplevel(Handle string) (*ZxdgImportedV2, error) {
	retId := NewZxdgImportedV2(p.Context())
	return retId, p.Context().SendRequest(p, 1, retId, Handle)
}

// Dispatch dispatches event for object ZxdgImporterV2
func (p *ZxdgImporterV2) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// ZxdgExportedV2 an exported surface handle
type ZxdgExportedV2 struct {
	BaseProxy
	mu                           sync.RWMutex
	privateZxdgExportedV2Handles map[ZxdgExportedV2HandleHandler]struct{}
}

// initZxdgExportedV2 initializes the ZxdgExportedV2 object's handler maps
func (ret *ZxdgExportedV2) initZxdgExportedV2() {
	ret.privateZxdgExportedV2Handles = make(map[ZxdgExportedV2HandleHandler]struct{})
}

// NewZxdgExportedV2 is a constructor for the ZxdgExportedV2 object
func NewZxdgExportedV2(ctx *Context) *ZxdgExportedV2 {
	ret := new(ZxdgExportedV2)
	ret.initZxdgExportedV2()
	ctx.Register(ret)
	return ret
}

// Destroy unexport the exported surface
func (p *ZxdgExportedV2) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// Dispatch dispatches event for object ZxdgExportedV2
func (p *ZxdgExportedV2) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZxdgExportedV2Handles) > 0 {
			ev := ZxdgExportedV2HandleEvent{}
			ev.Handle = event.String()
			p.mu.RLock()
			for h := range p.privateZxdgExportedV2Handles {
				h.HandleZxdgExportedV2Handle(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ZxdgExportedV2HandleEvent is the the exported surface handle
type ZxdgExportedV2HandleEvent struct {
	// Handle is the the exported surface handle
	Handle string
}

// ZxdgExportedV2HandleHandler is the handler interface for ZxdgExportedV2HandleEvent
type ZxdgExportedV2HandleHandler interface {
	HandleZxdgExportedV2Handle(ZxdgExportedV2HandleEvent)
}

// AddHandleHandler adds the Handle handler
func (p *ZxdgExportedV2) AddHandleHandler(h ZxdgExportedV2HandleHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZxdgExportedV2Handles[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveHandleHandler removes the Handle handler
func (p *ZxdgExportedV2) RemoveHandleHandler(h ZxdgExportedV2HandleHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZxdgExportedV2Handles, h)
}

// ZxdgImportedV2 an imported surface handle
type ZxdgImportedV2 struct {
	BaseProxy
	mu                              sync.RWMutex
	privateZxdgImportedV2Destroyeds map[ZxdgImportedV2DestroyedHandler]struct{}
}

// initZxdgImportedV2 initializes the ZxdgImportedV2 object's handler maps
func (ret *ZxdgImportedV2) initZxdgImportedV2() {
	ret.privateZxdgImportedV2Destroyeds = make(map[ZxdgImportedV2DestroyedHandler]struct{})
}

// NewZxdgImportedV2 is a constructor for the ZxdgImportedV2 object
func NewZxdgImportedV2(ctx *Context) *ZxdgImportedV2 {
	ret := new(ZxdgImportedV2)
	ret.initZxdgImportedV2()
	ctx.Register(ret)
	return ret
}

// Destroy destroy the xdg_imported object
func (p *ZxdgImportedV2) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// SetParentOf set as the parent of some surface
func (p *ZxdgImportedV2) SetParentOf(Surface *Surface) error {

	return p.Context().SendRequest(p, 1, Surface)
}

// Dispatch dispatches event for object ZxdgImportedV2
func (p *ZxdgImportedV2) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZxdgImportedV2Destroyeds) > 0 {
			ev := ZxdgImportedV2DestroyedEvent{}
			p.mu.RLock()
			for h := range p.privateZxdgImportedV2Destroyeds {
				h.HandleZxdgImportedV2Destroyed(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ZxdgImportedV2DestroyedEvent is the the imported surface handle has been destroyed
type ZxdgImportedV2DestroyedEvent struct {
}

// ZxdgImportedV2DestroyedHandler is the handler interface for ZxdgImportedV2DestroyedEvent
type ZxdgImportedV2DestroyedHandler interface {
	HandleZxdgImportedV2Destroyed(ZxdgImportedV2DestroyedEvent)
}

// AddDestroyedHandler adds the Destroyed handler
func (p *ZxdgImportedV2) AddDestroyedHandler(h ZxdgImportedV2DestroyedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZxdgImportedV2Destroyeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveDestroyedHandler removes the Destroyed handler
func (p *ZxdgImportedV2) RemoveDestroyedHandler(h ZxdgImportedV2DestroyedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateZxdgImportedV2Destroyeds, h)
}
