// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: xdg-dialog-v1.xml
// Do not edit

// Package wlr implements the xdg_dialog_v1 protocol
package wlr

import ()

// WmDialogV1ErrorAlreadyUsed means the xdg_toplevel object has already been used to create a xdg_dialog_v1
const WmDialogV1ErrorAlreadyUsed = 0

// WmDialogV1 create dialogs related to other toplevels
type WmDialogV1 struct {
	BaseProxy
}

// NewWmDialogV1 is a constructor for the WmDialogV1 object
func NewWmDialogV1(ctx *Context) *WmDialogV1 {
	ret := new(WmDialogV1)
	ctx.Register(ret)
	return ret
}

// Destroy destroy the dialog manager object
func (p *WmDialogV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// GetDialog create a dialog object
func (p *WmDialogV1) GetDialog(Toplevel *Toplevel) (*DialogV1, error) {
	retId := NewDialogV1(p.Context())
	return retId, p.Context().SendRequest(p, 1, retId, Toplevel)
}

// Dispatch dispatches event for object WmDialogV1
func (p *WmDialogV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// DialogV1 dialog object
type DialogV1 struct {
	BaseProxy
}

// NewDialogV1 is a constructor for the DialogV1 object
func NewDialogV1(ctx *Context) *DialogV1 {
	ret := new(DialogV1)
	ctx.Register(ret)
	return ret
}

// Destroy destroy the dialog object
func (p *DialogV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// SetModal mark dialog as modal
func (p *DialogV1) SetModal() error {

	return p.Context().SendRequest(p, 1)
}

// UnsetModal mark dialog as not modal
func (p *DialogV1) UnsetModal() error {

	return p.Context().SendRequest(p, 2)
}

// Dispatch dispatches event for object DialogV1
func (p *DialogV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}
