// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: xdg-activation-v1.xml
// Do not edit

// Package wlr implements the xdg_activation_v1 protocol
package wlr

import (
	"sync"
)

// ActivationTokenV1ErrorAlreadyUsed means The token has already been used previously
const ActivationTokenV1ErrorAlreadyUsed = 0

// ActivationV1 interface for activating surfaces
type ActivationV1 struct {
	BaseProxy
}

// NewActivationV1 is a constructor for the ActivationV1 object
func NewActivationV1(ctx *Context) *ActivationV1 {
	ret := new(ActivationV1)
	ctx.Register(ret)
	return ret
}

// Destroy destroy the xdg_activation object
func (p *ActivationV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// GetActivationToken requests a token
func (p *ActivationV1) GetActivationToken() (*ActivationTokenV1, error) {
	retId := NewActivationTokenV1(p.Context())
	return retId, p.Context().SendRequest(p, 1, retId)
}

// Activate notify new interaction being available
func (p *ActivationV1) Activate(Token string, Surface *Surface) error {

	return p.Context().SendRequest(p, 2, Token, Surface)
}

// Dispatch dispatches event for object ActivationV1
func (p *ActivationV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// ActivationTokenV1 an exported activation handle
type ActivationTokenV1 struct {
	BaseProxy
	mu                            sync.RWMutex
	privateActivationTokenV1Dones map[ActivationTokenV1DoneHandler]struct{}
}

// initActivationTokenV1 initializes the ActivationTokenV1 object's handler maps
func (ret *ActivationTokenV1) initActivationTokenV1() {
	ret.privateActivationTokenV1Dones = make(map[ActivationTokenV1DoneHandler]struct{})
}

// NewActivationTokenV1 is a constructor for the ActivationTokenV1 object
func NewActivationTokenV1(ctx *Context) *ActivationTokenV1 {
	ret := new(ActivationTokenV1)
	ret.initActivationTokenV1()
	ctx.Register(ret)
	return ret
}

// SetSerial specifies the seat and serial of the activating event
func (p *ActivationTokenV1) SetSerial(Serial uint32, Seat *Seat) error {

	return p.Context().SendRequest(p, 0, Serial, Seat)
}

// SetAppId specifies the application being activated
func (p *ActivationTokenV1) SetAppId(AppId string) error {

	return p.Context().SendRequest(p, 1, AppId)
}

// SetSurface specifies the surface requesting activation
func (p *ActivationTokenV1) SetSurface(Surface *Surface) error {

	return p.Context().SendRequest(p, 2, Surface)
}

// Commit issues the token request
func (p *ActivationTokenV1) Commit() error {

	return p.Context().SendRequest(p, 3)
}

// Destroy destroy the xdg_activation_token_v1 object
func (p *ActivationTokenV1) Destroy() error {

	return p.Context().SendRequest(p, 4)
}

// Dispatch dispatches event for object ActivationTokenV1
func (p *ActivationTokenV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateActivationTokenV1Dones) > 0 {
			ev := ActivationTokenV1DoneEvent{}
			ev.Token = event.String()
			p.mu.RLock()
			for h := range p.privateActivationTokenV1Dones {
				h.HandleActivationTokenV1Done(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// ActivationTokenV1DoneEvent is the the exported activation token
type ActivationTokenV1DoneEvent struct {
	// Token is the the exported activation token
	Token string
}

// ActivationTokenV1DoneHandler is the handler interface for ActivationTokenV1DoneEvent
type ActivationTokenV1DoneHandler interface {
	HandleActivationTokenV1Done(ActivationTokenV1DoneEvent)
}

// AddDoneHandler adds the Done handler
func (p *ActivationTokenV1) AddDoneHandler(h ActivationTokenV1DoneHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateActivationTokenV1Dones[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveDoneHandler removes the Done handler
func (p *ActivationTokenV1) RemoveDoneHandler(h ActivationTokenV1DoneHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateActivationTokenV1Dones, h)
}
