// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: zwlr-virtual-pointer-unstable-v1.xml
// Do not edit

// Package wlr implements the wlr_virtual_pointer_unstable_v1 protocol
package wlr

import ()

// ZwlrVirtualPointerV1ErrorInvalidAxis means client sent invalid axis enumeration value
const ZwlrVirtualPointerV1ErrorInvalidAxis = 0

// ZwlrVirtualPointerV1ErrorInvalidAxisSource means client sent invalid axis source enumeration value
const ZwlrVirtualPointerV1ErrorInvalidAxisSource = 1

// ZwlrVirtualPointerV1 virtual pointer
type ZwlrVirtualPointerV1 struct {
	BaseProxy
}

// NewZwlrVirtualPointerV1 is a constructor for the ZwlrVirtualPointerV1 object
func NewZwlrVirtualPointerV1(ctx *Context) *ZwlrVirtualPointerV1 {
	ret := new(ZwlrVirtualPointerV1)
	ctx.Register(ret)
	return ret
}

// Motion pointer relative motion event
func (p *ZwlrVirtualPointerV1) Motion(Time uint32, Dx float32, Dy float32) error {

	return p.Context().SendRequest(p, 0, Time, Dx, Dy)
}

// MotionAbsolute pointer absolute motion event
func (p *ZwlrVirtualPointerV1) MotionAbsolute(Time uint32, X uint32, Y uint32, XExtent uint32, YExtent uint32) error {

	return p.Context().SendRequest(p, 1, Time, X, Y, XExtent, YExtent)
}

// Button button event
func (p *ZwlrVirtualPointerV1) Button(Time uint32, Button uint32, State uint32) error {

	return p.Context().SendRequest(p, 2, Time, Button, State)
}

// Axis axis event
func (p *ZwlrVirtualPointerV1) Axis(Time uint32, Axis uint32, Value float32) error {

	return p.Context().SendRequest(p, 3, Time, Axis, Value)
}

// Frame end of a pointer event sequence
func (p *ZwlrVirtualPointerV1) Frame() error {

	return p.Context().SendRequest(p, 4)
}

// AxisSource axis source event
func (p *ZwlrVirtualPointerV1) AxisSource(AxisSource uint32) error {

	return p.Context().SendRequest(p, 5, AxisSource)
}

// AxisStop axis stop event
func (p *ZwlrVirtualPointerV1) AxisStop(Time uint32, Axis uint32) error {

	return p.Context().SendRequest(p, 6, Time, Axis)
}

// AxisDiscrete axis click event
func (p *ZwlrVirtualPointerV1) AxisDiscrete(Time uint32, Axis uint32, Value float32, Discrete int32) error {

	return p.Context().SendRequest(p, 7, Time, Axis, Value, Discrete)
}

// Destroy destroy the virtual pointer object
func (p *ZwlrVirtualPointerV1) Destroy() error {

	return p.Context().SendRequest(p, 8)
}

// Dispatch dispatches event for object ZwlrVirtualPointerV1
func (p *ZwlrVirtualPointerV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// ZwlrVirtualPointerManagerV1 virtual pointer manager
type ZwlrVirtualPointerManagerV1 struct {
	BaseProxy
}

// NewZwlrVirtualPointerManagerV1 is a constructor for the ZwlrVirtualPointerManagerV1 object
func NewZwlrVirtualPointerManagerV1(ctx *Context) *ZwlrVirtualPointerManagerV1 {
	ret := new(ZwlrVirtualPointerManagerV1)
	ctx.Register(ret)
	return ret
}

// CreateVirtualPointer Create a new virtual pointer
func (p *ZwlrVirtualPointerManagerV1) CreateVirtualPointer(Seat *Seat) (*ZwlrVirtualPointerV1, error) {
	retId := NewZwlrVirtualPointerV1(p.Context())
	return retId, p.Context().SendRequest(p, 0, Seat, retId)
}

// Destroy destroy the virtual pointer manager
func (p *ZwlrVirtualPointerManagerV1) Destroy() error {

	return p.Context().SendRequest(p, 1)
}

// CreateVirtualPointerWithOutput Create a new virtual pointer
func (p *ZwlrVirtualPointerManagerV1) CreateVirtualPointerWithOutput(Seat *Seat, Output *Output) (*ZwlrVirtualPointerV1, error) {
	retId := NewZwlrVirtualPointerV1(p.Context())
	return retId, p.Context().SendRequest(p, 2, Seat, Output, retId)
}

// Dispatch dispatches event for object ZwlrVirtualPointerManagerV1
func (p *ZwlrVirtualPointerManagerV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}
