// Code generated by github.com/neurlang/wayland/cmd/wayland-scanner. DO NOT EDIT.
// This file is autogenerated from: wlr/zwp-virtual-keyboard-unstable-v1.xml
// Do not edit

// Package wlr implements the virtual_keyboard_unstable_v1 protocol
package wlr

import ()

// ZwpKeyboardV1ErrorNoKeymap means No keymap was set
const ZwpKeyboardV1ErrorNoKeymap = 0

// ZwpKeyboardManagerV1ErrorUnauthorized means client not authorized to use the interface
const ZwpKeyboardManagerV1ErrorUnauthorized = 0

// ZwpKeyboardV1 virtual keyboard
type ZwpKeyboardV1 struct {
	BaseProxy
}

// NewZwpKeyboardV1 is a constructor for the ZwpKeyboardV1 object
func NewZwpKeyboardV1(ctx *Context) *ZwpKeyboardV1 {
	ret := new(ZwpKeyboardV1)
	ctx.Register(ret)
	return ret
}

// Keymap keyboard mapping
func (p *ZwpKeyboardV1) Keymap(Format uint32, Fd uintptr, Size uint32) error {

	return p.Context().SendRequest(p, 0, Format, Fd, Size)
}

// Key key event
func (p *ZwpKeyboardV1) Key(Time uint32, Key uint32, State uint32) error {

	return p.Context().SendRequest(p, 1, Time, Key, State)
}

// Modifiers modifier and group state
func (p *ZwpKeyboardV1) Modifiers(ModsDepressed uint32, ModsLatched uint32, ModsLocked uint32, Group uint32) error {

	return p.Context().SendRequest(p, 2, ModsDepressed, ModsLatched, ModsLocked, Group)
}

// Destroy destroy the virtual keyboard keyboard object
func (p *ZwpKeyboardV1) Destroy() error {

	return p.Context().SendRequest(p, 3)
}

// Dispatch dispatches event for object ZwpKeyboardV1
func (p *ZwpKeyboardV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// ZwpKeyboardManagerV1 virtual keyboard manager
type ZwpKeyboardManagerV1 struct {
	BaseProxy
}

// NewZwpKeyboardManagerV1 is a constructor for the ZwpKeyboardManagerV1 object
func NewZwpKeyboardManagerV1(ctx *Context) *ZwpKeyboardManagerV1 {
	ret := new(ZwpKeyboardManagerV1)
	ctx.Register(ret)
	return ret
}

// CreateKeyboard Create a new virtual keyboard
func (p *ZwpKeyboardManagerV1) CreateKeyboard(Seat *Seat) (*ZwpKeyboardV1, error) {
	retId := NewZwpKeyboardV1(p.Context())
	return retId, p.Context().SendRequest(p, 0, Seat, retId)
}

// Dispatch dispatches event for object ZwpKeyboardManagerV1
func (p *ZwpKeyboardManagerV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}
